Route112_CableCarStation_MapScripts::

Route112_CableCarStation_OnTransition:

Route112_CableCarStation_EventScript_MoveAttendantAside::

Route112_CableCarStation_OnFrame:

Route112_CableCarStation_EventScript_ExitCableCar::

Route112_CableCarStation_EventScript_Attendant::

Route112_CableCarStation_EventScript_RideCableCar::

Route112_CableCarStation_EventScript_DeclineRide::

Route112_CableCarStation_Movement_LeadPlayerToCableCar:

Route112_CableCarStation_Movement_FollowPlayerOutFromCableCar:

Route112_CableCarStation_Movement_BoardCableCar:

Route112_CableCarStation_Movement_ExitCableCar:

Route112_CableCarStation_Text_CableCarReadyGetOn:
	.string "The CABLE CAR is ready to go up.\n"
	.string "Would you like to be on it?$"

Route112_CableCarStation_Text_StepThisWay:
	.string "Please step this way.$"

Route112_CableCarStation_Text_RideAnotherTime:
	.string "Please ride with us another time.$"

