Route110_TrickHousePuzzle7_MapScripts::

@ Puzzle Room 7 in RSE uses whatever puzzle Mossdeep Gym uses
@ Because Mossdeep Gym was redesigned for Emerald, theres a good deal of leftover script from the old R/S puzzle

Route110_TrickHousePuzzle7_OnResume:

Route110_TrickHousePuzzle7_EventScript_UpdateSwitchMetatiles::

@ Leftover from R/S, none of the below metatile scripts are ever called
Route110_TrickHousePuzzle7_EventScript_SetSwitch1MetatilesOn::

Route110_TrickHousePuzzle7_EventScript_SetSwitch2MetatilesOn::

Route110_TrickHousePuzzle7_EventScript_SetSwitch3MetatilesOn::

Route110_TrickHousePuzzle7_EventScript_SetSwitch4MetatilesOn::

Route110_TrickHousePuzzle7_EventScript_SetSwitch5MetatilesOn::

Route110_TrickHousePuzzle7_EventScript_SetSwitch1MetatilesOff::

Route110_TrickHousePuzzle7_EventScript_SetSwitch2MetatilesOff::

Route110_TrickHousePuzzle7_EventScript_SetSwitch3MetatilesOff::

Route110_TrickHousePuzzle7_EventScript_SetSwitch4MetatilesOff::

Route110_TrickHousePuzzle7_EventScript_SetSwitch5MetatilesOff::

Route110_TrickHousePuzzle7_OnTransition:

Route110_TrickHousePuzzle7_EventScript_TeleportedTransition::

Route110_TrickHousePuzzle7_OnLoad:

Route110_TrickHousePuzzle7_OnFrame:

Route110_TrickHousePuzzle7_EventScript_ClearState2::

Route110_TrickHousePuzzle7_EventScript_Scroll::

Route110_TrickHousePuzzle7_EventScript_FoundScroll::

@ Unused, leftover from R/S
Route110_TrickHousePuzzle7_EventScript_TeleportPad::

@ All the below switch scripts are unused leftover from R/S
Route110_TrickHousePuzzle7_EventScript_Switch1::

Route110_TrickHousePuzzle7_EventScript_Switch2::

Route110_TrickHousePuzzle7_EventScript_Switch3::

Route110_TrickHousePuzzle7_EventScript_Switch4::

Route110_TrickHousePuzzle7_EventScript_Switch5::

@ All the below switch scripts are unused leftover from R/S
Route110_TrickHousePuzzle7_EventScript_SetSwitch1On::

Route110_TrickHousePuzzle7_EventScript_SetSwitch1Off::

Route110_TrickHousePuzzle7_EventScript_SetSwitch2On::

Route110_TrickHousePuzzle7_EventScript_SetSwitch2Off::

Route110_TrickHousePuzzle7_EventScript_SetSwitch3On::

Route110_TrickHousePuzzle7_EventScript_SetSwitch3Off::

Route110_TrickHousePuzzle7_EventScript_SetSwitch4On::

Route110_TrickHousePuzzle7_EventScript_SetSwitch4Off::

Route110_TrickHousePuzzle7_EventScript_SetSwitch5On::

Route110_TrickHousePuzzle7_EventScript_SetSwitch5Off::

@ From here is where the new, actually used puzzle scripts begin
Route110_TrickHousePuzzle7_EventScript_YellowButton::

Route110_TrickHousePuzzle7_EventScript_BlueButton::

Route110_TrickHousePuzzle7_EventScript_GreenButton::

Route110_TrickHousePuzzle7_EventScript_PurpleButton::

@ Unused
Route110_TrickHousePuzzle7_EventScript_RedButton::

Route110_TrickHousePuzzle7_EventScript_Joshua::

Route110_TrickHousePuzzle7_EventScript_Patricia::

Route110_TrickHousePuzzle7_EventScript_Alexis::

Route110_TrickHousePuzzle7_EventScript_Mariela::

Route110_TrickHousePuzzle7_EventScript_Alvaro::

Route110_TrickHousePuzzle7_EventScript_Everett::

Route110_TrickHousePuzzle7_Text_WroteSecretCodeLockOpened::
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is huggable.”\n"
	.string "… … … … … … … …\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle7_Text_JoshuaIntro:
	.string "The TRICK MASTER always vanishes\n"
	.string "like smoke. How does he do it?$"

Route110_TrickHousePuzzle7_Text_JoshuaDefeat:
	.string "Aiyeeeh! You're much too strong!\n"
	.string "How do you do it?$"

Route110_TrickHousePuzzle7_Text_JoshuaPostBattle:
	.string "I wish I could appear and disappear as\n"
	.string "if I were smoke, too.$"

Route110_TrickHousePuzzle7_Text_PatriciaIntro:
	.string "Going around the same spot…\n"
	.string "It begets ill fortune…$"

Route110_TrickHousePuzzle7_Text_PatriciaDefeat:
	.string "Defeated!\n"
	.string "It's a bad sign…$"

Route110_TrickHousePuzzle7_Text_PatriciaPostBattle:
	.string "I've circled the same spot over ten\n"
	.string "times now… It's ill fortune…$"

Route110_TrickHousePuzzle7_Text_AlexisIntro:
	.string "Whoever wins will get through here\n"
	.string "first. That's the feeling I get.$"

Route110_TrickHousePuzzle7_Text_AlexisDefeat:
	.string "Oh!\n"
	.string "Well, go ahead, then!$"

Route110_TrickHousePuzzle7_Text_AlexisPostBattle:
	.string "You're solving all the puzzles in the\n"
	.string "TRICK HOUSE. That's the feeling I get.$"

Route110_TrickHousePuzzle7_Text_MarielaIntro:
	.string "Nufufufu, here at last!\n"
	.string "Let's get right with it!$"

Route110_TrickHousePuzzle7_Text_MarielaDefeat:
	.string "You're so casual about winning!$"

Route110_TrickHousePuzzle7_Text_MarielaPostBattle:
	.string "Humph! I'm not upset!\n"
	.string "Not me!$"

Route110_TrickHousePuzzle7_Text_AlvaroIntro:
	.string "I ever so closely watched you coming!$"

Route110_TrickHousePuzzle7_Text_AlvaroDefeat:
	.string "This outcome I didn't see coming…$"

Route110_TrickHousePuzzle7_Text_AlvaroPostBattle:
	.string "Well, anyway, we both picked a weird\n"
	.string "place to get acquainted.\p"
	.string "As one weirdo to another,\n"
	.string "let's do our best!$"

Route110_TrickHousePuzzle7_Text_EverettIntro:
	.string "It's awfully cramped in here…$"

Route110_TrickHousePuzzle7_Text_EverettDefeat:
	.string "Oh, yes, strong you are.$"

Route110_TrickHousePuzzle7_Text_EverettPostBattle:
	.string "I was hoping to switch places with you\n"
	.string "when I beat you, but…$"

