Route110_TrickHouseEntrance_MapScripts::


Route110_TrickHouseEntrance_OnTransition:

Route110_TrickHouseEntrance_EventScript_SetReadyToGiveReward::

Route110_TrickHouseEntrance_EventScript_ReadyToGiveTentReward::

Route110_TrickHouseEntrance_EventScript_EnterFromCorridor::

Route110_TrickHouseEntrance_EventScript_CheckReadyForNextPuzzle::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle2::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle3::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle4::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle5::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle6::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle7::

Route110_TrickHouseEntrance_EventScript_CheckReadyForPuzzle8::

Route110_TrickHouseEntrance_EventScript_FinishedPuzzles::

Route110_TrickHouseEntrance_EventScript_NotReadyForPuzzle::

Route110_TrickHouseEntrance_EventScript_MoveTrickMasterToDoor::

Route110_TrickHouseEntrance_EventScript_ReadyBeingWatchedTrigger::

Route110_TrickHouseEntrance_EventScript_SetNotBeingWatched1::

Route110_TrickHouseEntrance_EventScript_SetNotBeingWatched2::

Route110_TrickHouseEntrance_EventScript_SetNotBeingWatched3::

Route110_TrickHouseEntrance_OnWarp:

Route110_TrickHouseEntrance_EventScript_TrickMasterFound::

Route110_TrickHouseEntrance_EventScript_SetTrickMasterHidingSpot::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle1::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle2::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle3::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle4::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle5::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle6::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle7::

Route110_TrickHouseEntrance_EventScript_SetHidingSpotPuzzle8::

Route110_TrickHouseEntrance_EventScript_RemoveTrickMaster::

Route110_TrickHouseEntrance_EventScript_SetTrickMasterFacingDoor::

Route110_TrickHouseEntrance_EventScript_SetTrickMasterInFrontOfDoor::

Route110_TrickHouseEntrance_OnFrame:

Route110_TrickHouseEntrance_EventScript_BeginChallenge::

Route110_TrickHouseEntrance_EventScript_UnusedRelease::

Route110_TrickHouseEntrance_EventScript_TrickMaster::

Route110_TrickHouseEntrance_EventScript_FoundTrickMaster::

Route110_TrickHouseEntrance_EventScript_FoundBeneathDesk::

Route110_TrickHouseEntrance_EventScript_FoundBehindTree::

Route110_TrickHouseEntrance_EventScript_FoundInDresser::

Route110_TrickHouseEntrance_EventScript_FoundBeyondWindow::

Route110_TrickHouseEntrance_EventScript_FoundInPlanter::

Route110_TrickHouseEntrance_EventScript_FoundInCupboard::

Route110_TrickHouseEntrance_EventScript_FoundBehindWindow::

Route110_TrickHouseEntrance_EventScript_FoundBeneathCushion::

Route110_TrickHouse_Movement_TrickMasterSpin:

Route110_TrickHouse_Movement_TrickMasterJumpAway:

Route110_TrickHouseEntrance_EventScript_MeetTrickMaster::

Route110_TrickHouseEntrance_EventScript_StillMakingPuzzle::

Route110_TrickHouseEntrance_EventScript_GiveReward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle1Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle2Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle3Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle4Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle5Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle6Reward::

Route110_TrickHouseEntrance_EventScript_GivePuzzle7Reward::

Route110_TrickHouseEntrance_EventScript_GotReward::

Route110_TrickHouseEntrance_EventScript_MechadollReward::

Route110_TrickHouseEntrance_EventScript_ChooseTent::

Route110_TrickHouseEntrance_EventScript_GiveRedTent::

Route110_TrickHouseEntrance_EventScript_GiveBlueTent::

Route110_TrickHouseEntrance_EventScript_ReceivedTent::

Route110_TrickHouseEntrance_EventScript_Door::

Route110_TrickHouseEntrance_EventScript_ItsAScroll::

Route110_TrickHouseEntrance_EventScript_GoInHolePrompt::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom::

Route110_TrickHouseEntrance_Movement_EnterRoom:

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom1::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom2::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom3::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom4::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom5::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom6::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom7::

Route110_TrickHouseEntrance_EventScript_EnterPuzzleRoom8::

Route110_TrickHouseEntrance_EventScript_LeftOnJourneyNote::

Route110_TrickHouseEntrance_EventScript_CheckLevelForMessage::

Route110_TrickHouseEntrance_EventScript_LeftOnJourneyNote2::

Route110_TrickHousePuzzle_EventScript_Door::

Route110_TrickHousePuzzle1_EventScript_Door::

Route110_TrickHousePuzzle2_EventScript_Door::

Route110_TrickHousePuzzle3_EventScript_Door::

Route110_TrickHousePuzzle4_EventScript_Door::

Route110_TrickHousePuzzle5_EventScript_Door::

Route110_TrickHousePuzzle6_EventScript_Door::

Route110_TrickHousePuzzle7_EventScript_Door::

Route110_TrickHousePuzzle8_EventScript_Door::

Route110_TrickHousePuzzle_EventScript_DoorLocked::

Route110_TrickHousePuzzle_EventScript_ReadScrollAgain::

Route110_TrickHousePuzzle_EventScript_FoundScroll::

Route110_TrickHouseEntrance_EventScript_TrickMasterHiding::

Route110_TrickHouseEntrance_EventScript_DoHidingSpotSparkle1::

Route110_TrickHouseEntrance_EventScript_DoHidingSpotSparkle2::

Route110_TrickHouseEntrance_EventScript_DoHidingSpotSparkle3::

Route110_TrickHouseEntrance_EventScript_DoHidingSpotSparkle::

Route110_TrickHouseEntrance_Text_YoureBeingWatched:
	.string "You're being watched…$"

Route110_TrickHouseEntrance_Text_ConcealedBeneathDesk:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beneath this desk? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBehindTree:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "behind this tree? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInDresser:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "in this dresser? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConealedBeyondWindow:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beyond this window? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInPlanter:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "in this planter? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInCupboard:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "in this cupboard? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBehindWindow:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "behind this window? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBeneathCushion:
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beneath this cushion? You're sharp!$"

Route110_TrickHouseEntrance_Text_TheyCallMeTrickMaster:
	.string "Behold!\p"
	.string "For I am the greatest living mystery\n"
	.string "of a man in all of HOENN!\l"
	.string "They call me…\p"
	.string "The TRICK MASTER!\n"
	.string "Wahahaha! Glad to meet you!$"

Route110_TrickHouseEntrance_Text_ComeToChallengeTrickHouse:
	.string "You, you've come to challenge\n"
	.string "my TRICK HOUSE, haven't you?\p"
	.string "That's why you're here, isn't it?\n"
	.string "Yes, it is!\p"
	.string "Consider your challenge accepted!\p"
	.string "Enter through the scroll there,\n"
	.string "and let your challenge commence!\p"
	.string "I shall be waiting in the back!$"

Route110_TrickHouseEntrance_Text_ItsAScroll:
	.string "It's a scroll.$"

Route110_TrickHouseEntrance_Text_GoInHoleBehindScroll:
	.string "There is a big hole behind the scroll!\p"
	.string "Want to go in?$"

Route110_TrickHouseEntrance_Text_LeavingOnJourneyNote:
	.string "There is a note affixed to the scroll…\p"
	.string "“I am leaving on a journey.\n"
	.string "Don't look for me. TRICK MASTER”$"

Route110_TrickHouseEntrance_Text_NextTimeUseThisTrick:
	.string "For the next time, I'll use this trick,\n"
	.string "and that scheme, and those ruses…\p"
	.string "Mufufufu… If I may say so, it's\n"
	.string "brilliantly difficult, even for me!$"

Route110_TrickHouseEntrance_Text_InMidstOfDevisingNewChallenges:
	.string "Hah? What?!\n"
	.string "Oh, it's you!\p"
	.string "I'm in the midst of devising new tricky\n"
	.string "challenges!\p"
	.string "It's not too much to ask for a bit more\n"
	.string "time for me to think, is it now?\l"
	.string "You wouldn't begrudge me that?\l"
	.string "Come back in a little while!$"

Route110_TrickHouseEntrance_Text_YoureHereToAcceptReward:
	.string "Ah, it's you! You're here to accept the\n"
	.string "reward from before, isn't that right?\l"
	.string "Yes, right I am!\p"
	.string "Here!\n"
	.string "I'll give it to you now!$"

Route110_TrickHouseEntrance_Text_DidYouNotComeToClaimReward:
	.string "Hah?\n"
	.string "Did you not come to claim your reward?$"

Route110_TrickHouseEntrance_Text_MechadollWhichTent:
	.string "MECHADOLL 5 I AM!\n"
	.string "IF REWARD IS NOT TAKEN BY YOU,\l"
	.string "THEN TRICK MASTER YOU CANNOT FOLLOW.\p"
	.string "RED TENT OR BLUE TENT,\n"
	.string "WHICH DO YOU PREFER?$"

Route110_TrickHouseEntrance_Text_ThenFarewell:
	.string "THEN FAREWELL.$"

Route110_TrickHouseEntrance_Text_PCFullAgain:
	.string "YOUR PC STATUS: FULL AGAIN.\n"
	.string "MEAN, YOU ARE.$"

Route110_TrickHousePuzzle_Text_FoundAScroll:
	.string "{PLAYER} found a scroll.$"

Route110_TrickHousePuzzle_Text_MemorizedSecretCode:
	.string "{PLAYER} memorized the secret code\n"
	.string "written on the scroll.$"

Route110_TrickHousePuzzle_Text_SecretCodeWrittenOnIt:
	.string "A secret code is written on it.$"

Route110_TrickHouseEntrance_Text_DoorLockedWriteSecretCodeHere:
	.string "The door is locked.\p"
	.string "…On closer inspection, this is written\n"
	.string "on it: “Write the secret code here.”$"
