Route101_MapScripts::

Route101_OnTransition:

Route101_OnFrame:

Route101_EventScript_HideMapNamePopup::

Route101_EventScript_StartBirchRescue::

Route101_EventScript_PreventExitSouth::

Route101_EventScript_PreventExitWest::

Route101_EventScript_PreventExitNorth::

Route101_Movement_PreventExitSouth:

Route101_Movement_PreventExitWest:

Route101_Movement_PreventExitNorth:

Route101_Movement_ZigzagoonChaseInCircles:

Route101_Movement_ZigzagoonChase1:

@ Leftover data? This command is unused.

Route101_Movement_ZigzagoonFaceBirch:

Route101_Movement_EnterScene:

Route101_Movement_BirchRunInCircles:

Route101_Movement_BirchRunAway1:

@ Leftover data? This command is unused.

Route101_Movement_BirchFaceZigzagoon:

Route101_Movement_Unused1:

Route101_Movement_Unused2:

Route101_EventScript_Youngster::

Route101_EventScript_Boy::

Route101_EventScript_RouteSign::

Route101_EventScript_BirchsBag::

Route101_EventScript_HideMayInBedroom::

Route101_EventScript_HideBrendanInBedroom::

Route101_Movement_BirchApproachPlayer:

Route101_Text_HelpMe:
	.string "H-help me!$"

Route101_Text_PleaseHelp:
	.string "Hello! You over there!\n"
	.string "Please! Help!\p"
	.string "In my BAG!\n"
	.string "There's a POKé BALL!$"

Route101_Text_DontLeaveMe:
	.string "Wh-Where are you going?!\n"
	.string "Don't leave me like this!$"

Route101_Text_YouSavedMe:
	.string "PROF. BIRCH: Whew…\p"
	.string "I was in the tall grass studying wild\n"
	.string "POKéMON when I was jumped.\p"
	.string "You saved me.\n"
	.string "Thanks a lot!\p"
	.string "Oh?\p"
	.string "Hi, you're {PLAYER}{KUN}!\p"
	.string "This is not the place to chat, so come\n"
	.string "by my POKéMON LAB later, okay?$"

Route101_Text_TakeTiredPokemonToPokeCenter:
	.string "If POKéMON get tired, take them to\n"
	.string "a POKéMON CENTER.\p"
	.string "There's a POKéMON CENTER in OLDALE\n"
	.string "TOWN right close by.$"

Route101_Text_WildPokemonInTallGrass:
	.string "Wild POKéMON will jump out at you in\n"
	.string "tall grass.\p"
	.string "If you want to catch POKéMON, you have\n"
	.string "to go into the tall grass and search.$"

Route101_Text_RouteSign:
	.string "ROUTE 101\n"
	.string "{UP_ARROW} OLDALE TOWN$"

