EverGrandeCity_GlaciasRoom_MapScripts::

EverGrandeCity_GlaciasRoom_OnWarp:

EverGrandeCity_GlaciasRoom_EventScript_PlayerTurnNorth::

EverGrandeCity_GlaciasRoom_OnFrame:

EverGrandeCity_GlaciasRoom_EventScript_WalkInCloseDoor::

EverGrandeCity_GlaciasRoom_OnLoad:

EverGrandeCity_GlaciasRoom_EventScript_ResetAdvanceToNextRoom::

EverGrandeCity_GlaciasRoom_EventScript_CloseDoor::

EverGrandeCity_GlaciasRoom_EventScript_Glacia::

EverGrandeCity_GlaciasRoom_EventScript_PostBattleSpeech::

EverGrandeCity_GlaciasRoom_EventScript_Defeated::

EverGrandeCity_GlaciasRoom_Text_IntroSpeech:
	.string "Welcome, my name is GLACIA\n"
	.string "of the ELITE FOUR.\p"
	.string "I've traveled from afar to HOENN\n"
	.string "so that I may hone my ice skills.\p"
	.string "But all I have seen are challenges by\n"
	.string "weak TRAINERS and their POKéMON.\p"
	.string "What about you?\p"
	.string "It would please me to no end if I could\n"
	.string "go all out against you!$"

EverGrandeCity_GlaciasRoom_Text_Defeat:
	.string "You and your POKéMON…\n"
	.string "How hot your spirits burn!\p"
	.string "The all-consuming heat overwhelms.\p"
	.string "It's no surprise that my icy skills\n"
	.string "failed to harm you.$"

EverGrandeCity_GlaciasRoom_Text_PostBattleSpeech:
	.string "Advance to the next room.\p"
	.string "And there, confirm the truly fearsome\n"
	.string "side of the POKéMON LEAGUE.$"

