@ LOCALID_BRIDGE_KECLEON_SHADOW is a second object which is identical to LOCALID_BRIDGE_KECLEON but has a reflection palette tag for the bridge shadow
Route120_MapScripts::

Route120_OnResume:

Route120_EventScript_RemoveKecleonObject::

Route120_EventScript_RemoveBridgeKecleon::

Route120_EventScript_RemoveKecleon::

Route120_OnLoad:

Route120_EventScript_CloseAncientTomb::

Route120_EventScript_SetBridgeClearMetatiles::

Route120_EventScript_SetBridgeKecleonMovement::

Route120_OnTransition:

Route120_EventScript_SetWeather::

Route120_EventScript_SetCloudyWeather::

Route120_EventScript_SetSunnyWeather::

Route120_EventScript_TrySetRainyWeather::

Route120_EventScript_SetRainyWeather::

Route120_EventScript_BerryBeauty::

Route120_EventScript_GiveFigyBerry::

Route120_EventScript_GiveWikiBerry::

Route120_EventScript_GiveMagoBerry::

Route120_EventScript_GiveAguavBerry::

Route120_EventScript_GiveIapapaBerry::

Route120_EventScript_GiveBerry::

Route120_EventScript_ReceivedBerry::

Route120_EventScript_BerryLove::

Route120_EventScript_BerryNotLove::

Route120_EventScript_Steven::

Route120_EventScript_StevenNotReady::

Route120_EventScript_StevenAskReadyForBattle::

Route120_EventScript_StevenBattleKecleon::

Route120_EventScript_RemoveBridgeKecleonPostBattle::

Route120_EventScript_StevenGiveDeconScope::

Route120_EventScript_PlayerApproachKecleonNorth::

Route120_EventScript_PlayerApproachKecleonWest::

Route120_Movement_ApproachKecleonWest:

Route120_EventScript_BridgeKecleon::

Route120_EventScript_RouteSignFortree::

Route120_EventScript_RouteSign121::

Route120_EventScript_Colin::

Route120_EventScript_Robert::

Route120_EventScript_RegisterRobert::

Route120_EventScript_RematchRobert::

Route120_EventScript_Lorenzo::

Route120_EventScript_Jenna::

Route120_EventScript_Jeffrey::

Route120_EventScript_RegisterJeffrey::

Route120_EventScript_RematchJeffrey::

Route120_EventScript_Jennifer::

Route120_EventScript_Chip::

Route120_EventScript_Clarissa::

Route120_EventScript_Angelica::

Route120_EventScript_Keigo::

Route120_EventScript_Riley::

Route120_EventScript_Leonel::

Route120_EventScript_Callie::

Route120_Text_StevenGreeting:
	.string "STEVEN: Hm? {PLAYER}{KUN}, hi.\n"
	.string "It's been a while.\p"
	.string "There's something here that you can't\n"
	.string "see, right?\p"
	.string "Now, if I were to use this device on\n"
	.string "the invisible obstacle…\p"
	.string "No, no. Rather than describing it,\n"
	.string "I should just show you.\l"
	.string "That would be more fun.\p"
	.string "{PLAYER}{KUN}, are your POKéMON ready for\n"
	.string "battle?$"

Route120_Text_StevenIllWaitHere:
	.string "STEVEN: No?\p"
	.string "I'll wait here, so you can get ready.$"

Route120_Text_StevenReadyForBattle:
	.string "STEVEN: {PLAYER}{KUN}, are your POKéMON\n"
	.string "ready for battle?$"

Route120_Text_StevenShowMeYourPower:
	.string "STEVEN: {PLAYER}{KUN}, show me your true\n"
	.string "power as a TRAINER!$"

Route120_Text_StevenUsedDevonScope:
	.string "STEVEN used the DEVON SCOPE.\p"
	.string "An invisible POKéMON became completely\n"
	.string "visible!\p"
	.string "The startled POKéMON attacked!$"

Route120_Text_StevenGiveDevonScope:
	.string "STEVEN: I see…\n"
	.string "Your battle style is intriguing.\p"
	.string "Your POKéMON have obviously grown\n"
	.string "since I first met you in DEWFORD.\p"
	.string "I'd like you to have this\n"
	.string "DEVON SCOPE.\p"
	.string "Who knows, there may be other\n"
	.string "concealed POKéMON.$"

Route120_Text_StevenGoodbye:
	.string "STEVEN: {PLAYER}{KUN}.\p"
	.string "I enjoy seeing POKéMON and TRAINERS\n"
	.string "who strive together.\p"
	.string "I think you're doing great.\p"
	.string "Well, let's meet again somewhere.$"

Kecleon_Text_SomethingUnseeable:
	.string "Something unseeable is in the way.$"

Kecleon_Text_WantToUseDevonScope:
	.string "Something unseeable is in the way.\p"
	.string "Want to use the DEVON SCOPE?$"

Kecleon_Text_UseDevonScopeMonAttacked:
	.string "{PLAYER} used the DEVON SCOPE.\p"
	.string "An invisible POKéMON became completely\n"
	.string "visible!\p"
	.string "The startled POKéMON attacked!$"

Route120_Text_RouteSignFortree:
	.string "ROUTE 120\n"
	.string "{LEFT_ARROW} FORTREE CITY$"

Route120_Text_RouteSign121:
	.string "{RIGHT_ARROW} ROUTE 121\n"
	.string "{LEFT_ARROW} ROUTE 120$"
