Route119_MapScripts::

Route119_OnResume:

Route119_EventScript_TryRemoveKecleon::

Route119_OnTransition:

Route119_EventScript_MoveInstituteWorkersDownstairs::

Route119_EventScript_RivalTrigger1::

Route119_EventScript_RivalTrigger2::

Route119_EventScript_RivalEncounter::

Route119_EventScript_PlayMayMusic::

Route119_EventScript_PlayBrendanMusic::

Route119_EventScript_BattleMay::

Route119_EventScript_BattleMayTreecko::

Route119_EventScript_BattleMayTorchic::

Route119_EventScript_BattleMayMudkip::

Route119_EventScript_DefeatedMay::

Route119_EventScript_BattleBrendan::

Route119_EventScript_BattleBrendanTreecko::

Route119_EventScript_BattleBrendanTorchic::

Route119_EventScript_BattleBrendanMudkip::

Route119_EventScript_DefeatedBrendan::

Route119_EventScript_GiveFlyHM::

Route119_EventScript_RivalExitScottArrive::

Route119_EventScript_SetScottPos1::

Route119_EventScript_SetScottPos2::

Route119_EventScript_ScottExit1::

Route119_EventScript_ScottExit2::

Route119_EventScript_RivalEnter1::

Route119_EventScript_RivalEnter2::

Route119_EventScript_RivalExit1::

Route119_EventScript_RivalExit2::

Route119_EventScript_SetRivalPos1::

Route119_EventScript_SetRivalPos2::

Route119_Movement_PlayerWatchRivalExit1:

Route119_Movement_PlayerWatchRivalExit2:

Route119_Movement_RivalEnter1:

Route119_Movement_RivalEnter2:

Route119_Movement_RivalExit1:

Route119_Movement_RivalExit2:

Route119_Movement_ScottEnter:

Route119_Movement_ScottExit1:

Route119_Movement_ScottExit2:

Route119_EventScript_CyclingTriathleteM::

Route119_EventScript_RouteSignFortree::

Route119_EventScript_WeatherInstituteSign::

Route119_EventScript_Brent::

Route119_EventScript_Donald::

Route119_EventScript_Taylor::

Route119_EventScript_Doug::

Route119_EventScript_Greg::

Route119_EventScript_Kent::

Route119_EventScript_Jackson::

Route119_EventScript_RegisterJackson::

Route119_EventScript_RematchJackson::

Route119_EventScript_Catherine::

Route119_EventScript_RegisterCatherine::

Route119_EventScript_RematchCatherine::

Route119_EventScript_Hugh::

Route119_EventScript_Phil::

Route119_EventScript_Yasu::

Route119_EventScript_Takashi::

Route119_EventScript_Hideo::

Route119_EventScript_Chris::

Route119_EventScript_Fabian::

Route119_EventScript_Dayton::

Route119_EventScript_Rachel::

Route119_EventScript_BridgeAquaGrunt1::

Route119_EventScript_BridgeAquaGrunt2::

Route119_EventScript_Boy1::

Route119_EventScript_Boy2::

Route119_EventScript_TrainerTipsDecoration::

Route119_EventScript_ScottWonAtFortreeGymCall::

Route119_Text_MayIntro:
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Where were you? I was looking for you!\p"
	.string "How much stronger have you gotten?\n"
	.string "Let me check for you!\p"
	.string "Ready with your POKéMON?\n"
	.string "Of course you are! Go!$"

Route119_Text_MayDefeat:
	.string "Achah!\n"
	.string "{PLAYER}{KUN}, you're strong!\p"
	.string "I was worried that you might be\n"
	.string "struggling with your training.$"

Route119_Text_MayPresentForYou:
	.string "MAY: But I had absolutely nothing to\n"
	.string "worry about! Keep it up!\p"
	.string "And, here! I have a present for you.$"

Route119_Text_MayExplainFly:
	.string "MAY: Use FLY, and your POKéMON will\n"
	.string "instantly carry you to any town you've\l"
	.string "already visited.\p"
	.string "But, to use FLY, you have to get\n"
	.string "the GYM BADGE from FORTREE CITY.\l"
	.string "That's important, so don't forget.\p"
	.string "You should FLY home and visit\n"
	.string "LITTLEROOT for a change.\p"
	.string "I bet your mom's worried about you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Well, let's meet again somewhere!$"

Route119_Text_BrendanIntro:
	.string "BRENDAN: {PLAYER}! So this is where\n"
	.string "you've been looking for POKéMON?\p"
	.string "Let me see how good you got.\n"
	.string "I'll test you!\p"
	.string "Now!\n"
	.string "It's a battle, so battle!$"

Route119_Text_BrendanDefeat:
	.string "Hmm…\n"
	.string "You've gotten pretty darn decent.$"

Route119_Text_BrendanIllGiveYouThis:
	.string "BRENDAN: I'd say you're good enough\n"
	.string "to search for POKéMON anywhere.\p"
	.string "Here, I'll give you this.\n"
	.string "Try it out.$"

Route119_Text_BrendanExplainFly:
	.string "BRENDAN: Use FLY, and your POKéMON\n"
	.string "instantly carries you to any town\l"
	.string "you've already visited.\p"
	.string "But you need the FORTREE GYM BADGE \n"
	.string "to do that.\p"
	.string "Anyway, I have to move along.$"

Route119_Text_ScottWayToGoBeSeeingYou:
	.string "SCOTT: Hahahah!\n"
	.string "Way to go, {PLAYER}{KUN}!\p"
	.string "I just passed by a TRAINER riding\n"
	.string "a BIKE.\p"
	.string "You just beat that TRAINER, didn't you?\n"
	.string "It was pretty obvious that you did.\p"
	.string "The kid looked really upset with\n"
	.string "a face all red from anger.\p"
	.string "I sure seem to run into you often.\n"
	.string "Are you off to FORTREE GYM next?\p"
	.string "I expect that you'll do well at the GYM.\n"
	.string "Well, I'll be seeing you!$"


Route119_Text_ScottYouWonAtFortreeGym:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "SCOTT: Hiya, {PLAYER}{KUN}, it's me!\p"
	.string "Just as I thought, you won at\n"
	.string "the FORTREE GYM.\p"
	.string "Your strength…\n"
	.string "Perhaps you really are the TRAINER\l"
	.string "that I've been searching for.\p"
	.string "Remember, you have a fan in me.\n"
	.string "I'll be cheering from the sidelines.\l"
	.string "Keep up the great work!\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

Route119_Text_StayAwayFromWeatherInstitute:
	.string "We're standing lookout here.\p"
	.string "Hey, you! Stay away from the WEATHER\n"
	.string "INSTITUTE. It's not safe.$"

Route119_Text_DontGoNearWeatherInstitute:
	.string "Lookout duty is surprisingly boring.\p"
	.string "Hey, you! Please don't go near the\n"
	.string "WEATHER INSTITUTE.$"

Route119_Text_ThoughtFlyByCatchingBirdMons:
	.string "I thought you FLY by catching a whole\n"
	.string "flock of BIRD POKéMON, and then\l"
	.string "hanging on to them somehow.\p"
	.string "But it turns out there's an HM move\n"
	.string "called FLY!\p"
	.string "I wish I'd known about that a long\n"
	.string "time ago…$"

Route119_Text_TallGrassSnaresBikeTires:
	.string "Tch…\n"
	.string "It's a no-go…\p"
	.string "The tall grass snares BIKE tires.\n"
	.string "There's no way you can cycle here.$"

Route119_Text_CanYourMonMakeSecretBase:
	.string "Can your POKéMON use its SECRET POWER\n"
	.string "on a big pile of grass and make a\l"
	.string "SECRET BASE?$"

Route119_Text_RouteSignFortree:
	.string "ROUTE 119\n"
	.string "{RIGHT_ARROW} FORTREE CITY$"

Route119_Text_WeatherInstitute:
	.string "WEATHER INSTITUTE$"

Route119_Text_TrainerTipsDecoration:
	.string "TRAINER TIPS\p"
	.string "Up to sixteen decorations and\n"
	.string "furniture items can be placed in\l"
	.string "a SECRET BASE.\p"
	.string "Pick your favorite items and create\n"
	.string "your very own SECRET BASE exactly the\l"
	.string "way you want.$"
