Underwater_SeafloorCavern_MapScripts::

Underwater_SeafloorCavern_OnTransition:

Underwater_SeafloorCavern_EventScript_HideSubmarine::

Underwater_SeafloorCavern_OnLoad:

Underwater_SeafloorCavern_EventScript_SetSubmarineGoneMetatiles::

Underwater_SeafloorCavern_OnResume:

Underwater_SeafloorCavern_EventScript_CheckStolenSub::

Underwater_SeafloorCavern_Text_SubExplorer1:
	.string "“SUBMARINE EXPLORER 1” is painted\n"
	.string "on the hull.\p"
	.string "This is the submarine TEAM AQUA\n"
	.string "stole in SLATEPORT!\p"
	.string "TEAM AQUA must have gone\n"
	.string "ashore here.$"

