MauvilleCity_PokemonCenter_2F_MapScripts::

@ The below 3 are unused and leftover from RS
MauvilleCity_PokemonCenter_2F_EventScript_Colosseum::

MauvilleCity_PokemonCenter_2F_EventScript_TradeCenter::

MauvilleCity_PokemonCenter_2F_EventScript_RecordCorner::

MauvilleCity_PokemonCenter_2F_EventScript_Youngster::

MauvilleCity_PokemonCenter_2F_Text_Youngster:
	.string "Did you know that you can link battle\n"
	.string "at the COLOSSEUM here?\p"
	.string "They put up your record on the wall\n"
	.string "for everyone to see.\p"
	.string "It's embarrassing if you lose more\n"
	.string "often than you win…$"

