FortreeCity_DecorationShop_MapScripts::

FortreeCity_DecorationShop_EventScript_PokefanM::

FortreeCity_DecorationShop_EventScript_Girl::

FortreeCity_DecorationShop_EventScript_ClerkDesks::

FortreeCity_DecorationShop_PokemartDecor_Desks:

FortreeCity_DecorationShop_EventScript_ClerkChairs::

FortreeCity_DecorationShop_PokemartDecor_Chairs:

FortreeCity_DecorationShop_Text_MerchandiseSentToPC:
	.string "Merchandise you buy here is sent to\n"
	.string "your own PC.\p"
	.string "That's fantastic! I wish they could\n"
	.string "also deliver me home like that.$"

FortreeCity_DecorationShop_Text_BuyingDeskForDolls:
	.string "I'm buying a pretty desk and I'm\n"
	.string "putting my cute DOLLS on it.\p"
	.string "If I don't, when I decorate my\n"
	.string "SECRET BASE, my DOLLS will get\l"
	.string "dirty or poked with splinters.$"

