Route110_TrickHousePuzzle5_MapScripts::

Route110_TrickHousePuzzle5_OnTransition:

Route110_TrickHousePuzzle5_EventScript_Scroll::

Route110_TrickHousePuzzle5_EventScript_FoundScroll::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Trigger0::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Trigger1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Trigger2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Trigger3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Trigger4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger0::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Trigger5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Trigger0::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Trigger1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Trigger2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Trigger3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Trigger4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger0::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger4::

@ Unused
Route110_TrickHousePuzzle5_EventScript_Mechadoll4Trigger5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5Trigger0::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Activate::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Activate::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Activate::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Activate::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5Activate::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Quiz1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Quiz2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1Quiz3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Quiz1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Quiz2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2Quiz3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Quiz1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Quiz2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3Quiz3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Quiz1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Quiz2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4Quiz3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5Quiz1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5Quiz2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5Quiz3::

Route110_TrickHousePuzzle5_EventScript_IncorrectAnswer::

Route110_TrickHousePuzzle5_EventScript_CorrectAnswer::

Route110_TrickHousePuzzle5_EventScript_CorrectGoThrough::

@ Absurd redundancy in movement scripts that could be resolved by using VAR_TEMP_8 for applymovement instead
@ Many of the below movement scripts arent even used, see below
@   Mechadoll 2 is the only mechadoll to walk right, all the other WalkRight scripts are unused
@   Mechadoll 5 never walks, all the Mechadoll5Walk scripts are unused
@   No mechadoll walks left 5 paces, all the WalkLeft5 scripts are unused
Route110_TrickHousePuzzle5_EventScript_MechadollWalkLeft1::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkLeft2::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkLeft3::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkLeft4::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkLeft5::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkRight1::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkRight2::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkRight3::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkRight4::

Route110_TrickHousePuzzle5_EventScript_MechadollWalkRight5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkLeft1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkLeft1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkLeft1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkLeft1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkLeft1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkLeft2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkLeft2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkLeft2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkLeft2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkLeft2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkLeft3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkLeft3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkLeft3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkLeft3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkLeft3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkLeft4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkLeft4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkLeft4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkLeft4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkLeft4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkLeft5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkLeft5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkLeft5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkLeft5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkLeft5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkRight1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkRight1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkRight1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkRight1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkRight1::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkRight2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkRight2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkRight2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkRight2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkRight2::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkRight3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkRight3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkRight3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkRight3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkRight3::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkRight4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkRight4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkRight4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkRight4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkRight4::

Route110_TrickHousePuzzle5_EventScript_Mechadoll1WalkRight5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll2WalkRight5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll3WalkRight5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll4WalkRight5::

Route110_TrickHousePuzzle5_EventScript_Mechadoll5WalkRight5::

Route110_TrickHousePuzzle5_Movement_WalkLeft1:

Route110_TrickHousePuzzle5_Movement_WalkLeft2:

Route110_TrickHousePuzzle5_Movement_WalkLeft3:

Route110_TrickHousePuzzle5_Movement_WalkLeft4:

Route110_TrickHousePuzzle5_Movement_WalkLeft5:

Route110_TrickHousePuzzle5_Movement_WalkRight1:

Route110_TrickHousePuzzle5_Movement_WalkRight2:

Route110_TrickHousePuzzle5_Movement_WalkRight3:

Route110_TrickHousePuzzle5_Movement_WalkRight4:

Route110_TrickHousePuzzle5_Movement_WalkRight5:

Route110_TrickHousePuzzle5_Movement_MechadollShake:

Route110_TrickHousePuzzle5_Text_WroteSecretCodeLockOpened:
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is a genius.”\n"
	.string "… … … … … … … …\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Intro:
	.string "CLICKETY-CLACK…\n"
	.string "MECHADOLL 1 AM I!\p"
	.string "IF YOU ANSWER QUIZZES CORRECTLY,\n"
	.string "THEN YOU WILL GO TO MECHADOLL 5.\l"
	.string "THEN YOU CAN OBTAIN THE SECRET CODE.$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz1:
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these POKéMON is not found\n"
	.string "on ROUTE 110. Which one is it?$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz2:
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these POKéMON is not of the\n"
	.string "WATER type. Which one is it?$"

Route110_TrickHousePuzzle5_Text_Mechadoll1Quiz3:
	.string "MECHADOLL 1 QUIZ.\p"
	.string "One of these POKéMON does not use\n"
	.string "LEECH LIFE. Which one is it?$"

Route110_TrickHousePuzzle5_Text_CorrectGoThrough:
	.string "CONGRATULATIONS. CORRECT YOU ARE.\n"
	.string "GO THROUGH. PLEASE.$"

Route110_TrickHousePuzzle5_Text_DisappointmentError:
	.string "BZZZT. DISAPPOINTMENT.\n"
	.string "ERROR.$"

Route110_TrickHousePuzzle5_Text_Wahahahaha:
	.string "WAHAHAHAHA! WAHAHAHAHA!\n"
	.string "CLICKETY-CLACK!$"

Route110_TrickHousePuzzle5_Text_WaitForNextChallenge:
	.string "YOUR NEXT CHALLENGE WE WAIT FOR.$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Intro:
	.string "CLICKETY-CLACK…\n"
	.string "MECHADOLL 2 AM I!\p"
	.string "MECHADOLL 1'S QUIZ DIFFICULTY LEVEL\n"
	.string "IS SET TOO LOW.$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz1:
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Which of these POKéMON did WALLY\n"
	.string "borrow from your father?$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz2:
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Which of these POKéMON was chasing\n"
	.string "PROF. BIRCH?$"

Route110_TrickHousePuzzle5_Text_Mechadoll2Quiz3:
	.string "MECHADOLL 2 QUIZ.\p"
	.string "Which of these POKéMON did TEAM AQUA\n"
	.string "use in PETALBURG FOREST?$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Intro:
	.string "CLICKETY-CLACK…\n"
	.string "MECHADOLL 3 AM I!\p"
	.string "MATTERS OF MONEY ARE MY SOLE FOCUS.$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz1:
	.string "MECHADOLL 3 QUIZ.\p"
	.string "Which costs more?\n"
	.string "Three HARBOR MAILS or one BURN HEAL?$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz2:
	.string "MECHADOLL 3 QUIZ.\p"
	.string "Sell one GREAT BALL and buy\n"
	.string "one POTION. How much money remains?$"

Route110_TrickHousePuzzle5_Text_Mechadoll3Quiz3:
	.string "MECHADOLL 3 QUIZ.\p"
	.string "Do one REPEL and SODA POP cost\n"
	.string "more than one SUPER POTION?$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Intro:
	.string "CLICKETY-CLACK…\n"
	.string "MECHADOLL 4 THAT IS ME!\p"
	.string "MY QUIZ IS AN OBJECT OF BEAUTY.$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz1:
	.string "MECHADOLL 4 QUIZ.\p"
	.string "In SEASHORE HOUSE, were there more men\n"
	.string "or women?$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz2:
	.string "MECHADOLL 4 QUIZ.\p"
	.string "In LAVARIDGE TOWN, were there more\n"
	.string "elderly men or elderly women?$"

Route110_TrickHousePuzzle5_Text_Mechadoll4Quiz3:
	.string "MECHADOLL 4 QUIZ.\p"
	.string "In the TRAINER'S SCHOOL, how many\n"
	.string "girl students were there?$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Intro:
	.string "CLICKETY-CLACK…\n"
	.string "MECHADOLL 5 AM I!\p"
	.string "THE MASTER'S BEST AND PROUDEST\n"
	.string "ACHIEVEMENT AM I.$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz1:
	.string "MECHADOLL 5 QUIZ.\p"
	.string "In SLATEPORT's POKéMON FAN CLUB,\n"
	.string "how many POKéMON were there?$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz2:
	.string "MECHADOLL 5 QUIZ.\p"
	.string "In FORTREE CITY, how many\n"
	.string "tree houses were there?$"

Route110_TrickHousePuzzle5_Text_Mechadoll5Quiz3:
	.string "MECHADOLL 5 QUIZ.\p"
	.string "On the CYCLING ROAD, how many\n"
	.string "TRIATHLETES were there?$"
