EverGrandeCity_MapScripts::

EverGrandeCity_OnTransition:

EverGrandeCity_EventScript_VictoryRoadSign::

EverGrandeCity_EventScript_CitySign::

EverGrandeCity_EventScript_PokemonLeagueSign::

EverGrandeCity_EventScript_SetVisitedEverGrande::

EverGrandeCity_Text_EnteringVictoryRoad:
	.string "ENTERING VICTORY ROAD$"

EverGrandeCity_Text_EnteringPokemonLeague:
	.string "ENTERING POKéMON LEAGUE\n"
	.string "CENTER GATE$"

EverGrandeCity_Text_CitySign:
	.string "EVER GRANDE CITY\p"
	.string "“The paradise of flowers, the sea,\n"
	.string "and POKéMON.”$"

