BattleFrontier_PokemonCenter_1F_MapScripts::

BattleFrontier_PokemonCenter_1F_OnTransition:

BattleFrontier_PokemonCenter_1F_EventScript_Nurse::

BattleFrontier_PokemonCenter_1F_EventScript_SchoolKid::

BattleFrontier_PokemonCenter_1F_EventScript_Man::

BattleFrontier_PokemonCenter_1F_EventScript_Picnicker::

BattleFrontier_PokemonCenter_1F_EventScript_Skitty::

BattleFrontier_PokemonCenter_1F_Text_NeverSeenPokemon:
	.string "There was someone here using a \n"
	.string "POKéMON I've never seen before.\p"
	.string "I never learned about it at\n"
	.string "TRAINER'S SCHOOL at least.\p"
	.string "I wonder where you can catch POKéMON\n"
	.string "like that.$"

BattleFrontier_PokemonCenter_1F_Text_NextStopBattleArena:
	.string "Okay! Next stop, the BATTLE ARENA!\n"
	.string "I'd better get the right POKéMON from\l"
	.string "the PC Storage System.$"

BattleFrontier_PokemonCenter_1F_Text_GoingThroughEveryChallenge:
	.string "Giggle… I'm going to go through every\n"
	.string "challenge with just this baby!$"

BattleFrontier_PokemonCenter_1F_Text_Skitty:
	.string "SKITTY: Mya myaaah!$"

