SSTidalCorridor_MapScripts::

SSTidalCorridor_OnFrame:

SSTidalCorridor_EventScript_DepartSlateportForLilycove::

SSTidalCorridor_EventScript_DepartLilycoveForSlateport::

SSTidalRooms_EventScript_HalfwayToSlateport::

SSTidalRooms_EventScript_ArrivedInLilycove::

SSTidalCorridor_EventScript_ReachedStepCount::

SSTidalCorridor_EventScript_HalfwayToLilycove::

SSTidalCorridor_EventScript_ArrivedInSlateport::

SSTidalRooms_EventScript_ArrivedInSlateport::

SSTidalRooms_EventScript_ProgessCruiseAfterBed::

SSTidalCorridor_EventScript_Briney::

SSTidalCorridor_EventScript_Peeko::

SSTidalCorridor_EventScript_Cabin1Sign::

SSTidalCorridor_EventScript_Cabin2Sign::

SSTidalCorridor_EventScript_Cabin3Sign::

SSTidalCorridor_EventScript_Cabin4Sign::

SSTidalCorridor_EventScript_ExitSailor::

SSTidalCorridor_EventScript_ExitLilycove::

SSTidalCorridor_EventScript_ExitSlateport::

SSTidalCorridor_EventScript_HideSnatchGiver::

SSTidalCorridor_EventScript_Porthole::

SSTidalCorridor_EventScript_LookThroughPorthole::

SSTidalCorridor_EventScript_Sailor::

SSTidalCorridor_EventScript_EnjoyYourCruise::

SSTidalCorridor_EventScript_CheckIfTrainersDefeated::

SSTidalCorridor_EventScript_TrainerNotDefeated::

SSTidalCorridor_EventScript_ScottScene::

SSTidalCorridor_Movement_ScottApproachPlayer:

SSTidalCorridor_Movement_ScottExit:

SSTidalCorridor_Movement_PlayerWatchScottExit:

SSTidalCorridor_Movement_SailorMoveForScott:

SSTidalCorridor_Movement_SailorReturn:

SSTidalCorridor_Text_ScottBattleFrontierInvite:
	.string "SCOTT: Well, hi, hi!\n"
	.string "{PLAYER}{KUN}, {PLAYER}{KUN}!\p"
	.string "Something's come up, so I have to\n"
	.string "disembark, but am I glad to see you!\p"
	.string "Congratulations, LEAGUE CHAMPION!\p"
	.string "There's a place I'd like to invite\n"
	.string "someone like you.\p"
	.string "It's the…\n"
	.string "BATTLE FRONTIER!\p"
	.string "What's the place like?\n"
	.string "You'll understand when you see it!\p"
	.string "I've spoken with the ship's CAPTAIN\n"
	.string "about this.\p"
	.string "The next time you take a ferry,\n"
	.string "you should be able to sail to\l"
	.string "the BATTLE FRONTIER.\p"
	.string "Okay, {PLAYER}{KUN}, I'll be waiting for you\n"
	.string "at the BATTLE FRONTIER!$"

SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage:
	.string "This ferry is built to plow through\n"
	.string "fast-running currents.\p"
	.string "We hope you enjoy your voyage with us.\n"
	.string "Feel free to explore the ship.$"

SSTidal_Text_HopeYouEnjoyVoyage:
	.string "We hope you enjoy your voyage on\n"
	.string "our ferry.$"

SSTidal_Text_MadeLandInSlateport:
	.string "We have made land in SLATEPORT CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidal_Text_MadeLandInLilycove:
	.string "We have made land in LILYCOVE CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidalCorridor_Text_CanRestInCabin2:
	.string "It'll be some time before we make land,\n"
	.string "I reckon.\p"
	.string "You can rest up in your cabin if you'd\n"
	.string "like. Your cabin's No. 2.\p"
	.string "The bed in there is soft and plushy.\n"
	.string "I can attest to how comfy it is!$"

SSTidalCorridor_Text_WeveArrived:
	.string "We've arrived!$"

SSTidalCorridor_Text_VisitOtherCabins:
	.string "Go visit other cabins.\n"
	.string "TRAINERS bored of the boat trip will\l"
	.string "be itching to battle.$"

SSTidalCorridor_Text_EnjoyYourCruise:
	.string "Enjoy your cruise!$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole:
	.string "The horizon spreads beyond\n"
	.string "the porthole.$"

SSTidalCorridor_Text_BrineyWelcomeAboard:
	.string "MR. BRINEY: Welcome aboard, {PLAYER}{KUN}!\p"
	.string "They made me honorary captain of\n"
	.string "the S.S. TIDAL!\p"
	.string "You can call me CAPTAIN BRINEY now!\p"
	.string "You know, I retired once before,\n"
	.string "but when I saw this majestic ship…\p"
	.string "Let me just say, it stirred my sleeping\n"
	.string "soul as a sailor!$"

SSTidalCorridor_Text_Peeko:
	.string "PEEKO: Pihyo pihyohyo…$"

SSTidalCorridor_Text_Cabin1:
	.string "Cabin 1$"

SSTidalCorridor_Text_Cabin2:
	.string "Cabin 2$"

SSTidalCorridor_Text_Cabin3:
	.string "Cabin 3$"

SSTidalCorridor_Text_Cabin4:
	.string "Cabin 4$"
