UnionRoom_MapScripts::

UnionRoom_OnResume:

UnionRoom_OnTransition:

UnionRoom_EventScript_Player1::

UnionRoom_EventScript_Player2::

UnionRoom_EventScript_Player3::

UnionRoom_EventScript_Player4::

UnionRoom_EventScript_Player5::

UnionRoom_EventScript_Player6::

UnionRoom_EventScript_Player7::

UnionRoom_EventScript_Player8::

UnionRoom_EventScript_Attendant::

UnionRoom_EventScript_Unused::
