AncientTomb_MapScripts::

AncientTomb_OnResume:

AncientTomb_EventScript_TryRemoveRegisteel::

AncientTomb_OnTransition:

AncientTomb_EventScript_ShowRegisteel::

AncientTomb_OnLoad:

AncientTomb_EventScript_HideRegiEntrance::

AncientTomb_EventScript_CaveEntranceMiddle::

AncientTomb_EventScript_BigHoleInWall::

AncientTomb_EventScript_CaveEntranceSide::

AncientTomb_EventScript_Registeel::

AncientTomb_EventScript_DefeatedRegisteel::

AncientTomb_EventScript_RanFromRegisteel::

