Route115_MapScripts::

Route115_OnLoad:

Route115_OnTransition:

Route115_OnFrame:

Route115_EventScript_Woman::

Route115_EventScript_RouteSignRustboro::

Route115_EventScript_MeteorFallsSign::

Route115_EventScript_Timothy::

Route115_EventScript_RegisterTimothy::

Route115_EventScript_RematchTimothy::

Route115_EventScript_Koichi::

Route115_EventScript_Nob::

Route115_EventScript_RegisterNob::

Route115_EventScript_RematchNob::

Route115_EventScript_Cyndy::

Route115_EventScript_RegisterCyndy::

Route115_EventScript_RematchCyndy::

Route115_EventScript_Hector::

Route115_EventScript_Kyra::

Route115_EventScript_Jaiden::

Route115_EventScript_Alix::

Route115_EventScript_Helene::

Route115_EventScript_Marlene::

Route115_Text_NeverKnowWhenCavePokemonWillAppear:
	.string "Exploring a cave isn't like walking\n"
	.string "on a road.\p"
	.string "You never know when wild POKéMON will\n"
	.string "appear. It's full of suspense.$"

Route115_Text_RouteSignRustboro:
	.string "ROUTE 115\n"
	.string "{DOWN_ARROW} RUSTBORO CITY$"

Route115_Text_MeteorFallsSign:
	.string "METEOR FALLS\n"
	.string "FALLARBOR TOWN THROUGH HERE$"

