Route124_DivingTreasureHuntersHouse_MapScripts::

Route124_DivingTreasureHuntersHouse_OnTransition:

Route124_DivingTreasureHuntersHouse_EventScript_TreasureHunter::

Route124_DivingTreasureHuntersHouse_EventScript_SkipGreeting::

Route124_DivingTreasureHuntersHouse_EventScript_CheckPlayerHasShard::

Route124_DivingTreasureHuntersHouse_EventScript_GetPlayersShards::

Route124_DivingTreasureHuntersHouse_EventScript_HasRedShard::

Route124_DivingTreasureHuntersHouse_EventScript_HasYellowShard::

Route124_DivingTreasureHuntersHouse_EventScript_HasBlueShard::

Route124_DivingTreasureHuntersHouse_EventScript_HasGreenShard::

Route124_DivingTreasureHuntersHouse_EventScript_HasShard::

Route124_DivingTreasureHuntersHouse_EventScript_ShowTradeOptions::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsR::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsY::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRY::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsB::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRB::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsYB::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRYB::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsYG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRYG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsBG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRBG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsYBG::

Route124_DivingTreasureHuntersHouse_EventScript_ShardOptionsRYBG::

Route124_DivingTreasureHuntersHouse_EventScript_TradeRedShard::

Route124_DivingTreasureHuntersHouse_EventScript_TradeYellowShard::

Route124_DivingTreasureHuntersHouse_EventScript_TradeBlueShard::

Route124_DivingTreasureHuntersHouse_EventScript_TradeGreenShard::

Route124_DivingTreasureHuntersHouse_EventScript_TryTradeShard::

Route124_DivingTreasureHuntersHouse_EventScript_TradeShard::

Route124_DivingTreasureHuntersHouse_EventScript_BagFull::

Route124_DivingTreasureHuntersHouse_EventScript_DeclineTrade::

Route124_DivingTreasureHuntersHouse_EventScript_NoShards::

Route124_DivingTreasureHuntersHouse_EventScript_EndTrade::

Route124_DivingTreasureHuntersHouse_EventScript_ShardTradeBoard::

Route124_DivingTreasureHuntersHouse_Text_Greeting:
	.string "I'm the DIVING TREASURE HUNTER!\p"
	.string "I'm the awesome dude who makes\n"
	.string "deep-sea dives to gather treasures\l"
	.string "resting at the bottom.$"

Route124_DivingTreasureHuntersHouse_Text_HaveYouSeenAnyShards:
	.string "Tell me, have you seen any SHARDS of\n"
	.string "tools made in ancient times?$"

Route124_DivingTreasureHuntersHouse_Text_YouHaventGotAnyShards:
	.string "You haven't got any treasures\n"
	.string "for me…\p"
	.string "If you see any SHARDS, like the RED\n"
	.string "SHARD, you've got to trade it with me!$"

Route124_DivingTreasureHuntersHouse_Text_ThatsAShardIllTradeYou:
	.string "Oh, hey! That…\n"
	.string "That's a SHARD! I'm looking for those!\p"
	.string "Oh, man, you've got to trade that\n"
	.string "with me! I'll give you something good!$"

Route124_DivingTreasureHuntersHouse_Text_WhatDoYouWantToTrade:
	.string "What do you want to trade?$"

Route124_DivingTreasureHuntersHouse_Text_YoullTradeShardForStone:
	.string "You'll trade your {STR_VAR_1} for\n"
	.string "my {STR_VAR_2}, then?$"

Route124_DivingTreasureHuntersHouse_Text_ItsADeal:
	.string "It's a done deal!\n"
	.string "Use that wisely!$"

Route124_DivingTreasureHuntersHouse_Text_TradeSomethingElse:
	.string "Do you want to trade something else?$"

Route124_DivingTreasureHuntersHouse_Text_BagFull:
	.string "Whoops, your BAG's full.\n"
	.string "Get rid of some items, friend!$"

Route124_DivingTreasureHuntersHouse_Text_ComeBackIfYouChangeMind:
	.string "No? That's a downer.\n"
	.string "Well, if you change your mind, come back.$"

Route124_DivingTreasureHuntersHouse_Text_ShardTradeBoard:
	.string "{CLEAR_TO 0x0a}Wanted item{CLEAR_TO 0x7c}Trade item\n"
	.string "{CLEAR_TO 0x0f}RED SHARD{CLEAR_TO 0x59}{LEFT_ARROW}{RIGHT_ARROW}{CLEAR_TO 0x7b}FIRE STONE{CLEAR_TO 0xc8}\p"
	.string "{CLEAR_TO 0x0a}Wanted item{CLEAR_TO 0x7c}Trade item\n"
	.string "{CLEAR_TO 0x06}YELLOW SHARD{CLEAR_TO 0x59}{LEFT_ARROW}{RIGHT_ARROW}{CLEAR_TO 0x73}THUNDERSTONE{CLEAR_TO 0xc8}\p"
	.string "{CLEAR_TO 0x0a}Wanted item{CLEAR_TO 0x7c}Trade item\n"
	.string "{CLEAR_TO 0x0c}BLUE SHARD{CLEAR_TO 0x59}{LEFT_ARROW}{RIGHT_ARROW}{CLEAR_TO 0x79}WATER STONE{CLEAR_TO 0xc8}\p"
	.string "{CLEAR_TO 0x0a}Wanted item{CLEAR_TO 0x7c}Trade item\n"
	.string "{CLEAR_TO 0x08}GREEN SHARD{CLEAR_TO 0x59}{LEFT_ARROW}{RIGHT_ARROW}{CLEAR_TO 0x7b}LEAF STONE$"
