LilycoveCity_DepartmentStore_5F_MapScripts::

@ During the abnormal weather from Kyogre/Groudon awakening the dept store rooftop is inaccessible
@ Likely done to avoid dealing with showing the weather. Technically the rooftop is indoors
LilycoveCity_DepartmentStore_5F_OnWarp:

LilycoveCity_DepartmentStore_5F_EventScript_BlockRoofStairs::

LilycoveCity_DepartmentStore_5F_EventScript_ClerkFarLeft::

LilycoveCity_DepartmentStore_5F_Pokemart_Dolls:

LilycoveCity_DepartmentStore_5F_EventScript_ClerkMidLeft::

LilycoveCity_DepartmentStore_5F_Pokemart_Cushions:

LilycoveCity_DepartmentStore_5F_EventScript_ClerkMidRight::

LilycoveCity_DepartmentStore_5F_Pokemart_Posters:

LilycoveCity_DepartmentStore_5F_EventScript_ClerkFarRight::

LilycoveCity_DepartmentStore_5F_Pokemart_Mats:

LilycoveCity_DepartmentStore_5F_EventScript_PokefanF::

LilycoveCity_DepartmentStore_5F_EventScript_Woman::

LilycoveCity_DepartmentStore_5F_EventScript_WomanNormal::

LilycoveCity_DepartmentStore_5F_EventScript_WomanLegendaryWeather::

LilycoveCity_DepartmentStore_5F_EventScript_LittleGirl::

LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls:
	.string "This place is full of cute DOLLS.\p"
	.string "I should buy some for me, instead of\n"
	.string "just for my children.$"

LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon:
	.string "I'm not big enough to raise POKéMON,\n"
	.string "so I'm getting a cute DOLL instead.$"

LilycoveCity_DepartmentStore_5F_Text_SellManyCuteMatsHere:
	.string "They sell many cute MATS here.\p"
	.string "I wonder which one I should get?\n"
	.string "Maybe I'll buy them all…$"

LilycoveCity_DepartmentStore_5F_Text_ClosedRooftopForWeather:
	.string "I think they closed the rooftop\n"
	.string "because the weather is wild today.$"
