LilycoveCity_DepartmentStoreRooftop_MapScripts::

LilycoveCity_DepartmentStoreRooftop_OnTransition:

LilycoveCity_DepartmentStoreRooftop_EventScript_ShowSaleWoman::

LilycoveCity_DepartmentStoreRooftop_EventScript_HideSaleWoman::

LilycoveCity_DepartmentStoreRooftop_EventScript_SaleWoman::

LilycoveCity_DepartmentStoreRooftop_PokemartDecor_ClearOutSale:

LilycoveCity_DepartmentStoreRooftop_EventScript_Man::

LilycoveCity_DepartmentStoreRooftop_EventScript_ManClearOutSale::

LilycoveCity_DepartmentStoreRooftop_EventScript_ThirstyMan::

LilycoveCity_DepartmentStoreRooftop_EventScript_VendingMachine::

LilycoveCity_DepartmentStoreRooftop_EventScript_ChooseDrink::

LilycoveCity_DepartmentStoreRooftop_EventScript_FreshWater::

LilycoveCity_DepartmentStoreRooftop_EventScript_SodaPop::

LilycoveCity_DepartmentStoreRooftop_EventScript_Lemonade::

LilycoveCity_DepartmentStoreRooftop_EventScript_CheckMoneyFreshWater::

LilycoveCity_DepartmentStoreRooftop_EventScript_CheckMoneySodaPop::

LilycoveCity_DepartmentStoreRooftop_EventScript_CheckMoneyLemonade::

LilycoveCity_DepartmentStoreRooftop_EventScript_RemoveMoneyFreshWater::

LilycoveCity_DepartmentStoreRooftop_EventScript_RemoveMoneySodaPop::

LilycoveCity_DepartmentStoreRooftop_EventScript_RemoveMoneyLemonade::

LilycoveCity_DepartmentStoreRooftop_EventScript_TryBuyDrink::

LilycoveCity_DepartmentStoreRooftop_EventScript_ChooseNewDrink::

LilycoveCity_DepartmentStoreRooftop_EventScript_NotEnoughMoneyForDrink::

LilycoveCity_DepartmentStoreRooftop_EventScript_NoRoomForDrink::

LilycoveCity_DepartmentStoreRooftop_EventScript_ExitVendingMachine::

LilycoveCity_DepartmentStoreRooftop_Text_SetDatesForClearOutSales:
	.string "Don't they have set dates for their\n"
	.string "clear-out sales?\p"
	.string "I watch TV, but they never show any\n"
	.string "commercials.$"

LilycoveCity_DepartmentStoreRooftop_Text_BeenWaitingForClearOutSale:
	.string "Yes! I've been waiting a long time for\n"
	.string "this clear-out sale.\p"
	.string "They have items that you can only get\n"
	.string "here. I'm going to load up, that I am!$"

LilycoveCity_DepartmentStoreRooftop_Text_BoneDryThirsty:
	.string "Ohh… I'm bone-dry thirsty!$"

LilycoveCity_DepartmentStoreRooftop_Text_WhichDrinkWouldYouLike:
	.string "It's a VENDING MACHINE.\n"
	.string "Which drink would you like?$"

LilycoveCity_DepartmentStoreRooftop_Text_CanOfDrinkDroppedDown:
	.string "Clang!\p"
	.string "A can of {STR_VAR_1} dropped down.$"

LilycoveCity_DepartmentStoreRooftop_Text_ExtraCanOfDrinkDroppedDown:
	.string "Clang!\p"
	.string "Score! An extra can of {STR_VAR_1}\n"
	.string "dropped down!$"

LilycoveCity_DepartmentStoreRooftop_Text_NotEnoughMoney:
	.string "Not enough money…$"

LilycoveCity_DepartmentStoreRooftop_Text_DecidedAgainstBuyingDrink:
	.string "Decided against buying a drink.$"
