IslandCave_MapScripts::

IslandCave_OnResume:

IslandCave_EventScript_TryRemoveRegice::

IslandCave_OnLoad:

IslandCave_EventScript_HideRegiEntrance::

IslandCave_OnTransition:

IslandCave_EventScript_ShowRegice::

IslandCave_EventScript_OpenRegiEntrance::

IslandCave_EventScript_CaveEntranceMiddle::

IslandCave_EventScript_BigHoleInWall::

IslandCave_EventScript_CaveEntranceSide::

IslandCave_EventScript_CloseBrailleMsg::

IslandCave_EventScript_ClearSteps::

IslandCave_EventScript_Regice::

IslandCave_EventScript_DefeatedRegice::

IslandCave_EventScript_RanFromRegice::
