SlateportCity_Mart_MapScripts::

SlateportCity_Mart_EventScript_Clerk::

SlateportCity_Mart_Pokemart:

SlateportCity_Mart_EventScript_BlackBelt::

SlateportCity_Mart_EventScript_Man::

SlateportCity_Mart_Text_SomeItemsOnlyAtMart:
	.string "The MARKET does have some interesting\n"
	.string "merchandise.\p"
	.string "But there are some items you can only\n"
	.string "get at a POKéMON MART.$"

SlateportCity_Mart_Text_GreatBallIsBetter:
	.string "A GREAT BALL is better than a POKé BALL\n"
	.string "at catching POKéMON.\p"
	.string "With this, I should be able to get that\n"
	.string "elusive POKéMON…$"

