Route125_MapScripts::

Route125_OnTransition:

Route125_OnLoad:

Route125_OnFrame:

Route125_EventScript_Nolen::

Route125_EventScript_Stan::

Route125_EventScript_Tanya::

Route125_EventScript_Sharon::

Route125_EventScript_Ernest::

Route125_EventScript_RegisterErnest::

Route125_EventScript_RematchErnest::

Route125_EventScript_Kim::

Route125_EventScript_Iris::

Route125_EventScript_Presley::

Route125_EventScript_Auron::

