gText_ObtainedTheItem::
	.string "{PLAYER} Obtained the {STR_VAR_2}!$"
gText_FoundTheItem::
	.string "{PLAYER} Found the {STR_VAR_2}!$"
gText_ObtainedTheHiddenItem::
	.string "{PLAYER} Obtained the hidden {STR_VAR_2}!$"
gText_FoundTheHiddenItem::
	.string "{PLAYER} Found the hidden {STR_VAR_2}!$"

gText_ObtainedItems::
	.string "{PLAYER} Obtained {STR_VAR_1} {STR_VAR_2}!$"
gText_FoundItems::
	.string "{PLAYER} Found {STR_VAR_1} {STR_VAR_2}!$"
gText_ObtainedHiddenItems::
	.string "{PLAYER} Obtained {STR_VAR_1} hidden {STR_VAR_2}!$"
gText_FoundHiddenItems::
	.string "{PLAYER} Found {STR_VAR_1} hidden {STR_VAR_2}!$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2} in the {STR_VAR_3} POCKET.$"
gText_SentItemToPC::
	.string "{PLAYER} transferred the {STR_VAR_2} to the PC.$"
gText_BagIsFull::
	.string "The BAG is full...$"
gText_PCIsFull::
	.string "Too bad! The PC is full...$"
gText_BagAndPCAreFull::
	.string "Too bad! Both the BAG and the PC are full...$"


gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"

gText_PutItemInPC::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the PC since bag is full.$"

gText_TooBadBagAndPCAreFull::
	.string "Too bad!\n"
	.string "The BAG and PC are full…$"
