Route102_MapScripts::

Route102_EventScript_LittleBoy::

Route102_EventScript_RouteSignOldale::

Route102_EventScript_RouteSignPetalburg::

Route102_EventScript_Boy::

Route102_EventScript_Calvin::

Route102_EventScript_CalvinRegisterMatchCallAfterBattle::

Route102_EventScript_CalvinRegisterMatchCall::

Route102_EventScript_CalvinTryRegister::

Route102_EventScript_CalvinRegister::

Route102_EventScript_CalvinRematch::

Route102_EventScript_Rick::

Route102_EventScript_Tiana::

Route102_EventScript_Allen::

Route102_Text_WatchMeCatchPokemon:
	.string "WALLY: {PLAYER}…\n"
	.string "POKéMON hide in tall grass like this,\l"
	.string "don't they?\p"
	.string "Please watch me and see if I can\n"
	.string "catch one properly.\p"
	.string "…Whoa!$"

Route102_Text_WallyIDidIt:
	.string "WALLY: I did it… It's my…\n"
	.string "My POKéMON!$"

Route102_Text_LetsGoBack:
	.string "{PLAYER}, thank you!\n"
	.string "Let's go back to the GYM!$"

Route102_Text_ImNotVeryTall:
	.string "I'm…not very tall, so I sink right\n"
	.string "into tall grass.\p"
	.string "The grass goes up my nose and…\n"
	.string "Fwafwafwafwafwa…\p"
	.string "Fwatchoo!$"

Route102_Text_CatchWholeBunchOfPokemon:
	.string "I'm going to catch a whole bunch of\n"
	.string "POKéMON!$"

Route102_Text_RouteSignOldale:
	.string "ROUTE 102\n"
	.string "{RIGHT_ARROW} OLDALE TOWN$"

Route102_Text_RouteSignPetalburg:
	.string "ROUTE 102\n"
	.string "{LEFT_ARROW} PETALBURG CITY$"
