ShoalCave_LowTideLowerRoom_MapScripts::

ShoalCave_LowTideLowerRoom_OnLoad:

ShoalCave_LowTideLowerRoom_EventScript_SetShoalItemMetatiles::

ShoalCave_LowTideLowerRoom_EventScript_SetShoalItemMetatilesEnd::

ShoalCave_LowTideLowerRoom_EventScript_ShoalSalt4::

ShoalCave_LowTideLowerRoom_EventScript_ReceivedShoalSalt::

ShoalCave_LowTideLowerRoom_EventScript_BlackBelt::

ShoalCave_LowTideLowerRoom_EventScript_ReceivedFocusBand::

ShoalCave_LowTideLowerRoom_Text_CanOvercomeColdWithFocus:
	.string "The penetrating cold around these\n"
	.string "parts is an impediment to training.\p"
	.string "But with focus, one can overcome!\p"
	.string "With this FOCUS BAND, buckle down and\n"
	.string "withstand the cold!$"

ShoalCave_LowTideLowerRoom_Text_EverythingStartsWithFocus:
	.string "Everything starts with focus!$"

