EverGrandeCity_HallOfFame_MapScripts::

EverGrandeCity_HallOfFame_OnWarp:

EverGrandeCity_HallOfFame_EventScript_TurnPlayerNorth::

EverGrandeCity_HallOfFame_OnFrame:

EverGrandeCity_HallOfFame_EventScript_EnterHallOfFame::

EverGrandeCity_HallOfFame_EventScript_GameClearMale::

EverGrandeCity_HallOfFame_EventScript_GameClearFemale::

EverGrandeCity_HallOfFame_Movement_WalkIntoHallOfFame1:

EverGrandeCity_HallOfFame_Movement_WalkIntoHallOfFame2:

EverGrandeCity_HallOfFame_Text_HereWeHonorLeagueChampions:
	.string "WALLACE: This room…\p"
	.string "This is where we keep records of\n"
	.string "POKéMON that prevailed through\l"
	.string "harsh battles.\p"
	.string "It is here that the LEAGUE CHAMPIONS\n"
	.string "are honored.$"

EverGrandeCity_HallOfFame_Text_LetsRecordYouAndYourPartnersNames:
	.string "WALLACE: Come on, let's record your\n"
	.string "name as a TRAINER who triumphed over\l"
	.string "the POKéMON LEAGUE, and the names of\l"
	.string "the partners who battled with you.$"

