Route105_MapScripts::

Route105_OnLoad:

Route105_CloseRegiEntrance::

Route105_OnTransition:

Route105_OnFrame:

Route105_EventScript_Foster::

Route105_EventScript_Luis::

Route105_EventScript_Dominik::

Route105_EventScript_Beverly::

Route105_EventScript_Imani::

Route105_EventScript_Josue::

Route105_EventScript_Andres::

Route105_EventScript_AndresRegisterMatchCallAfterBattle::

Route105_EventScript_AndresRematch::

Route104_Text_DadPokenavCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "DAD: Oh, {PLAYER}?\p"
	.string "… … … … … …\n"
	.string "Where are you now?\l"
	.string "It sounds windy wherever you are.\p"
	.string "I just heard from DEVON's MR. STONE\n"
	.string "about your POKéNAV, so I decided\l"
	.string "to give you a call.\p"
	.string "It sounds like you're doing fine,\n"
	.string "so that's fine with me.\p"
	.string "You take care now.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

Route104_Text_RegisteredDadInPokenav:
	.string "Registered DAD NORMAN\n"
	.string "in the POKéNAV.$"
