EverGrandeCity_SidneysRoom_MapScripts::

EverGrandeCity_SidneysRoom_OnTransition:

EverGrandeCity_SidneysRoom_OnLoad:

EverGrandeCity_SidneysRoom_EventScript_ResetAdvanceToNextRoom::

EverGrandeCity_SidneysRoom_EventScript_CloseDoor::

EverGrandeCity_SidneysRoom_OnWarp:

EverGrandeCity_SidneysRoom_EventScript_PlayerTurnNorth::

EverGrandeCity_SidneysRoom_OnFrame:

EverGrandeCity_SidneysRoom_EventScript_WalkInCloseDoor::

EverGrandeCity_SidneysRoom_EventScript_Sidney::

EverGrandeCity_SidneysRoom_EventScript_PostBattleSpeech::

EverGrandeCity_SidneysRoom_EventScript_Defeated::

EverGrandeCity_SidneysRoom_Text_IntroSpeech:
	.string "Welcome, challenger!\n"
	.string "I'm SIDNEY of the ELITE FOUR.\p"
	.string "I like that look you're giving me.\n"
	.string "I guess you'll give me a good match.\l"
	.string "That's good! Looking real good!\p"
	.string "All right! You and me, let's enjoy\n"
	.string "a battle that can only be staged\l"
	.string "here in the POKéMON LEAGUE!$"

EverGrandeCity_SidneysRoom_Text_Defeat:
	.string "Well, how do you like that? I lost!\n"
	.string "Eh, it was fun, so it doesn't matter.$"

EverGrandeCity_SidneysRoom_Text_PostBattleSpeech:
	.string "Well, listen to what this loser has\n"
	.string "to say.\p"
	.string "You've got what it takes to go far.\n"
	.string "Now, go on to the next room and enjoy\l"
	.string "your next battle!$"

