Route104_MapScripts::

Route104_OnFrame:

Route104_EventScript_StartSailToDewford::

Route104_OnTransition:

Route104_EventScript_ShowOrHideWhiteHerbFlorist::

Route104_EventScript_HideWhiteHerbFlorist::

Route104_EventScript_TrySetRivalPos::

Route104_EventScript_DontSetRivalPos::

Route104_EventScript_Rival::

Route104_EventScript_RivalTrigger::

@ Unused, shares script with Rustboro encounter instead
Route104_EventScript_PlayRivalMusic::

Route104_EventScript_PlayMayMusic::

Route104_EventScript_PlayBrendanMusic::

Route104_EventScript_RivalEncounter::

Route104_EventScript_MayEncounter::

Route104_Movement_RivalWalkSlowLeft:

Route104_Movement_RivalApproachPlayer:

Route104_Movement_PlayerFaceRival:

Route104_EventScript_MayAskToBattle::

Route104_EventScript_BattleMay::

Route104_EventScript_MayDefeated::

Route104_EventScript_RestoreMusic::

Route104_EventScript_BattleMayTreecko::

Route104_EventScript_BattleMayTorchic::

Route104_EventScript_BattleMayMudkip::

Route104_EventScript_BrendanEncounter::

Route104_EventScript_BrendanAskToBattle::

Route104_EventScript_BattleBrendan::

Route104_EventScript_BrendanDefeated::

Route104_EventScript_BattleBrendanTreecko::

Route104_EventScript_BattleBrendanTorchic::

Route104_EventScript_BattleBrendanMudkip::

Route104_Movement_PlayerBackUp:

Route104_Movement_RivalExitBrineysCottage:

Route104_EventScript_ExpertF::

Route104_EventScript_ReceivedBerry::

Route104_EventScript_WhiteHerbFlorist::

Route104_EventScript_ReceivedWhiteHerb::

Route104_EventScript_Girl1::

Route104_EventScript_BugCatcher::

Route104_EventScript_BrineysCottageSign::

Route104_EventScript_RouteSignPetalburg::

Route104_EventScript_RouteSignRustboro::

Route104_EventScript_FlowerShopSign::

Route104_EventScript_TrainerTipsDoubleBattles::

Route104_EventScript_Boy1::

Route104_EventScript_Woman::

Route104_EventScript_Boy2::

Route104_EventScript_ReceivedBulletSeed::

Route104_EventScript_Girl2::

Route104_EventScript_SailToDewford::

Route104_EventScript_SailToDewfordNoCall::

Route104_EventScript_SailToDewfordDadCalls::

Route104_EventScript_ArriveInDewford::

Route104_EventScript_DeliverLetterReminder::

Route104_EventScript_LandedInDewford::

Route104_Movement_SailToDewfordBeforeDadCalls:

Route104_Movement_SailToDewfordAfterDadCalls:

Route104_Movement_SailToDewford:

Route104_Movement_PlayerBoardBoat:

Route104_Movement_PlayerExitBoat:

Route104_Movement_PlayerMoveForBriney:

Route104_Movement_BrineyBoardBoat:

Route104_Movement_BrineyExitBoat:

Route104_EventScript_Ivan::

Route104_EventScript_Billy::

Route104_EventScript_Haley::

Route104_EventScript_TryRegisterHaleyAfterBattle::

Route104_EventScript_RegisterHaleyAfterBattle::

Route104_EventScript_TryRegisterHaley::

Route104_EventScript_RegisterHaley::

Route104_EventScript_RematchHaley::

Route104_EventScript_Winston::

Route104_EventScript_TryRegisterWinstonAfterBattle::

Route104_EventScript_RegisterWinstonAfterBattle::

Route104_EventScript_TryRegisterWinston::

Route104_EventScript_RegisterWinston::

Route104_EventScript_RematchWinston::

Route104_EventScript_Cindy::

Route104_EventScript_TryRegisterCindyAfterBattle::

Route104_EventScript_RegisterCindyAfterBattle::

Route104_EventScript_TryRegisterCindy::

Route104_EventScript_RegisterCindy::

Route104_EventScript_RematchCindy::

Route104_EventScript_Gina::

Route104_EventScript_Mia::

Route104_EventScript_Darian::

Route104_Text_BrineyLivesInSeasideCottage:
	.string "That seaside cottage is where\n"
	.string "MR. BRINEY lives.\p"
	.string "He was once a mighty sailor who never\n"
	.string "feared the sea, however stormy.$"

Route104_Text_WhatsItLikeAtBottomOfSea:
	.string "The sea, huh?\p"
	.string "I wonder what it's like at the bottom\n"
	.string "of the sea?$"

Route104_Text_ThrowBallAtWeakenedPokemon:
	.string "If you're going to throw a POKé BALL,\n"
	.string "weaken the wild POKéMON first.\p"
	.string "It will be easier to catch if it's been\n"
	.string "poisoned, burned, or lulled to sleep.$"

Route104_Text_OnlyThrowBallAtWildPokemon:
	.string "You're a thief if you try to steal\n"
	.string "someone else's POKéMON.\p"
	.string "You should throw POKé BALLS only at\n"
	.string "wild POKéMON.$"

Route104_Text_ImNotATrainer:
	.string "Oh, no, I'm not a TRAINER.\p"
	.string "But that's right, if TRAINERS lock eyes,\n"
	.string "it's a challenge to battle.\p"
	.string "If you don't want to battle, stay out\n"
	.string "of their sight.$"

Route104_Text_LikeFillingMouthWithSeedsTakeThis:
	.string "I like filling my mouth with seeds,\n"
	.string "then spitting them out fast!\p"
	.string "You can have this, so you try it out!\p"
	.string "Use it on a POKéMON, and it will learn\n"
	.string "a move for firing seeds rapidly.$"

Route104_Text_TMsAreOneTimeUse:
	.string "A word of advice!\p"
	.string "A TM, TECHNICAL MACHINE, is good only\n"
	.string "for one-time use.\p"
	.string "Once you use it, it's gone.\n"
	.string "Think twice before using it!$"

Route104_Text_DontNeedThisTakeIt:
	.string "This FLOWER SHOP started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping.\p"
	.string "I don't need this WHITE HERB anymore.\n"
	.string "Would you take it, please?$"

Route104_Text_FlowerShopSellingSaplings:
	.string "This FLOWER SHOP started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping. Where should I put them?$"

Route104_Text_MrBrineysCottage:
	.string "MR. BRINEY'S COTTAGE$"

Route104_Text_RouteSignPetalburg:
	.string "ROUTE 1O4\n"
	.string "{RIGHT_ARROW} PETALBURG CITY$"

Route104_Text_RouteSignRustboro:
	.string "ROUTE 1O4\n"
	.string "{UP_ARROW} RUSTBORO CITY$"

Route104_Text_PrettyPetalFlowShop:
	.string "PRETTY PETAL FLOWER SHOP$"

Route104_Text_TrainerTipsDoubleBattles:
	.string "TRAINER TIPS\p"
	.string "In the HOENN region there are pairs\n"
	.string "of TRAINERS who challenge others\l"
	.string "for 2-on-2 POKéMON battles called\l"
	.string "DOUBLE BATTLES.\p"
	.string "In a DOUBLE BATTLE, the TRAINER must\n"
	.string "send out two POKéMON, the one at the\l"
	.string "left of the list and the top one.\l"
	.string "Watch how POKéMON are lined up.$"

Route104_Text_MayWeShouldRegister:
	.string "MAY: Oh, hi, {PLAYER}{KUN}!\p"
	.string "DEVON upgraded your POKéNAV with\n"
	.string "the MATCH CALL system, huh?\p"
	.string "We should register each other so we\n"
	.string "can get in contact anytime.$"

Route104_Text_RegisteredMay:
	.string "{PLAYER} registered MAY\n"
	.string "in the POKéNAV.$"

Route104_Text_MayHowsYourPokedex:
	.string "MAY: Oh, by the way, {PLAYER}{KUN},\n"
	.string "how's your POKéDEX coming along?$"

Route104_Text_MayMinesDecentLetsBattle:
	.string "Mine's looking pretty decent.\n"
	.string "So…\l"
	.string "How about a little battle?$"

Route104_Text_MayHaventRaisedPokemon:
	.string "MAY: Oh, what's the matter?\p"
	.string "Haven't you caught or raised your\n"
	.string "POKéMON very much?\p"
	.string "That's not very good for a TRAINER!$"

Route104_Text_MayLetsBattle:
	.string "MAY: So, what do you think?\n"
	.string "How about a little battle here?$"

Route104_Text_MayIntro:
	.string "MAY: You just became a TRAINER,\n"
	.string "{PLAYER}{KUN}. I'm not going to lose!$"

Route104_Text_MayDefeat:
	.string "Yikes!\n"
	.string "You're better than I expected!$"

Route104_Text_MayPostBattle:
	.string "MAY: I can tell you've gotten pretty\n"
	.string "good with the way you handle POKéMON.\p"
	.string "But instead of only making them\n"
	.string "battle, you should be like MR. BRINEY.\p"
	.string "It's important to become friends with\n"
	.string "POKéMON, too.$"

Route104_Text_BrendanWeShouldRegister:
	.string "BRENDAN: Oh, hey, {PLAYER}!\p"
	.string "Cool, you had DEVON install the MATCH\n"
	.string "CALL system on your POKéNAV!\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS so we can keep in touch.$"

Route104_Text_RegisteredBrendan:
	.string "{PLAYER} registered BRENDAN\n"
	.string "in the POKéNAV.$"

Route104_Text_BrendanHowsYourPokedex:
	.string "BRENDAN: {PLAYER}, how's your POKéDEX?\n"
	.string "Have you filled in any pages yet?$"

Route104_Text_BrendanDoingGreatLetsBattle:
	.string "Me, I'm doing great!\p"
	.string "Want to check out how good I am with\n"
	.string "a battle?$"

Route104_Text_BrendanNoConfidence:
	.string "BRENDAN: What's the matter? Don't have\n"
	.string "any confidence in your POKéMON?$"

Route104_Text_BrendanLetsBattle:
	.string "BRENDAN: What's up?\n"
	.string "Want to have a battle with me?$"

Route104_Text_BrendanIntro:
	.string "BRENDAN: I know you just became\n"
	.string "a TRAINER, but I won't go easy!$"

Route104_Text_BrendanDefeat:
	.string "Hmm…\n"
	.string "You're pretty good.$"

Route104_Text_BrendanPostBattle:
	.string "BRENDAN: You've gotten pretty decent\n"
	.string "at handling POKéMON.\p"
	.string "But, you know, you shouldn't just be\n"
	.string "making POKéMON battle.\p"
	.string "Like MR. BRINEY, it's important to\n"
	.string "become friends with your POKéMON.$"
