Route124_MapScripts::

Route124_OnTransition:

Route124_EventScript_HuntersHouseSign::

Route124_EventScript_Spencer::

Route124_EventScript_Roland::

Route124_EventScript_Jenny::

Route124_EventScript_RegisterJenny::

Route124_EventScript_RematchJenny::

Route124_EventScript_Grace::

Route124_EventScript_Chad::

Route124_EventScript_Lila::

Route124_EventScript_RegisterLila::

Route124_EventScript_RematchLila::

Route124_EventScript_Roy::

Route124_EventScript_RegisterRoy::

Route124_EventScript_RematchRoy::

Route124_EventScript_Declan::

Route124_EventScript_Isabella::

Route124_Text_HuntersHouse:
	.string "HUNTER'S HOUSE$"

