@ NOTE: Route 109's sail to Dewford script references local IDs from Dewford's map.
@  These are labeled in DewfordTown/scripts.inc

Route109_MapScripts::

Route109_EventScript_StartDepartForDewford::

Route109_EventScript_EnterBoatSouth::

Route109_EventScript_EnterBoatEast::

Route109_EventScript_EnterBoatWest::

Route109_EventScript_DoSailToDewford::

Route109_Movement_SailToDewford:

Route109_Movement_PlayerEnterBoatSouth:

Route109_Movement_PlayerExitBoat:

Route109_Movement_PlayerEnterBoatEast:

Route109_Movement_PlayerEnterBoatWest:

Route109_Movement_BrineyEnterBoat:

Route109_Movement_BrineyExitBoat:

Route109_EventScript_MrBriney::

Route109_EventScript_HaveNotDeliveredDevonGood::

Route109_EventScript_DeliveredDevonGoods::

Route109_EventScript_SailToDewford::

Route109_EventScript_StayHere::

Route109_EventScript_ChoseNotToSail::

Route109_EventScript_SeashoreHouseGirl::

Route109_EventScript_SandCastleBoy::

Route109_EventScript_SoftSandGirl::

Route109_EventScript_AlreadyReceivedSoftSand::

Route109_EventScript_Woman::

Route109_EventScript_OldMan::

Route109_EventScript_Zigzagoon::

Route109_EventScript_SeashoreHouseSign::

Route109_EventScript_TrainerTipsSign::

Route109_EventScript_David::

Route109_EventScript_Alice::

Route109_EventScript_Huey::

Route109_EventScript_Edmond::

Route109_EventScript_Ricky::

Route109_EventScript_RickyRegisterMatchCallAfterBattle::

Route109_EventScript_RickyRematch::

Route109_EventScript_Lola::

Route109_EventScript_LolaRegisterMatchCallAfterBattle::

Route109_EventScript_LolaRematch::

Route109_EventScript_Austina::

Route109_EventScript_Gwen::

Route109_EventScript_Carter::

Route109_EventScript_Paul::

Route109_EventScript_Mel::

Route109_EventScript_Chandler::

Route109_EventScript_Hailey::

Route109_EventScript_Elijah::

DewfordTown_Text_BrineyLandedInSlateportDeliverGoods:
	.string "MR. BRINEY: Ahoy!\n"
	.string "We've made land in SLATEPORT!\p"
	.string "I suppose you're going to visit CAPT.\n"
	.string "STERN and deliver the DEVON GOODS?$"

Route109_Text_BrineySailToDewfordQuestion:
	.string "MR. BRINEY: I thought you're supposed\n"
	.string "to deliver the DEVON GOODS.\p"
	.string "Would you like to sail back to\n"
	.string "DEWFORD, then?$"

Route109_Text_BrineyDewfordItIs:
	.string "MR. BRINEY: DEWFORD it is, then!\p"
	.string "Anchors aweigh!\n"
	.string "PEEKO, we're setting sail, my darling!$"

Route109_Text_BrineyDeliverDevonGoods:
	.string "MR. BRINEY: Then you go on and deliver\n"
	.string "the DEVON GOODS. I'll be waiting.$"

DewfordTown_Text_BrineyLandedInSlateport:
	.string "MR. BRINEY: Ahoy! We've made land in\n"
	.string "SLATEPORT!\p"
	.string "You just go on and tell me whenever\n"
	.string "you want to set sail again!$"

Route109_Text_BrineyWhereAreWeBound:
	.string "MR. BRINEY: Ahoy!\n"
	.string "For you, I'll go out to sea anytime!\p"
	.string "Now, my friend, where are we bound?$"

Route109_Text_BrineyTellMeWhenYouNeedToSail:
	.string "MR. BRINEY: You just tell me whenever\n"
	.string "you need to set sail again!$"

Route109_Text_ChillAtMyPapasSpot:
	.string "Yo, TRAINERS!\n"
	.string "Whether you're hot to trot,\l"
	.string "or cool cat not,\l"
	.string "chill at my papa's spot!$"

Route109_Text_LittleKidsDartAround:
	.string "Little kids can dart around so quickly…\p"
	.string "You don't dare take your eyes off them\n"
	.string "for an instant. It's very taxing.\p"
	.string "Mine are with my POKéMON, so they\n"
	.string "should be okay, but…$"

Route109_Text_SandCastleTakingLongTime:
	.string "Our sand castle's taking a long time\n"
	.string "to make.$"

Route109_Text_YouCanHaveThis:
	.string "You can have this!$"

Route109_Text_WereGoingToMakeBigCastle:
	.string "We're going to get all the sand from\n"
	.string "the beach and make a big castle!\p"
	.string "And then we're going to be a king and\n"
	.string "queen.\p"
	.string "We'll let you be a servant.$"

Route109_Text_ZigzagoonPicksUpLitter:
	.string "The water around these parts is clean.\p"
	.string "But, I get my ZIGZAGOON to pick up\n"
	.string "litter from the shoreline at times.\p"
	.string "Dirty water becomes rain and joins our\n"
	.string "rivers, which we drink from…\p"
	.string "If we pollute the sea, it all comes\n"
	.string "back to haunt us eventually.$"

Route109_Text_ZigzagoonCry:
	.string "ZIGZAGOON: Guguu?$"

Route109_Text_SeashoreHouseSign:
	.string "SEASHORE HOUSE\p"
	.string "“May hot battles rage on hot sands!\n"
	.string "The place for hot TRAINERS!”$"

Route109_Text_TrainerTipsSign:
	.string "TRAINER TIPS\p"
	.string "POKéMON at the same level may not\n"
	.string "always have identical stats.\p"
	.string "POKéMON raised by TRAINERS are said\n"
	.string "to grow stronger than wild POKéMON.$"
