Route123_MapScripts::

Route123_OnTransition:

Route123_EventScript_GigaDrainGirl::

Route123_EventScript_NoGrassMons::

Route123_EventScript_ReceivedGigaDrain::

Route123_EventScript_RouteSign::

Route123_EventScript_RouteSignMtPyre::

Route123_EventScript_BerryMastersHouseSign::

Route123_EventScript_Wendy::

Route123_EventScript_Braxton::

Route123_EventScript_Violet::

Route123_EventScript_Cameron::

Route123_EventScript_RegisterCameron::

Route123_EventScript_RematchCameron::

Route123_EventScript_Jacki::

Route123_EventScript_RegisterJacki::

Route123_EventScript_RematchJacki::

Route123_EventScript_Miu::

Route123_EventScript_Yuki::

Route123_EventScript_Kindra::

Route123_EventScript_Frederick::

Route123_EventScript_Alberto::

Route123_EventScript_Ed::

Route123_EventScript_Kayley::

Route123_EventScript_Jonas::

Route123_EventScript_Jazmyn::

Route123_EventScript_Davis::

Route123_EventScript_Fernando::

Route123_EventScript_RegisterFernando::

Route123_EventScript_RematchFernando::

Route123_Text_LoveGrassMonsHaveAny:
	.string "I love GRASS-type POKéMON!\p"
	.string "Do you have any GRASS-type POKéMON?$"

Route123_Text_YouLikeGrassMonsTooHaveThis:
	.string "Oh?\p"
	.string "You like GRASS-type POKéMON, too,\n"
	.string "don't you?\p"
	.string "I'm so happy, you can have this!\n"
	.string "It's a token of our friendship.$"

Route123_Text_CheckTreesWithMyGrassMon:
	.string "I check trees with my GRASS-type\n"
	.string "POKéMON. I'm like a tree doctor.$"

Route123_Text_RouteSign:
	.string "{RIGHT_ARROW} ROUTE 123\n"
	.string "{LEFT_ARROW} ROUTE 118$"

Route123_Text_RouteSignMtPyre:
	.string "{UP_ARROW} MT. PYRE\n"
	.string "“Forbidden to the faint of heart.”$"

Route123_Text_BerryMastersHouse:
	.string "BERRY MASTER'S HOUSE$"

