LilycoveCity_DepartmentStore_3F_MapScripts::

LilycoveCity_DepartmentStore_3F_EventScript_ClerkLeft::

LilycoveCity_DepartmentStore_3F_Pokemart_Vitamins:

LilycoveCity_DepartmentStore_3F_EventScript_ClerkRight::

LilycoveCity_DepartmentStore_3F_Pokemart_StatBoosters:

LilycoveCity_DepartmentStore_3F_EventScript_TriathleteM::

LilycoveCity_DepartmentStore_3F_EventScript_PokefanM::

LilycoveCity_DepartmentStore_3F_EventScript_Woman::

LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon:
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK,\n"
	.string "and CALCIUM raises SP. ATK.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance:
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon:
	.string "I gave a CARBOS to my POKéMON,\n"
	.string "and its SPEED went up.$"

