Route111_MapScripts::

Route111_OnLoad:

Route111_EventScript_CloseDesertRuins::

@ Show Mirage Tower just prior to disintegration. Mirage Tower is otherwise handled by the map layout
Route111_EventScript_ShowTemporaryMirageTower::

Route111_OnTransition:

Route111_EventScript_SetFallingPlayerGfx::

Route111_EventScript_SetFallingPlayerGfxMale::

Route111_EventScript_SetFallingPlayerGfxFemale::

Route111_EventScript_CheckSetSandstorm::
Route111_EventScript_SetSandstorm::
Route111_EventScript_EndCheckSetSandstorm::

Route111_EventScript_SetWinstratesNotDefeated::

Route111_EventScript_SetLayoutNoMirageTower::

Route111_EventScript_SetMirageTowerGone::

Route111_OnWarp:

Route111_EventScript_HidePlayerForMirageTower::

Route111_OnFrame:

Route111_EventScript_MirageTowerDisappear::

Route111_EventScript_RootFossilDisappeared::

@ Unused
Route111_Movement_PlayerFall::

Route111_EventScript_Girl::

Route111_EventScript_ReceivedBerry::

@ Unused
Route111_EventScript_ViciousSandstormTriggerUp::

Route111_EventScript_ViciousSandstormTriggerDown::

Route111_EventScript_ViciousSandstormTriggerLeft::

@ Unused
Route111_EventScript_ViciousSandstormTriggerRight::

Route111_EventScript_ViciousSandstormTrigger::

Route111_EventScript_PreventRouteAccess::

Route111_EventScript_PushUpFromRoute::

Route111_EventScript_PushDownFromRoute::

Route111_EventScript_PushLeftFromRoute::

Route111_EventScript_PushRightFromRoute::

Route111_Movement_PushUpFromRoute:

Route111_Movement_PushDownFromRoute:

Route111_Movement_PushLeftFromRoute:

Route111_Movement_PushRightFromRoute:

Route111_EventScript_SunTrigger::

Route111_EventScript_SandstormTrigger::

Route111_EventScript_Victor::

Route111_EventScript_BattleWinstrates::

Route111_EventScript_OpenWinstrateDoor::

Route111_EventScript_CloseWinstrateDoor::

Route111_Movement_WinstrateEnterHouse:

Route111_Movement_WinstrateExitHouse:

Route111_Movement_WaitForNextWinstrate:

Route111_EventScript_RouteSignMauville::

Route111_EventScript_WinstrateHouseSign::

Route111_EventScript_RouteSign112::

Route111_EventScript_RouteSign113::

Route111_EventScript_OldLadysRestStopSign::

Route111_EventScript_TrainerTipsSpAtkSpDef::

Route111_EventScript_Man1::

Route111_EventScript_Man2::

Route111_EventScript_Hiker::

Route111_EventScript_HikerMirageTowerGone::

Route111_EventScript_HikerMirageTowerDisintegrated::

Route111_EventScript_HikerMirageTowerVisible::

Route111_EventScript_RockSmashTipFatMan::

Route111_EventScript_Drew::

Route111_EventScript_Heidi::

Route111_EventScript_Beau::

Route111_EventScript_Becky::

Route111_EventScript_Dusty::

Route111_EventScript_RegisterDusty::

Route111_EventScript_RematchDusty::

Route111_EventScript_Travis::

Route111_EventScript_Irene::

Route111_EventScript_Daisuke::

Route111_EventScript_Wilton::

Route111_EventScript_RegisterWilton::

Route111_EventScript_RematchWilton::

Route111_EventScript_Brooke::

Route111_EventScript_RegisterBrooke::

Route111_EventScript_RematchBrooke::

Route111_EventScript_Hayden::

Route111_EventScript_Bianca::

Route111_EventScript_Tyron::

Route111_EventScript_Celina::

Route111_EventScript_Celia::

Route111_EventScript_Bryan::

Route111_EventScript_Branden::

Route111_EventScript_TrainerHillSign::

Route111_Text_BattleOurFamily:
	.string "Hello! I take it you're a traveler.\p"
	.string "How's this? What do you say to taking\n"
	.string "on our family of four in a series of\l"
	.string "POKéMON battles?$"

Route111_Text_IsThatSo:
	.string "Is that so?\n"
	.string "Drop in, if you change your mind!$"

Route111_Text_VictorIntro:
	.string "That's the spirit! I like you!$"

Route111_Text_VictorDefeat:
	.string "Aiyah!\n"
	.string "You're a lot tougher than I expected!$"

Route111_Text_VictorPostBattle:
	.string "Hey, all!\n"
	.string "I've found a pretty strong TRAINER!$"

Route111_Text_VictoriaIntro:
	.string "Oh, my goodness! Aren't you young?\p"
	.string "You must be quite the TRAINER to beat\n"
	.string "my husband, though.\p"
	.string "It's my turn to battle now!$"

Route111_Text_VictoriaDefeat:
	.string "Oh, gosh!\n"
	.string "I can't get over how strong you are!$"

Route111_Text_VictoriaPostBattle:
	.string "There's a strong TRAINER here!\n"
	.string "This one's really strong!$"

Route111_Text_ViviIntro:
	.string "You're stronger than Mommy? Wow!\p"
	.string "But I'm strong, too!\n"
	.string "Really! Honestly!$"

Route111_Text_ViviDefeat:
	.string "Huh? Did I just lose?$"

Route111_Text_ViviPostBattle:
	.string "This stinks…\p"
	.string "…Snivel… Grandma!$"

Route111_Text_VickyIntro:
	.string "How dare you make my granddaughter\n"
	.string "cry!\p"
	.string "For that, I'm going to smack you!\n"
	.string "Prepare to lose!$"

Route111_Text_VickyDefeat:
	.string "Kwah! You are strong…\n"
	.string "My granddaughter was right…$"

Route111_Text_VickyPostBattle:
	.string "If you're not in any hurry,\n"
	.string "visit with us awhile.$"

Route111_Text_ToughToKeepWinningUpTheRanks:
	.string "If you don't raise your POKéMON some\n"
	.string "more, it could be tough to keep winning\l"
	.string "up through the ranks.\p"
	.string "I've heard the POKéMON LEAGUE's\n"
	.string "ELITE FOUR are far stronger than\l"
	.string "any GYM LEADER.$"

Route111_Text_WinstrateFamilyDestroyedMe:
	.string "I challenged the WINSTRATE family,\n"
	.string "but four matches in a row is tough\l"
	.string "going… They destroyed me.$"

Route111_Text_RouteSignMauville:
	.string "ROUTE 111\n"
	.string "{DOWN_ARROW} MAUVILLE CITY$"

Route111_Text_WinstrateHouseSign:
	.string "“Our family's hearts beat as one!”\n"
	.string "THE WINSTRATE'S HOUSE$"

Route111_Text_RouteSign112:
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 112$"

Route111_Text_RouteSign113:
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 113$"

Route111_Text_OldLadysRestStopSign:
	.string "OLD LADY'S REST STOP\n"
	.string "“Come in and rest your tired bones.”$"

Route111_Text_TrainerTipsSpAtkSpDef:
	.string "TRAINER TIPS\p"
	.string "One of the indicators of a POKéMON's\n"
	.string "powerfulness is SP. ATK. It stands for\l"
	.string "“SPECIAL ATTACK.”\p"
	.string "Likewise, SP. DEF stands for “SPECIAL\n"
	.string "DEFENSE.”$"

Route111_Text_ShouldBeMirageTowerAroundHere:
	.string "There should be a tower made of sand\n"
	.string "around here somewhere.\p"
	.string "But for some reason, it can be seen\n"
	.string "sometimes, and sometimes not.\p"
	.string "That's why I call it the MIRAGE TOWER.$"

Route111_Text_MirageTowerClearlyVisible:
	.string "I see it!\n"
	.string "The tower of sand!\p"
	.string "The sand tower they called a mirage\n"
	.string "is clearly visible!\p"
	.string "But it looks so fragile…\n"
	.string "It could crumble away anytime…\p"
	.string "I want to go inside it, but I can't\n"
	.string "get my courage up for it…$"

Route111_Text_ThatWasShockingSandRainedDown:
	.string "Whoa…\n"
	.string "That was shocking.\p"
	.string "Sand rained down in chunks all of\n"
	.string "a sudden.\p"
	.string "What was it like inside?\n"
	.string "Were there sandy ghosts and such?$"

Route111_Text_MirageTowerHasntBeenSeenSince:
	.string "Since I spoke to you, the tower of sand\n"
	.string "hasn't been seen.\p"
	.string "Perhaps it really was\n"
	.string "the MIRAGE TOWER…$"

Route111_Text_ClawFossilDisappeared:
	.string "The CLAW FOSSIL disappeared into\n"
	.string "the sand…$"

Route111_Text_RootFossilDisappeared:
	.string "The ROOT FOSSIL disappeared into\n"
	.string "the sand…$"

Route111_Text_MauvilleUncleToldMeToTakeRockSmash:
	.string "Oh, no!\p"
	.string "My uncle in MAUVILLE told me to take\n"
	.string "ROCK SMASH with me if I was going to\l"
	.string "ROUTE 111!\p"
	.string "My uncle? He lives across from\n"
	.string "the bike shop in MAUVILLE.$"

Route111_Text_TrainerHillSign:
	.string "{RIGHT_ARROW} TRAINER HILL ENTRANCE\p"
	.string "“Scale the heights, you hot-blooded\n"
	.string "TRAINERS!”$"

