BattleFrontier_RankingHall_MapScripts::

BattleFrontier_RankingHall_EventScript_TowerSinglesRecords::

BattleFrontier_RankingHall_EventScript_TowerDoublesRecords::

BattleFrontier_RankingHall_EventScript_TowerMultisRecords::

BattleFrontier_RankingHall_EventScript_TowerLinkRecords::

BattleFrontier_RankingHall_EventScript_ArenaRecords::

BattleFrontier_RankingHall_EventScript_PalaceRecords::

BattleFrontier_RankingHall_EventScript_FactoryRecords::

BattleFrontier_RankingHall_EventScript_DomeRecords::

BattleFrontier_RankingHall_EventScript_PikeRecords::

BattleFrontier_RankingHall_EventScript_PyramidRecords::

BattleFrontier_RankingHall_EventScript_ShowRecords::

BattleFrontier_RankingHall_EventScript_Attendant::

BattleFrontier_RankingHall_EventScript_DomePikeFactoryRecordsSign::

BattleFrontier_RankingHall_EventScript_PalaceArenaPyramidRecordsSIgn::

BattleFrontier_RankingHall_EventScript_NinjaBoy::

BattleFrontier_RankingHall_EventScript_NinjaBoyNameOnList::

BattleFrontier_RankingHall_EventScript_Boy::

BattleFrontier_RankingHall_Text_ExplainRankingHall:
	.string "This is the RANKING HALL.\p"
	.string "This is where we recognize the immortal\n"
	.string "TRAINERS who left great records in\l"
	.string "BATTLE FRONTIER events.$"

BattleFrontier_RankingHall_Text_DomePikeFactoryRecords:
	.string "BATTLE DOME, BATTLE PIKE,\n"
	.string "and BATTLE FACTORY Records$"

BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords:
	.string "BATTLE PALACE, BATTLE ARENA,\n"
	.string "and BATTLE PYRAMID Records$"

BattleFrontier_RankingHall_Text_IsYourNameOnThisList:
	.string "Hi, is your name on this list?$"

BattleFrontier_RankingHall_Text_WowThatsSuper:
	.string "Wow, that's super!\n"
	.string "I'll have to try harder, too!$"

BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName:
	.string "Oh, is that right?\p"
	.string "If you saw your friend's name up here,\n"
	.string "I bet it would make you work harder!$"

BattleFrontier_RankingHall_Text_MyNamesNotUpThere:
	.string "Hmm…\n"
	.string "My name's not up there…\p"
	.string "Well, it's only natural since I haven't\n"
	.string "taken any challenges yet.$"

