MtChimney_CableCarStation_MapScripts::

MtChimney_CableCarStation_OnTransition:

MtChimney_CableCarStation_EventScript_MoveAttendantAside::

MtChimney_CableCarStation_OnFrame:

MtChimney_CableCarStation_EventScript_ExitCableCar::

MtChimney_CableCarStation_EventScript_Attendant::

MtChimney_CableCarStation_EventScript_RideCableCar::

MtChimney_CableCarStation_EventScript_DeclineRide::

MtChimney_CableCarStation_Movement_LeadPlayerToCableCar:

MtChimney_CableCarStation_Movement_FollowPlayerOutFromCableCar:

MtChimney_CableCarStation_Movement_BoardCableCar:

MtChimney_CableCarStation_Movement_ExitCableCar:

MtChimney_CableCarStation_Text_CableCarReadyGetOn:
	.string "The CABLE CAR is ready to go down.\n"
	.string "Would you like to be on it?$"

MtChimney_CableCarStation_Text_StepThisWay:
	.string "Please step this way.$"

MtChimney_CableCarStation_Text_RideAnotherTime:
	.string "Please ride with us another time.$"

