EverGrandeCity_PokemonLeague_1F_MapScripts::

EverGrandeCity_PokemonLeague_1F_OnTransition:

EverGrandeCity_PokemonLeague_1F_EventScript_GuardsBlockDoor::

EverGrandeCity_PokemonLeague_1F_EventScript_Nurse::

EverGrandeCity_PokemonLeague_1F_EventScript_Clerk::

EverGrandeCity_PokemonLeague_1F_Pokemart:

@ The door guards only check for FLAG_GARBAGEFLAG because Winonas badge is the only one that can be skipped
@ Its assumed the player has the remaining badges
EverGrandeCity_PokemonLeague_1F_EventScript_DoorGuard::

EverGrandeCity_PokemonLeague_1F_EventScript_PlayerMoveToFrontFromRight::

EverGrandeCity_PokemonLeague_1F_EventScript_PlayerMoveToFrontFromLeft::

EverGrandeCity_PokemonLeague_1F_EventScript_NotAllBadges::

EverGrandeCity_PokemonLeague_1F_EventScript_GoForth::

EverGrandeCity_PokemonLeague_1F_Movement_MoveToFrontFromRight:

EverGrandeCity_PokemonLeague_1F_Movement_MoveToFrontFromLeft:

EverGrandeCity_PokemonLeague_1F_Movement_LeftGuardOutOfWay:

EverGrandeCity_PokemonLeague_1F_Movement_RightGuardOutOfWay:

EverGrandeCity_PokemonLeague_1F_Text_MustHaveAllGymBadges:
	.string "Beyond this point, only those TRAINERS\n"
	.string "who have collected all the GYM BADGES\l"
	.string "are permitted to enter.\p"
	.string "TRAINER, let us confirm that you have\n"
	.string "all the GYM BADGES.$"

EverGrandeCity_PokemonLeague_1F_Text_HaventObtainedAllBadges:
	.string "You haven't obtained all the BADGES.\p"
	.string "If you're bound for the POKéMON\n"
	.string "LEAGUE, you must return with them.$"

EverGrandeCity_PokemonLeague_1F_Text_GoForth:
	.string "TRAINER! Believe in yourself and your\n"
	.string "POKéMON, and go forth!$"

