NewMauville_Entrance_MapScripts::

NewMauville_Entrance_OnLoad:

NewMauville_Entrance_EventScript_CloseDoor::

NewMauville_Entrance_OnTransition:

NewMauville_Entrance_EventScript_Door::

NewMauville_Entrance_EventScript_DontOpenDoor::

NewMauville_Entrance_Text_DoorIsLocked:
	.string "The door is locked.$"

NewMauville_Entrance_Text_UseBasementKey:
	.string "Use the BASEMENT KEY?$"

NewMauville_Entrance_Text_UsedBasementKey:
	.string "{PLAYER} used the BASEMENT KEY.\p"
	.string "The door opened!$"

