LilycoveCity_PokemonCenter_1F_MapScripts::

LilycoveCity_PokemonCenter_1F_OnTransition:

@ SetLilycoveLadyGfx returns TRUE if its the Contest Lady
LilycoveCity_PokemonCenter_1F_EventScript_SetLilycoveLadyGfx::

LilycoveCity_PokemonCenter_1F_EventScript_HideContestLadyMon::

LilycoveCity_PokemonCenter_1F_EventScript_ShowContestLadyMon::

LilycoveCity_PokemonCenter_1F_EventScript_Nurse::

LilycoveCity_PokemonCenter_1F_EventScript_Boy::

LilycoveCity_PokemonCenter_1F_EventScript_Maniac::

LilycoveCity_PokemonCenter_1F_EventScript_ManiacBadTeamGone::

LilycoveCity_PokemonCenter_1F_Text_HowManyKindsOfPokemon:
	.string "I wonder how many kinds of POKéMON\n"
	.string "there are in the world.\p"
	.string "It'd be great to cross seas and\n"
	.string "trade POKéMON with people far away.$"

LilycoveCity_PokemonCenter_1F_Text_HeardAboutRottenScoundrels:
	.string "I've been hearing about some rotten\n"
	.string "scoundrels who steal POKéMON and rip\l"
	.string "off METEORITES.$"

LilycoveCity_PokemonCenter_1F_Text_HaventSeenRottenScoundrels:
	.string "Those rotten scoundrels who steal\n"
	.string "POKéMON and rip off METEORITES…\p"
	.string "I haven't seen them around recently.$"

