EverGrandeCity_PhoebesRoom_MapScripts::

EverGrandeCity_PhoebesRoom_OnWarp:

EverGrandeCity_PhoebesRoom_EventScript_PlayerTurnNorth::

EverGrandeCity_PhoebesRoom_OnFrame:

EverGrandeCity_PhoebesRoom_EventScript_WalkInCloseDoor::

EverGrandeCity_PhoebesRoom_OnLoad:

EverGrandeCity_PhoebesRoom_EventScript_ResetAdvanceToNextRoom::

EverGrandeCity_PhoebesRoom_EventScript_CloseDoor::

EverGrandeCity_PhoebesRoom_EventScript_Phoebe::

EverGrandeCity_PhoebesRoom_EventScript_PostBattleSpeech::

EverGrandeCity_PhoebesRoom_EventScript_Defeated::

EverGrandeCity_PhoebesRoom_Text_IntroSpeech:
	.string "Ahahaha!\p"
	.string "I'm PHOEBE of the ELITE FOUR.\n"
	.string "I did my training on MT. PYRE.\p"
	.string "While I trained, I gained the ability\n"
	.string "to commune with GHOST-type POKéMON.\p"
	.string "Yes, the bond I developed with POKéMON\n"
	.string "is extremely tight.\p"
	.string "So, come on, just try and see if you can\n"
	.string "even inflict damage on my POKéMON!$"

EverGrandeCity_PhoebesRoom_Text_Defeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

EverGrandeCity_PhoebesRoom_Text_PostBattleSpeech:
	.string "There's a definite bond between you\n"
	.string "and your POKéMON, too.\p"
	.string "I didn't recognize it, so it's only\n"
	.string "natural that I lost.\p"
	.string "Yup, I'd like to see how far your bond\n"
	.string "will carry you.\p"
	.string "Go ahead, move on to the next room.$"

