LilycoveCity_ContestLobby_MapScripts::

@ Some scripts for this room are split into data/scripts/contest_hall and data/scripts/berry_blender

LilycoveCity_ContestLobby_OnTransition:

LilycoveCity_ContestLobby_EventScript_TryShowBlendMaster::

LilycoveCity_ContestLobby_EventScript_ShowBlendMaster::

LilycoveCity_ContestLobby_OnFrame:

LilycoveCity_ContestLobby_EventScript_TryDoContestArtist::

LilycoveCity_ContestLobby_EventScript_ContestArtist::

LilycoveCity_ContestLobby_EventScript_TakePaintingToMuseum::

LilycoveCity_ContestLobby_EventScript_ConfirmDontTakePainting::

LilycoveCity_ContestLobby_EventScript_ReceivedArtistRibbon::

LilycoveCity_ContestLobby_EventScript_UpdateMuseumPatrons::

LilycoveCity_ContestLobby_EventScript_ShowPatron1::

LilycoveCity_ContestLobby_EventScript_ShowPatron2::

LilycoveCity_ContestLobby_EventScript_ShowPatron3::

LilycoveCity_ContestLobby_EventScript_ShowPatron4::

LilycoveCity_ContestLobby_EventScript_ShowTourists::

LilycoveCity_ContestLobby_EventScript_SetPaintingFlag::

LilycoveCity_ContestLobby_EventScript_MadeCoolPainting::

LilycoveCity_ContestLobby_EventScript_MadeBeautyPainting::

LilycoveCity_ContestLobby_EventScript_MadeCutePainting::

LilycoveCity_ContestLobby_EventScript_MadeSmartPainting::

LilycoveCity_ContestLobby_EventScript_MadeToughPainting::

LilycoveCity_ContestLobby_Movement_ArtistApproachPlayer:

LilycoveCity_ContestLobby_Movement_ArtistExit:

LilycoveCity_ContestLobby_Movement_PlayerFaceArtist:

LilycoveCity_ContestLobby_Movement_ArtistBeginToExit:

LilycoveCity_ContestLobby_Movement_ArtistReturnToPlayer:

LilycoveCity_ContestLobby_EventScript_TryDoLinkContestArtist::

LilycoveCity_ContestLobby_EventScript_LinkContestArtist::

LilycoveCity_ContestLobby_EventScript_TakePaintingToMuseumLink::

LilycoveCity_ContestLobby_EventScript_ConfirmDontTakePaintingLink::

LilycoveCity_ContestLobby_EventScript_ReceivedLinkArtistRibbon::

LilycoveCity_ContestLobby_Movement_LinkArtistApproachPlayer:

LilycoveCity_ContestLobby_Movement_LinkArtistExit:

LilycoveCity_ContestLobby_Movement_PlayerFaceLinkArtist:

LilycoveCity_ContestLobby_Movement_LinkArtistBeginExit:

LilycoveCity_ContestLobby_Movement_LinkArtistReturnToPlayer:

@ EventScript_SpeakToContestReceptionist either ends or returns after a contest entry is submitted
LilycoveCity_ContestLobby_EventScript_ContestReceptionist::

LilycoveCity_ContestLobby_EventScript_SetContestType::

LilycoveCity_ContestLobby_EventScript_SetNormalContestType::

LilycoveCity_ContestLobby_EventScript_SetSuperContestType::

LilycoveCity_ContestLobby_EventScript_SetHyperContestType::

LilycoveCity_ContestLobby_EventScript_SetMasterContestType::

@ Functionally unused
LilycoveCity_ContestLobby_EventScript_SetDebug::

LilycoveCity_ContestLobby_EventScript_WarpToContestHall::

LilycoveCity_ContestLobby_EventScript_WarpToCoolContestHall::

LilycoveCity_ContestLobby_EventScript_WarpToBeautyContestHall::

LilycoveCity_ContestLobby_EventScript_WarpToCuteContestHall::

LilycoveCity_ContestLobby_EventScript_WarpToSmartContestHall::

LilycoveCity_ContestLobby_EventScript_WarpToToughContestHall::

LilycoveCity_ContestLobby_EventScript_LeadToContestHall::

LilycoveCity_ContestLobby_Movement_PlayerWalkToContestHall:

LilycoveCity_ContestLobby_Movement_PlayerApproachReceptionist:

LilycoveCity_ContestLobby_Movement_ReceptionistApproachCounter:

LilycoveCity_ContestLobby_Movement_ReceptionistExitCounter:

LilycoveCity_ContestLobby_Movement_ReceptionistWalkToContestHall:

LilycoveCity_ContestLobby_Movement_ReceptionistFacePlayer:

LilycoveCity_ContestLobby_EventScript_BlackBelt::

LilycoveCity_ContestLobby_EventScript_Girl::

LilycoveCity_ContestLobby_EventScript_Artist::

LilycoveCity_ContestLobby_EventScript_FatMan::

LilycoveCity_ContestLobby_EventScript_Fisherman::

LilycoveCity_ContestLobby_EventScript_NinjaBoy::

LilycoveCity_ContestLobby_EventScript_ContestWinner1::

LilycoveCity_ContestLobby_EventScript_ContestWinner2::

LilycoveCity_ContestLobby_EventScript_ContestWinner3::

LilycoveCity_ContestLobby_EventScript_ContestWinner4::

LilycoveCity_ContestLobby_EventScript_ContestWinner5::

LilycoveCity_ContestLobby_EventScript_ContestWinner6::

LilycoveCity_ContestLobby_EventScript_Blender3Boy::

LilycoveCity_ContestLobby_EventScript_Blender3Girl::

LilycoveCity_ContestLobby_EventScript_BerryBlenderSpeedRecords::

LilycoveCity_ContestLobby_EventScript_LinkContestResults::

LilycoveCity_ContestLobby_EventScript_BlendMaster::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker1::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker2::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker3::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker4::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker5::

LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker6::

LilycoveCity_ContestLobby_EventScript_FaceOriginalDirection::

LilycoveCity_ContestLobby_EventScript_LinkContestReceptionist::

LilycoveCity_ContestLobby_EventScript_AskEnterLinkContest::

LilycoveCity_ContestLobby_EventScript_TryEnterLinkContest::

LilycoveCity_ContestLobby_EventScript_EmeraldMode::

LilycoveCity_ContestLobby_EventScript_GlobalMode::

LilycoveCity_ContestLobby_EventScript_ChooseLinkContestType::

LilycoveCity_ContestLobby_EventScript_LinkContestInfo::

LilycoveCity_ContestLobby_EventScript_ExplainLinkContest::

LilycoveCity_ContestLobby_EventScript_ExplainEMode::

LilycoveCity_ContestLobby_EventScript_ExplainGMode::

LilycoveCity_ContestLobby_EventScript_CancelLinkContest::

LilycoveCity_ContestLobby_EventScript_ChooseLinkContestMon::

LilycoveCity_ContestLobby_EventScript_LinkCantEnterLowRank::

LilycoveCity_ContestLobby_EventScript_LinkCantEnterEgg::

LilycoveCity_ContestLobby_EventScript_LinkCantEnterFainted::

LilycoveCity_ContestLobby_EventScript_EnterMonForLinkContest::

LilycoveCity_ContestLobby_EventScript_TrySetUpLinkContest::

LilycoveCity_ContestLobby_EventScript_TryLinkEMode::

LilycoveCity_ContestLobby_EventScript_TryLinkGMode::

LilycoveCity_ContestLobby_EventScript_CancelLinkDifferentContest::

LilycoveCity_ContestLobby_EventScript_CancelLinkDifferentChoices::

LilycoveCity_ContestLobby_EventScript_CancelLinkModeDifference::

LilycoveCity_ContestLobby_EventScript_CancelLinkError::

LilycoveCity_ContestLobby_EventScript_CancelLinkNoWirelessGMode::

LilycoveCity_ContestLobby_EventScript_CancelLinkTransmissionError::

LilycoveCity_ContestLobby_EventScript_StartLinkContest::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupType::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupCoolContest::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupBeautyContest::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupCuteContest::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupSmartContest::

LilycoveCity_ContestLobby_EventScript_SetLinkGroupToughContest::

LilycoveCity_ContestLobby_EventScript_DecideLinkLeader::

LilycoveCity_ContestLobby_EventScript_TryLeadGroup::

LilycoveCity_ContestLobby_EventScript_TryJoinGroup::

LilycoveCity_ContestLobby_EventScript_TryBecomeLinkLeader::

LilycoveCity_ContestLobby_EventScript_TryJoinLinkGroup::

LilycoveCity_ContestLobby_EventScript_LinkLeaderDecided::

LilycoveCity_ContestLobby_EventScript_LeadToLinkContestHall::

LilycoveCity_ContestLobby_Movement_PlayerWalkToLinkContestHall:

LilycoveCity_ContestLobby_Movement_PlayerApproachLinkReceptionist:

LilycoveCity_ContestLobby_Movement_LinkReceptionistApproachCounter:

LilycoveCity_ContestLobby_Movement_LinkReceptionistExitCounter:

LilycoveCity_ContestLobby_Movement_LinkReceptionistWalkToContestHall:

LilycoveCity_ContestLobby_Movement_LinkReceptionistFacePlayer:

LilycoveCity_ContestLobby_EventScript_LittleGirl::

LilycoveCity_ContestLobby_EventScript_LittleGirlHaveCase::

LilycoveCity_ContestLobby_Text_LadyGaveMePokeblockCase:
	.string "Yippee!\p"
	.string "The lady at the reception counter\n"
	.string "gave me a case for {POKEBLOCK}S!$"

LilycoveCity_ContestLobby_Text_MakePokeblocksDifferentBerries:
	.string "Make {POKEBLOCK}S and put them in there.\p"
	.string "When you make a {POKEBLOCK}, everyone\n"
	.string "has to put in a different BERRY.$"

LilycoveCity_ContestLobby_Text_YourPokemonSpurredMeToPaint:
	.string "Congratulations!\p"
	.string "I did a painting of your POKéMON to\n"
	.string "commemorate its victory…\p"
	.string "Well, your POKéMON's appeals were\n"
	.string "so fantastic, it spurred me into\l"
	.string "painting better than I usually do.\l"
	.string "Look, see?$"

LilycoveCity_ContestLobby_Text_ShouldITakePaintingToMuseum:
	.string "What do you think? I'm confident in\n"
	.string "what I've done, but do you like it?\p"
	.string "A work of this caliber, it wouldn't look\n"
	.string "out of place in an art museum.\p"
	.string "Huh? An art museum really is looking\n"
	.string "for paintings?\p"
	.string "Do you think I should take this there?$"

LilycoveCity_ContestLobby_Text_IllTakePaintingToMuseum:
	.string "What, really? Then, sure, I will take\n"
	.string "this painting there right now.\p"
	.string "I'll give it a proper title, too.\p"
	.string "I hope they'll like it and consider\n"
	.string "exhibiting this.\p"
	.string "Please check if they did accept this.\n"
	.string "Thank you!$"

LilycoveCity_ContestLobby_Text_TakeMementoOfPainting:
	.string "Oh, that's right!\p"
	.string "As a memento of me painting your\n"
	.string "POKéMON, please take this.$"

LilycoveCity_ContestLobby_Text_ReceivedARibbon:
	.string "{PLAYER} received a RIBBON.$"

LilycoveCity_ContestLobby_Text_PutTheRibbonOnMon:
	.string "{PLAYER} put the RIBBON on\n"
	.string "{STR_VAR_1}.$"

LilycoveCity_ContestLobby_Text_OkaySeeYou:
	.string "Okay, see you!$"

LilycoveCity_ContestLobby_Text_TakeHomeButIdLikeToTakeToMuseum:
	.string "Oh… Then, I guess I'll just take\n"
	.string "this home with me…\p"
	.string "But, you know, I would like to take\n"
	.string "this to the art museum… Okay?$"

LilycoveCity_ContestLobby_Text_FineThatsTheWayItIs:
	.string "Oh, fine, that's the way it is.\n"
	.string "I will hang this in my own house.\p"
	.string "I'll just have to try harder next time.\n"
	.string "Well, be seeing you.$"

LilycoveCity_ContestLobby_Text_MasterRankHereICome:
	.string "Hoo, boy… Master Rank CONTESTS,\n"
	.string "here I come.\p"
	.string "The world will know that my dearest\n"
	.string "POKéMON is the cutest being in all\l"
	.string "existence. The time has come!\l"
	.string "Uheheheh.$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere:
	.string "You can see a whole variety of\n"
	.string "POKéMON here.\p"
	.string "That's why I make this place a regular\n"
	.string "part of my daily stroll.$"

LilycoveCity_ContestLobby_Text_ContestFeastForEyes:
	.string "Wow, coming out to a CONTEST is\n"
	.string "a feast for these eyes!\p"
	.string "Would you look at all the POKéMON\n"
	.string "that just scream to be painted?$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme:
	.string "The TOUGHNESS CONTEST is like\n"
	.string "extreme, man!\p"
	.string "Those muscular appeals…\n"
	.string "Cascading sweat… I swoon!$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon:
	.string "Day in and day out, I lavished my care\n"
	.string "on this POKéMON.\p"
	.string "Its condition is peaking.\n"
	.string "Today, victory is mine!$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily:
	.string "I made {POKEBLOCK}S with Mom, Dad, and\n"
	.string "Big Sister. They turned out great!\p"
	.string "I bet you can make smoother, better\n"
	.string "{POKEBLOCK}S if you have more people.$"

