SootopolisCity_House1_MapScripts::

SootopolisCity_House1_EventScript_BrickBreakBlackBelt::

SootopolisCity_House1_EventScript_ReceivedBrickBreak::

SootopolisCity_House1_EventScript_Kecleon::

SootopolisCity_House1_Text_DevelopedThisTM:
	.string "For thirty years I've remained in\n"
	.string "SOOTOPOLIS honing my skills.\p"
	.string "I developed a shattering TM.\n"
	.string "I bequeath it to you!$"

SootopolisCity_House1_Text_ExplainBrickBreak:
	.string "TM31 contains BRICK BREAK! It's a move\n"
	.string "so horrible that I can't describe it.$"

SootopolisCity_House1_Text_Kecleon:
	.string "KECLEON: Puu puhyaah.$"

