InsideOfTruck_MapScripts::

InsideOfTruck_OnLoad:

InsideOfTruck_OnResume:

InsideOfTruck_EventScript_SetIntroFlags::

InsideOfTruck_EventScript_SetIntroFlagsMale::

InsideOfTruck_EventScript_SetIntroFlagsFemale::

InsideOfTruck_EventScript_MovingBox::

InsideOfTruck_Text_BoxPrintedWithMonLogo:
	.string "The box is printed with a POKéMON logo.\p"
	.string "It's a POKéMON brand moving and\n"
	.string "delivery service.$"

