LilycoveCity_House1_MapScripts::

LilycoveCity_House1_EventScript_ExpertM::

LilycoveCity_House1_EventScript_Kecleon::

LilycoveCity_House1_Text_PokemonPartnersNotTools:
	.string "POKéMON are partners to people.\n"
	.string "They aren't our tools.\p"
	.string "Unfortunately, there are some people\n"
	.string "who fail to understand that…$"

LilycoveCity_House1_Text_Kecleon:
	.string "KECLEON: Ruroro?$"

