LittlerootTown_BrendansHouse_2F_MapScripts::

LittlerootTown_BrendansHouse_2F_OnTransition:

LittlerootTown_BrendansHouse_2F_EventScript_CheckShouldUpdateBrendanPos::

LittlerootTown_BrendansHouse_2F_EventScript_TryUpdateBrendanPos::

LittlerootTown_BrendansHouse_2F_EventScript_Ret::

LittlerootTown_BrendansHouse_2F_EventScript_CheckSetReadyToMeetBrendan::

LittlerootTown_BrendansHouse_2F_EventScript_SetReadyToMeetBrendan::

LittlerootTown_BrendansHouse_2F_OnWarp:

LittlerootTown_BrendansHouse_2F_EventScript_CheckInitDecor::

LittlerootTown_BrendansHouse_2F_EventScript_RivalsPokeBall::

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendan::

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanNorth::

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanSouth::

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanWest::

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanEast::

LittlerootTown_BrendansHouse_2F_Movement_BrendanEnters:

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerNorth:

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCNorth:

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanNorth:

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerSouth:

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCSouth:

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanSouth:

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerWest:

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCWest:

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanWest:

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerEast:

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCEast:

@ Unused, the player is already facing this direction so its unneeded
LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanEast:

LittlerootTown_BrendansHouse_2F_EventScript_PC::

LittlerootTown_BrendansHouse_2F_EventScript_CheckPlayersPC::

LittlerootTown_BrendansHouse_2F_EventScript_TurnOffPlayerPC::

LittlerootTown_BrendansHouse_2F_EventScript_CheckRivalsPC::

PlayersHouse_2F_EventScript_Notebook::

PlayersHouse_2F_EventScript_GameCube::

PlayersHouse_2F_Text_ClockIsStopped:
	.string "The clock is stopped…\p"
	.string "Better set it and start it!$"

PlayersHouse_2F_Text_HowDoYouLikeYourRoom:
	.string "MOM: {PLAYER}, how do you like your\n"
	.string "new room?\p"
	.string "Good! Everything's put away neatly!\p"
	.string "They finished moving everything in\n"
	.string "downstairs, too.\p"
	.string "POKéMON movers are so convenient!\p"
	.string "Oh, you should make sure that\n"
	.string "everything's all there on your desk.$"

PlayersHouse_2F_Text_Notebook:
	.string "{PLAYER} flipped open the notebook.\p"
	.string "ADVENTURE RULE NO. 1\n"
	.string "Open the MENU with START.\p"
	.string "ADVENTURE RULE NO. 2\n"
	.string "Record your progress with SAVE.\p"
	.string "The remaining pages are blank…$"

Common_Text_LookCloserAtMap:
	.string "{PLAYER} took a closer look at the\n"
	.string "HOENN region map.$"

PlayersHouse_2F_Text_ItsAGameCube:
	.string "It's a Nintendo GameCube.\p"
	.string "A Game Boy Advance is connected to\n"
	.string "serve as the Controller.$"
