AbandonedShip_HiddenFloorRooms_MapScripts::

AbandonedShip_HiddenFloorRooms_OnFrame:

@ After the below calculation, VAR_TEMP_4 is the room number of the door the player entered
@ Bottom row, left column   (Rm 1)
@ Bottom row, middle column (Rm 2)
@ Bottom row, right column	(Rm 3)
@ Upper row,  left column   (Rm 4)
@ Upper row,  middle column (Rm 5)
@ Upper row,  right column  (Rm 6)
AbandonedShip_HiddenFloorRooms_EventScript_DoHiddenItemSparkle::

AbandonedShip_HiddenFloorRooms_EventScript_InMiddleRoomColumn::

AbandonedShip_HiddenFloorRooms_EventScript_InRightRoomColumn::

AbandonedShip_HiddenFloorRooms_EventScript_InUpperRoomRow::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm1::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm2::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm3::

AbandonedShip_HiddenFloorRooms_EventScript_Rm3NoSparkle::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm4::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm5::

AbandonedShip_HiddenFloorRooms_EventScript_EnterRm6::

AbandonedShip_HiddenFloorRooms_EventScript_Rm1KeySparkle::

AbandonedShip_HiddenFloorRooms_EventScript_Rm2KeySparkle::

AbandonedShip_HiddenFloorRooms_EventScript_Rm4KeySparkle::

AbandonedShip_HiddenFloorRooms_EventScript_Rm6KeySparkle::

AbandonedShip_HiddenFloorRooms_EventScript_Trash::

AbandonedShip_HiddenFloorRooms_Text_BrightShinyTrash:
	.string "It's bright and shiny!\n"
	.string "But it's just trash…$"

