MossdeepCity_House2_MapScripts::

MossdeepCity_House2_EventScript_Man::

MossdeepCity_House2_EventScript_Twin::

MossdeepCity_House2_EventScript_Wingull::

MossdeepCity_House2_EventScript_WingullExitNorth::

MossdeepCity_House2_EventScript_WingullExitWest::

MossdeepCity_House2_Movement_WingullExitNorth:

MossdeepCity_House2_Movement_WingullExitEast:

MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree:
	.string "My little sister exchanges MAIL with\n"
	.string "her boyfriend in FORTREE.\p"
	.string "I don't envy her one bit at all.$"

MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth:
	.string "Even though I can't see my friend in\n"
	.string "FORTREE, my POKéMON carries MAIL\l"
	.string "back and forth for us.\p"
	.string "I'm not lonesome, even though we're\n"
	.string "apart.$"

MossdeepCity_House2_Text_Wingull:
	.string "WINGULL: Pihyoh!$"

