BattleFrontier_BattleDomePreBattleRoom_MapScripts::

BattleFrontier_BattleDomePreBattleRoom_OnWarp:

BattleFrontier_BattleDomePreBattleRoom_EventScript_TurnPlayerNorth::

BattleFrontier_BattleDomePreBattleRoom_OnFrame:

BattleFrontier_BattleDomePreBattleRoom_EventScript_EnterRoom::
BattleFrontier_BattleDomePreBattleRoom_EventScript_AskReadyForNextRound::

BattleFrontier_BattleDomePreBattleRoom_EventScript_AskReadyForNextRoundNoRecord::

BattleFrontier_BattleDomePreBattleRoom_EventScript_AskRecordBattle::

BattleFrontier_BattleDomePreBattleRoom_EventScript_RecordBattle::

BattleFrontier_BattleDomePreBattleRoom_EventScript_AskPauseChallenge::

BattleFrontier_BattleDomePreBattleRoom_EventScript_AskRetireChallenge::

BattleFrontier_BattleDomePreBattleRoom_EventScript_RetireChallenge::

BattleFrontier_BattleDomePreBattleRoom_EventScript_PauseChallenge::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ShowOpponentInfo::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ShowTourneyTree::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ShowRoundMessage::

BattleFrontier_BattleDomePreBattleRoom_EventScript_TourneyInRound1::

BattleFrontier_BattleDomePreBattleRoom_EventScript_TourneyInRound2::

BattleFrontier_BattleDomePreBattleRoom_EventScript_TourneyInSemifinals::

BattleFrontier_BattleDomePreBattleRoom_EventScript_TourneyInFinals::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ContinueChallenge::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForNextRoundMessage::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForRound1::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForRound2::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForSemifinals::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForFinals::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForTuckerSilver::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForTuckerGold::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForTuckerSilverShort::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReadyForTuckerGoldShort::

BattleFrontier_BattleDomePreBattleRoom_EventScript_ReturnFromBattle::

BattleFrontier_BattleDomePreBattleRoom_EventScript_RoundCompleteMessage::

BattleFrontier_BattleDomePreBattleRoom_EventScript_Round1Complete::

BattleFrontier_BattleDomePreBattleRoom_EventScript_Round2Complete::

BattleFrontier_BattleDomePreBattleRoom_EventScript_SemifinalsComplete::

BattleFrontier_BattleDomePreBattleRoom_Movement_AttendantMoveAside:

BattleFrontier_BattleDomePreBattleRoom_Movement_PlayerEnter:

BattleFrontier_BattleDomePreBattleRoom_Movement_PlayerWalkToDoor:

BattleFrontier_BattleDomePreBattleRoom_Movement_PlayerEnterDoor:

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForRound1:
	.string "Your 1st-round match is next.\n"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForRound2:
	.string "Your 2nd-round match is next.\n"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForSemifinals:
	.string "Your semifinal match is next.\n"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForFinals:
	.string "Your final match is next.\n"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ChooseTwoMons:
	.string "Please choose the two POKéMON\n"
	.string "that are to appear in battle.$"

BattleFrontier_BattleDomePreBattleRoom_Text_RightThisWay:
	.string "Right this way, please.$"

BattleFrontier_BattleDomePreBattleRoom_Text_RestoreMonsToFullHealth:
	.string "Thank you for competing!\p"
	.string "I'll restore your POKéMON to\n"
	.string "full health.$"

BattleFrontier_BattleDomePreBattleRoom_Text_Round1Complete:
	.string "All 1st-round matches have been\n"
	.string "completed.\p"
	.string "These are the teams that advanced!$"

BattleFrontier_BattleDomePreBattleRoom_Text_Round2Complete:
	.string "All 2nd-round matches have been\n"
	.string "completed.\p"
	.string "These are the teams that advanced!$"

BattleFrontier_BattleDomePreBattleRoom_Text_SemifinalsComplete:
	.string "All semifinal matches have been\n"
	.string "completed.\p"
	.string "These are the teams that advanced!$"

@ Unused
BattleFrontier_BattleDomePreBattleRoom_Text_CongratsReadyForRound2:
	.string "Congratulations for getting through\n"
	.string "the 1st round.\p"
	.string "The 2nd round is next.\n"
	.string "Are you ready?$"

@ Unused
BattleFrontier_BattleDomePreBattleRoom_Text_CongratsReadyForSemifinals:
	.string "Congratulations for advancing\n"
	.string "to the semifinals.\p"
	.string "The best four teams meet in this round.\n"
	.string "Are you ready?$"

@ Unused
BattleFrontier_BattleDomePreBattleRoom_Text_CongratsReadyForFinals:
	.string "Congratulations for advancing\n"
	.string "to the final match.\p"
	.string "You're one win from the championship.\n"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_PlayersNextOpponentIsTrainer:
	.string "{PLAYER}'s next opponent\n"
	.string "is this TRAINER.$"

BattleFrontier_BattleDomePreBattleRoom_Text_TourneyInRound1:
	.string "The tournament is in the 1st round.$"

BattleFrontier_BattleDomePreBattleRoom_Text_TourneyInRound2:
	.string "The tournament is in the 2nd round.$"

BattleFrontier_BattleDomePreBattleRoom_Text_TourneyInSemifinals:
	.string "The tournament is in the semifinals.$"

BattleFrontier_BattleDomePreBattleRoom_Text_TourneyInFinals:
	.string "The tournament is up to the final.$"

BattleFrontier_BattleDomePreBattleRoom_Text_SaveAndQuitGame:
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleFrontier_BattleDomePreBattleRoom_Text_RetireYourChallenge:
	.string "Would you like to retire from your\n"
	.string "Battle Tournament challenge?$"

BattleFrontier_BattleDomePreBattleRoom_Text_SavingDataPleaseWait:
	.string "I am saving your data.\n"
	.string "Please wait.$"

BattleFrontier_BattleDomePreBattleRoom_Text_RecordLastMatch:
	.string "Should I record your last match\n"
	.string "on your FRONTIER PASS?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForTuckerSilver:
	.string "Congratulations for advancing\n"
	.string "to the final match.\p"
	.string "For the final match, you will challenge\n"
	.string "the DOME ACE TUCKER.\p"
	.string "Are you ready?$"

@ Identical to ReadyForTuckerSilver
BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForTuckerGold:
	.string "Congratulations for advancing\n"
	.string "to the final match.\p"
	.string "For the final match, you will challenge\n"
	.string "the DOME ACE TUCKER.\p"
	.string "Are you ready?$"

BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForTuckerSilverShort:
	.string "Your final battle against TUCKER is\n"
	.string "next. Are you ready?$"

@ Identical again
BattleFrontier_BattleDomePreBattleRoom_Text_ReadyForTuckerGoldShort:
	.string "Your final battle against TUCKER is\n"
	.string "next. Are you ready?$"

