Route103_MapScripts::

Route103_OnTransition:

Route103_OnLoad:

Route103_EventScript_OpenAlteringCave::

Route103_EventScript_Rival::

Route103_EventScript_RivalMay::

Route103_EventScript_RivalBrendan::

Route103_EventScript_StartMayBattleTreecko::

Route103_EventScript_StartMayBattleTorchic::

Route103_EventScript_StartMayBattleMudkip::

Route103_EventScript_StartBrendanBattleTreecko::

Route103_EventScript_StartBrendanBattleTorchic::

Route103_EventScript_StartBrendanBattleMudkip::

Route103_EventScript_AfterMayBattle::

Route103_EventScript_AfterBrendanBattle::

Route103_EventScript_RivalExit::

Route103_EventScript_RivalExitFacingNorth::

Route103_EventScript_RivalExitFacingEastOrWest::

Route103_EventScript_RivalExitFacingSouth::

Route103_EventScript_RivalEnd::

Route103_Movement_RivalExitFacingNorth1:

Route103_Movement_RivalExitFacingNorth2:

Route103_Movement_WatchRivalExitFacingNorth:

Route103_Movement_RivalExit1:

Route103_Movement_RivalExit2:

Route103_Movement_WatchRivalExitFacingEastOrWest:

Route103_EventScript_Boy::

Route103_EventScript_Man::

Route103_EventScript_RouteSign::

Route103_EventScript_Daisy::

Route103_EventScript_Amy::

Route102_EventScript_AmyRegisterMatchCallAfterBattle::

Route102_EventScript_AmyRematch::

Route103_EventScript_Liv::

Route102_EventScript_LivRegisterMatchCallAfterBattle::

Route102_EventScript_LivRematch::

Route103_EventScript_Andrew::

Route103_EventScript_Miguel::

Route102_EventScript_MiguelRegisterMatchCallAfterBattle::

Route103_EventScript_MiguelRematch::

Route103_EventScript_Marcos::

Route103_EventScript_Rhett::

Route103_EventScript_Pete::

Route103_EventScript_Isabelle::

Route103_Text_MayRoute103Pokemon:
	.string "MAY: Let's see… The POKéMON found\n"
	.string "on ROUTE 103 include…$"

Route103_Text_MayLetsBattle:
	.string "Oh, hi, {PLAYER}{KUN}!\p"
	.string "…Oh, I see, my dad gave you\n"
	.string "a POKéMON as a gift.\p"
	.string "Since we're here, let's have a quick\n"
	.string "battle!\p"
	.string "I'll give you a taste of what being\n"
	.string "a TRAINER is like.$"

Route103_Text_MayDefeated:
	.string "Wow! That's great!\n"
	.string "{PLAYER}{KUN}, you're pretty good!$"

Route103_Text_MayTimeToHeadBack:
	.string "MAY: I think I know why my dad has\n"
	.string "an eye out for you now.\p"
	.string "I mean, you just got that POKéMON,\n"
	.string "but it already likes you.\p"
	.string "You might be able to befriend any\n"
	.string "kind of POKéMON easily.\p"
	.string "Well, it's time to head back to\n"
	.string "the LAB.$"

Route103_Text_BrendanRoute103Pokemon:
	.string "BRENDAN: Okay, so it's this one and\n"
	.string "that one that live on ROUTE 103…$"

Route103_Text_BrendanLetsBattle:
	.string "Hey, it's {PLAYER}!\p"
	.string "…Oh, yeah, Dad gave you a POKéMON.\p"
	.string "Since we're here, how about a little\n"
	.string "battle?\p"
	.string "I'll teach you what being a TRAINER's\n"
	.string "about!$"

Route103_Text_BrendanDefeated:
	.string "Huh, {PLAYER}, you're not too shabby.$"

Route103_Text_BrendanTimeToHeadBack:
	.string "BRENDAN: I think I get it.\n"
	.string "I think I know why my dad has his eye\l"
	.string "out for you now.\p"
	.string "Look, your POKéMON already likes you,\n"
	.string "even though you just got it.\p"
	.string "{PLAYER}, I get the feeling that you\n"
	.string "could befriend any POKéMON with ease.\p"
	.string "We should head back to the LAB.$"

Route103_Text_ShouldHaveBroughtPotion:
	.string "My POKéMON is staggeringly tired…\n"
	.string "I should have brought a POTION…$"

Route103_Text_ShortcutToOldale:
	.string "If you cross the sea from here,\n"
	.string "it'll be a shortcut to OLDALE TOWN.\p"
	.string "Fufufu, that's useful, isn't it?$"

Route103_Text_RouteSign:
	.string "ROUTE 103\n"
	.string "{DOWN_ARROW} OLDALE TOWN$"

