AbandonedShip_HiddenFloorCorridors_MapScripts::

AbandonedShip_HiddenFloorCorridors_OnResume:

AbandonedShip_HiddenFloorCorridors_OnLoad:

AbandonedShip_HiddenFloorCorridors_EventScript_UnlockRoom1::

AbandonedShip_HiddenFloorCorridors_EventScript_UnlockRoom2::

AbandonedShip_HiddenFloorCorridors_EventScript_UnlockRoom4::

AbandonedShip_HiddenFloorCorridors_EventScript_UnlockRoom6::

AbandonedShip_HiddenFloorCorridors_EventScript_LockRoom1::

AbandonedShip_HiddenFloorCorridors_EventScript_LockRoom2::

AbandonedShip_HiddenFloorCorridors_EventScript_LockRoom4::

AbandonedShip_HiddenFloorCorridors_EventScript_LockRoom6::

AbandonedShip_HiddenFloorCorridors_EventScript_Room1Door::

AbandonedShip_HiddenFloorCorridors_EventScript_Room2Door::

AbandonedShip_HiddenFloorCorridors_EventScript_Room4Door::

AbandonedShip_HiddenFloorCorridors_EventScript_Room6Door::

AbandonedShip_HiddenFloorCorridors_EventScript_Rm1IsLocked::

AbandonedShip_HiddenFloorCorridors_EventScript_Rm2IsLocked::

AbandonedShip_HiddenFloorCorridors_EventScript_Rm4IsLocked::

AbandonedShip_HiddenFloorCorridors_EventScript_Rm6IsLocked::

AbandonedShip_HiddenFloorCorridors_EventScript_TheDoorIsOpen::

AbandonedShip_HiddenFloorCorridors_Text_Rm1DoorIsLocked:
	.string "The door is locked.\p"
	.string "“RM. 1” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm2DoorIsLocked:
	.string "The door is locked.\p"
	.string "“RM. 2” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm4DoorIsLocked:
	.string "The door is locked.\p"
	.string "“RM. 4” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm6DoorIsLocked:
	.string "The door is locked.\p"
	.string "“RM. 6” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_InsertedKey:
	.string "{PLAYER} inserted and turned the\n"
	.string "KEY.\p"
	.string "The inserted KEY stuck fast,\n"
	.string "but the door opened.$"

