BattleFrontier_BattleTowerBattleRoom_MapScripts::

BattleFrontier_BattleTowerBattleRoom_OnWarp:

BattleFrontier_BattleTowerBattleRoom_EventScript_SetUpObjects::

BattleFrontier_BattleTowerBattleRoom_OnFrame:

BattleFrontier_BattleTowerBattleRoom_EventScript_EnterRoom::

BattleFrontier_BattleTowerBattleRoom_EventScript_OpponentEnter::
BattleFrontier_BattleTower_EventScript_WarpToLobbyLost::

BattleFrontier_BattleTowerBattleRoom_EventScript_DefeatedOpponent::
BattleFrontier_BattleTowerBattleRoom_EventScript_AskReadyForOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_AskReadyForOpponentNoRecord::

BattleFrontier_BattleTowerBattleRoom_EventScript_AskRecordBattle::

BattleFrontier_BattleTowerBattleRoom_EventScript_RecordBattle::

BattleFrontier_BattleTowerBattleRoom_EventScript_AskPauseChallenge::

BattleFrontier_BattleTowerBattleRoom_EventScript_AskRetireChallenge::

BattleFrontier_BattleTowerBattleRoom_EventScript_ContinueChallenge::

BattleFrontier_BattleTowerBattleRoom_EventScript_WarpToLobbyWon::

BattleFrontier_BattleTowerBattleRoom_EventScript_PauseChallenge::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyForOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor2ndOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor3rdOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor4thOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor5thOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor6thOpponent::

BattleFrontier_BattleTowerBattleRoom_EventScript_ReadyFor7thOpponent::

BattleFrontier_EventScript_IncrementWinStreak::

BattleFrontier_BattleTowerBattleRoom_EventScript_SecondAttendantEnter::

BattleFrontier_BattleTowerBattleRoom_EventScript_MaidenUpNext::
BattleFrontier_BattleTowerBattleRoom_EventScript_AskReadyForMaiden::

BattleFrontier_BattleTowerBattleRoom_EventScript_AskReadyForMaidenNoRecord::

BattleFrontier_BattleTowerBattleRoom_EventScript_BattleAnabel::
BattleFrontier_BattleTowerBattleRoom_EventScript_BattleAnabelSilver::

BattleFrontier_BattleTowerBattleRoom_EventScript_DefeatedAnabelSilver::

BattleFrontier_BattleTowerBattleRoom_EventScript_AnabelGoldIntro::
BattleFrontier_BattleTowerBattleRoom_EventScript_BattleAnabelGold::

BattleFrontier_BattleTowerBattleRoom_EventScript_DefeatedAnabelGold::

BattleFrontier_BattleTowerBattleRoom_EventScript_DoTowerBattle::
BattleFrontier_BattleTowerBattleRoom_EventScript_EndTowerBattle::

BattleFrontier_EventScript_SetBrainObjectGfx::

BattleFrontier_BattleTowerBattleRoom_Movement_PlayerEnter:

BattleFrontier_BattleTowerBattleRoom_Movement_PlayerFaceAttendant:

BattleFrontier_BattleTowerBattleRoom_Movement_PlayerFaceBattle:

BattleFrontier_BattleTowerBattleRoom_Movement_OpponentEnter:

BattleFrontier_BattleTowerBattleRoom_Movement_OpponentExit:

BattleFrontier_BattleTowerBattleRoom_Movement_AttendantApproachPlayer:

BattleFrontier_BattleTowerBattleRoom_Movement_AttendantReturnToPos:

BattleFrontier_BattleTowerBattleRoom_Movement_SetInvisible:

BattleFrontier_BattleTowerBattleRoom_Movement_SecondAttendantEnter:

BattleFrontier_BattleTowerBattleRoom_Movement_SecondAttendantExit:

BattleFrontier_BattleTowerBattleRoom_Movement_SecondAttendantDelay:

BattleFrontier_BattleTowerBattleRoom_Movement_AttendantFaceSecondAttendant:

BattleFrontier_BattleTowerBattleRoom_Movement_AnabelEnter:

BattleFrontier_BattleTowerBattleRoom_EventScript_WarpToLobby::

BattleFrontier_BattleTowerBattleRoom_EventScript_WarpToLobbyDoubles::

BattleFrontier_BattleTowerBattleRoom_EventScript_WarpToLobbyMultis::

BattleFrontier_BattleTowerBattleRoom_EventScript_WarpToLobbyLinkMultis::

BattleFrontier_BattleTowerBattleRoom_EventScript_RetireChallenge::

BattleFrontier_BattleTowerBattleRoom_Text_RestoreMonsToFullHealth:
	.string "We will restore your POKéMON to\n"
	.string "full health.$"

@ Unused
BattleFrontier_BattleTowerBattleRoom_Text_ReadyForOpponent:
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor2ndOpponent:
	.string "You will be facing opponent no. 2.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor3rdOpponent:
	.string "You will be facing opponent no. 3.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor4thOpponent:
	.string "You will be facing opponent no. 4.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor5thOpponent:
	.string "You will be facing opponent no. 5.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor6thOpponent:
	.string "You will be facing opponent no. 6.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor7thOpponent:
	.string "You will be facing opponent no. 7.\n"
	.string "Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordYourBattle:
	.string "Record your battle on your\n"
	.string "FRONTIER PASS?$"

BattleFrontier_BattleTowerLobby_Text_BattleRecordedOnPass:
	.string "{PLAYER}'s battle was recorded\n"
	.string "on the FRONTIER PASS.$"

BattleFrontier_BattleTowerBattleRoom_Text_SaveAndQuitGame:
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleFrontier_BattleTowerBattleRoom_Text_SavingPleaseWait:
	.string "Saving your battle data.\n"
	.string "Please wait.$"

BattleFrontier_BattleTowerBattleRoom_Text_CancelYourChallenge:
	.string "Would you like to cancel your BATTLE\n"
	.string "ROOM challenge?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordCouldntBeSaved::
	.string "There was an error of some sort.\n"
	.string "Your record could not be saved.$"

BattleFrontier_BattleTowerBattleRoom_Text_SalonMaidenOnHerWay:
	.string "Excuse me, but…\p"
	.string "Our leader, the SALON MAIDEN, is on\n"
	.string "her way here in hopes of battling you.\p"
	.string "She should be arriving very shortly.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyForSalonMaiden:
	.string "You will be facing the SALON MAIDEN.\n"
	.string "Are you prepared?$"

BattleFrontier_BattleTowerBattleRoom_Text_GreetingsImAnabel:
	.string "Greetings…\n"
	.string "My name is ANABEL.\p"
	.string "I am the SALON MAIDEN, and I am in\n"
	.string "charge of running the BATTLE TOWER…\p"
	.string "I have heard several rumors\n"
	.string "about you…\p"
	.string "In all honesty, what I have heard does\n"
	.string "not seem attractive in any way…\p"
	.string "The reason I've come to see you…\n"
	.string "Well, there is but one reason…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetMeSeeYourTalent:
	.string "Let me see your talent in\n"
	.string "its entirety…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelTalentShallBeRecognized:
	.string "ANABEL: Fufufu, nicely done…\p"
	.string "Your FRONTIER PASS, please…\n"
	.string "Your talent shall be recognized.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol:
	.string "The Ability Symbol was embossed on\n"
	.string "the FRONTIER PASS!$"

BattleFrontier_BattleTowerBattleRoom_Text_UntilNextTime:
	.string "… … … … … …\p"
	.string "You have confidence in your POKéMON\n"
	.string "battling talent, don't you?\p"
	.string "I urge you to keep battling and\n"
	.string "keep on winning.\p"
	.string "I will be waiting for you.\n"
	.string "Until the next time we meet…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelYouCameBack:
	.string "ANABEL: You really did come back to\n"
	.string "see me…\p"
	.string "… … … … … …\p"
	.string "You've won straight matches to see me…\n"
	.string "I won't have to hold back against you…\p"
	.string "It's been too long now…\p"
	.string "Too long since I've been able to battle\n"
	.string "without thinking about anything…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetsBeginShallWe:
	.string "Let's begin, shall we?$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelCongratsYourPassPlease:
	.string "ANABEL: Fufu, congratulations…\n"
	.string "Your FRONTIER PASS, please…$"

BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine:
	.string "The Ability Symbol took on\n"
	.string "a golden shine!$"

BattleFrontier_BattleTowerBattleRoom_Text_WishICouldBattleYouAgain:
	.string "That was fun…\p"
	.string "I have never had a POKéMON battle\n"
	.string "so enjoyable before…\p"
	.string "I wish I could battle with you again…$"

