RustboroCity_House3_MapScripts::

RustboroCity_House3_EventScript_OldMan::

RustboroCity_House3_EventScript_OldWoman::

@ Misspelling on purpose, see nickname
RustboroCity_House3_EventScript_Pekachu::

RustboroCity_House3_Text_IGivePerfectlySuitedNicknames:
	.string "For my own POKéMON, I give them\n"
	.string "perfectly suited nicknames!\p"
	.string "It's my expression of, uh…\n"
	.string "originality, yes, that's it!$"

RustboroCity_House3_Text_NamingPikachuPekachu:
	.string "But giving the name PEKACHU to\n"
	.string "a PIKACHU? It seems pointless.\p"
	.string "I suppose it is good to use a name\n"
	.string "that's easy to understand, but…$"

RustboroCity_House3_Text_Pekachu:
	.string "PEKACHU: Peka!$"

