NewMauville_Inside_MapScripts::

NewMauville_Inside_OnResume:

NewMauville_Inside_EventScript_TryRemoveVoltorb::

NewMauville_Inside_OnTransition:

NewMauville_Inside_EventScript_ShowVoltorb1::

NewMauville_Inside_EventScript_ShowVoltorb2::

NewMauville_Inside_EventScript_ShowVoltorb3::

NewMauville_Inside_OnLoad:

NewMauville_Inside_EventScript_BlueButton::

NewMauville_Inside_EventScript_GreenButton::

NewMauville_Inside_EventScript_SetBarrierStateBlueButton::

NewMauville_Inside_EventScript_SetBarrierStateGreenButton::

NewMauville_Inside_EventScript_RedButton::

NewMauville_Inside_EventScript_SetGeneratorOffMetatiles::

NewMauville_Inside_EventScript_Generator::

NewMauville_Inside_EventScript_GeneratorOff::

NewMauville_Inside_EventScript_Voltorb1::

NewMauville_Inside_EventScript_DefeatedVoltorb1::

NewMauville_Inside_EventScript_Voltorb2::

NewMauville_Inside_EventScript_DefeatedVoltorb2::

NewMauville_Inside_EventScript_Voltorb3::

NewMauville_Inside_EventScript_DefeatedVoltorb3::

NewMauville_Inside_Text_GeneratorRadiatingHeat:
	.string "The generator is radiating heat that\n"
	.string "can be felt even at a distance.\p"
	.string "It looks like it should be turned off\n"
	.string "as soon as possible.$"

NewMauville_Inside_Text_GeneratorQuietedDown:
	.string "The generator quieted down.$"

NewMauville_Inside_Text_SteppedOnSwitchGeneratorStopped:
	.string "{PLAYER} stepped on the switch.\p"
	.string "Click…\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "The generator appears to have\n"
	.string "stopped…$"
