LilycoveCity_LilycoveMuseum_1F_MapScripts::

LilycoveCity_LilycoveMuseum_1F_EventScript_Greeter::

LilycoveCity_LilycoveMuseum_1F_EventScript_Curator::

LilycoveCity_LilycoveMuseum_1F_EventScript_NotYet::

LilycoveCity_LilycoveMuseum_1F_EventScript_SawPaintings::

LilycoveCity_LilycoveMuseum_1F_EventScript_NotInterested::

LilycoveCity_LilycoveMuseum_1F_EventScript_InterestedInPaintings::

LilycoveCity_LilycoveMuseum_1F_EventScript_FollowCuratorNorth::

LilycoveCity_LilycoveMuseum_1F_EventScript_FollowCuratorWest::

LilycoveCity_LilycoveMuseum_1F_EventScript_FollowCuratorEast::

LilycoveCity_LilycoveMuseum_1F_Movement_CuratorEnterStairs:

LilycoveCity_LilycoveMuseum_1F_Movement_FollowCuratorWest:

LilycoveCity_LilycoveMuseum_1F_Movement_FollowCuratorEast:

LilycoveCity_LilycoveMuseum_1F_Movement_FollowCuratorNorth:

LilycoveCity_LilycoveMuseum_1F_EventScript_OldPainting::

LilycoveCity_LilycoveMuseum_1F_EventScript_FantasyPainting::

LilycoveCity_LilycoveMuseum_1F_EventScript_WomanPainting::

LilycoveCity_LilycoveMuseum_1F_EventScript_LegendaryPokemonPainting::

LilycoveCity_LilycoveMuseum_1F_EventScript_GrassPokemonPainting::

LilycoveCity_LilycoveMuseum_1F_EventScript_BerryPainting::

LilycoveCity_LilycoveMuseum_EventScript_BirdSculpture::

LilycoveCity_LilycoveMuseum_1F_EventScript_PokeBallSculpture::

LilycoveCity_LilycoveMuseum_1F_EventScript_StoneTablet::

LilycoveCity_LilycoveMuseum_1F_EventScript_SchoolKidM::

LilycoveCity_LilycoveMuseum_1F_EventScript_Artist1::

LilycoveCity_LilycoveMuseum_1F_EventScript_NinjaBoy::

LilycoveCity_LilycoveMuseum_1F_EventScript_Woman1::

LilycoveCity_LilycoveMuseum_1F_EventScript_Woman2::

LilycoveCity_LilycoveMuseum_1F_EventScript_PsychicM::

LilycoveCity_LilycoveMuseum_1F_EventScript_Artist2::

LilycoveCity_LilycoveMuseum_1F_EventScript_FatMan::

LilycoveCity_LilycoveMuseum_1F_Text_WelcomeToLilycoveMuseum:
	.string "Welcome to LILYCOVE MUSEUM.\p"
	.string "Please take the time to enjoy our\n"
	.string "collection of fantastic artwork\l"
	.string "featuring POKéMON.$"

LilycoveCity_LilycoveMuseum_1F_Text_ImCuratorHaveYouViewedOurPaintings:
	.string "I'm the CURATOR of this MUSEUM of\n"
	.string "fine arts.\p"
	.string "It's heartening to see someone so\n"
	.string "young as you in our MUSEUM.\p"
	.string "Have you viewed our collection of\n"
	.string "paintings already?$"

LilycoveCity_LilycoveMuseum_1F_Text_NotDisturbYouTakeYourTime:
	.string "Ah, then let me not disturb you.\n"
	.string "Please, do take your time.$"

LilycoveCity_LilycoveMuseum_1F_Text_HaveYouAnInterestInPaintings:
	.string "Oh? I do believe that you seem to\n"
	.string "be a POKéMON TRAINER.\p"
	.string "Have you an interest in paintings,\n"
	.string "too?$"

LilycoveCity_LilycoveMuseum_1F_Text_HonoredYoudVisitInSpiteOfThat:
	.string "I see…\p"
	.string "I'm honored that you would visit\n"
	.string "us in spite of that.$"

LilycoveCity_LilycoveMuseum_1F_Text_ExcellentCanYouComeWithMe:
	.string "Ah, excellent!\n"
	.string "You do like paintings!\p"
	.string "Then, may I ask you to come with me?$"

LilycoveCity_LilycoveMuseum_1F_Text_VeryOldPainting:
	.string "It's a very old painting.\n"
	.string "The paint is peeling here and there.$"

LilycoveCity_LilycoveMuseum_1F_Text_OddLandscapeFantasticScenery:
	.string "It's an odd landscape with bizarre\n"
	.string "and fantastic scenery.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfBeautifulWoman:
	.string "It's a painting of a beautiful, smiling\n"
	.string "woman with a POKéMON on her lap.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfLegendaryPokemon:
	.string "It's a painting of a legendary POKéMON\n"
	.string "from long ago.\p"
	.string "The artist painted this from\n"
	.string "imagination.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfGrassPokemon:
	.string "It's a painting of GRASS POKéMON\n"
	.string "swaying in a breeze.\p"
	.string "They appear to be enjoying the wind's\n"
	.string "gentle caress.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfBerries:
	.string "It's a delicious-looking painting\n"
	.string "of BERRIES.\p"
	.string "This painting could make you hungry!$"

LilycoveCity_LilycoveMuseum_Text_BirdPokemonSculptureReplica:
	.string "It's a replica of a famous sculpture.\p"
	.string "It depicts an ancient BIRD POKéMON.$"

LilycoveCity_LilycoveMuseum_1F_Text_BigPokeBallCarvedFromStone:
	.string "It's a big POKé BALL carved from\n"
	.string "a black stone.\p"
	.string "It was apparently used in festivals\n"
	.string "in the olden days.$"

LilycoveCity_LilycoveMuseum_1F_Text_StoneTabletWithAncientText:
	.string "It's a huge stone tablet inscribed\n"
	.string "with POKéMON and dense text in the\l"
	.string "small characters of an ancient,\l"
	.string "unreadable language.$"

LilycoveCity_LilycoveMuseum_1F_Text_WorksOfMagnificence:
	.string "Hmmm…\n"
	.string "What works of great magnificence…$"

LilycoveCity_LilycoveMuseum_1F_Text_MustntForgetLoveForFineArts:
	.string "Battling with POKéMON is fun,\n"
	.string "I'll grant you that.\p"
	.string "But one mustn't forget our love for\n"
	.string "the fine arts.$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisMuseumIsInspiration:
	.string "This ART MUSEUM… Well, you could\n"
	.string "see many fantastic paintings.\p"
	.string "And the CURATOR is a wonderful person.\p"
	.string "Among artists like myself, this MUSEUM\n"
	.string "is an inspiration.$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisLadyIsPretty:
	.string "This lady is pretty!\n"
	.string "She's like Mommy!$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisPokemonIsAdorable:
	.string "This POKéMON is adorable!\n"
	.string "Just like our little boy!$"

LilycoveCity_LilycoveMuseum_1F_Text_HeardMuseumGotNewPaintings:
	.string "I'd heard that this ART MUSEUM got\n"
	.string "in some new paintings.\p"
	.string "So, naturally I hurried over.\p"
	.string "Are the new paintings up on\n"
	.string "the second floor?$"

LilycoveCity_LilycoveMuseum_1F_Text_CuratorHasBeenCheerful:
	.string "Lately, the CURATOR has been\n"
	.string "unusually cheerful.\p"
	.string "I bet something good happened for him.\n"
	.string "Definitely.$"

LilycoveCity_LilycoveMuseum_1F_Text_AimToSeeGreatPaintings:
	.string "I aim to see many great paintings\n"
	.string "here and learn from them.\p"
	.string "I have this dream of one day having\n"
	.string "my artwork exhibited here.$"

LilycoveCity_LilycoveMuseum_1F_Text_MuseumTouristDestination:
	.string "The ART MUSEUM has become a favorite\n"
	.string "tourist destination.\p"
	.string "It's great for LILYCOVE…\n"
	.string "No, great for the HOENN region!\p"
	.string "This is what I've heard--a lone TRAINER\n"
	.string "procured all the paintings upstairs.$"

