VerdanturfTown_BattleTentLobby_MapScripts::

VerdanturfTown_BattleTentLobby_OnWarp:

VerdanturfTown_BattleTentLobby_EventScript_TurnPlayerNorth::

VerdanturfTown_BattleTentLobby_OnFrame:

VerdanturfTown_BattleTentLobby_EventScript_GetChallengeStatus::

VerdanturfTown_BattleTentLobby_EventScript_QuitWithoutSaving::

VerdanturfTown_BattleTentLobby_EventScript_WonChallenge::

VerdanturfTown_BattleTentLobby_EventScript_GivePrize::

VerdanturfTown_BattleTentLobby_EventScript_NoRoomForPrize::

VerdanturfTown_BattleTentLobby_EventScript_PrizeWaiting::

VerdanturfTown_BattleTentLobby_EventScript_LostChallenge::

VerdanturfTown_BattleTentLobby_EventScript_ResumeChallenge::

VerdanturfTown_BattleTentLobby_EventScript_Attendant::
VerdanturfTown_BattleTentLobby_EventScript_AskEnterChallenge::

VerdanturfTown_BattleTentLobby_EventScript_TryEnterChallenge::

VerdanturfTown_BattleTentLobby_EventScript_SaveBeforeChallenge::
VerdanturfTown_BattleTentLobby_EventScript_EnterChallenge::

VerdanturfTown_BattleTentLobby_EventScript_ExplainChallenge::

VerdanturfTown_BattleTentLobby_EventScript_NotEnoughValidMons::

VerdanturfTown_BattleTentLobby_EventScript_NotEnoughValidMonsLv50::

VerdanturfTown_BattleTentLobby_EventScript_NotEnoughValidMonsLvOpen::

VerdanturfTown_BattleTentLobby_EventScript_CancelChallengeSaveFailed::

VerdanturfTown_BattleTentLobby_EventScript_LoadPartyCancelChallenge::
VerdanturfTown_BattleTentLobby_EventScript_CancelChallenge::
VerdanturfTown_BattleTentLobby_EventScript_EndCancelChallenge::

VerdanturfTown_BattleTentLobby_EventScript_WalkToDoor::

VerdanturfTown_BattleTentLobby_Movement_WalkToDoor:

VerdanturfTown_BattleTentLobby_Movement_AttendantEnterDoor:

VerdanturfTown_BattleTentLobby_Movement_PlayerEnterDoor:

VerdanturfTown_BattleTentLobby_EventScript_AttractGiver::

VerdanturfTown_BattleTentLobby_EventScript_ReceivedAttract::

VerdanturfTown_BattleTentLobby_EventScript_Boy1::

VerdanturfTown_BattleTentLobby_EventScript_Boy2::

VerdanturfTown_BattleTentLobby_EventScript_Scott::

VerdanturfTown_BattleTentLobby_EventScript_ScottAlreadySpokenTo::

VerdanturfTown_BattleTentLobby_EventScript_LittleBoy::

VerdanturfTown_BattleTentLobby_EventScript_RulesBoard::

VerdanturfTown_BattleTentLobby_EventScript_ReadRulesBoard::

VerdanturfTown_BattleTentLobby_EventScript_RulesLevel::

VerdanturfTown_BattleTentLobby_EventScript_RulesBasics::

VerdanturfTown_BattleTentLobby_EventScript_RulesNature::

VerdanturfTown_BattleTentLobby_EventScript_RulesMoves::

VerdanturfTown_BattleTentLobby_EventScript_RulesUnderpowered::

VerdanturfTown_BattleTentLobby_EventScript_RulesWhenInDanger::

VerdanturfTown_BattleTentLobby_EventScript_ExitRules::

VerdanturfTown_BattleTentLobby_Text_MonsReluctantToUseDislikedMoves:
	.string "If it doesn't like a certain move,\n"
	.string "a POKéMON will be reluctant to use it.\p"
	.string "It doesn't matter how strong it is,\n"
	.string "either.\p"
	.string "For example, a POKéMON with a GENTLE\n"
	.string "nature probably won't enjoy hurting\l"
	.string "its opponents.\p"
	.string "If it can't seem to live up to its\n"
	.string "potential, it's probably failing at\l"
	.string "using a disliked move against its will.$"

VerdanturfTown_BattleTentLobby_Text_GentleMonsScaryIfAngry:
	.string "My big sister is gentle usually.\n"
	.string "But when she gets angry,\l"
	.string "she's really, really scary!\p"
	.string "I bet a gentle POKéMON will be scary\n"
	.string "if it gets angry!$"

VerdanturfTown_BattleTentLobby_Text_AttractionRunsDeep:
	.string "My feelings toward my POKéMON…\n"
	.string "The attraction runs deep…\p"
	.string "Oh, hi, you didn't see that, did you?\n"
	.string "Well, it doesn't matter.\p"
	.string "How would you like this TM for\n"
	.string "your POKéMON?$"

VerdanturfTown_BattleTentLobby_Text_AttractionMutual:
	.string "My feelings toward my POKéMON…\n"
	.string "I'm sure the attraction is mutual!\p"
	.string "They battle exactly the way I want\n"
	.string "them to!$"

VerdanturfTown_BattleTentLobby_Text_TaughtWhatKindsOfMoves:
	.string "What kind of moves have you taught\n"
	.string "your POKéMON?\p"
	.string "I think you would give yourself\n"
	.string "an advantage if they knew how to\l"
	.string "heal or protect themselves.$"

VerdanturfTown_BattleTentLobby_Text_ScottCanMeetToughTrainers:
	.string "SCOTT: Hey there, {PLAYER}{KUN}!\n"
	.string "I thought I might see you here.\p"
	.string "A BATTLE TENT's a place where\n"
	.string "you can meet tough TRAINERS.\p"
	.string "It doesn't matter what the rules are,\n"
	.string "or how battles are waged, either.\p"
	.string "{PLAYER}{KUN}, I expect you to do\n"
	.string "the best you can!$"

VerdanturfTown_BattleTentLobby_Text_ScottVisitRegularly:
	.string "SCOTT: I visit here regularly in hopes\n"
	.string "of seeing tough TRAINERS in action\l"
	.string "in whatever the situation.$"
