Route119_House_MapScripts::

Route119_House_EventScript_Woman::

Route119_House_EventScript_Wingull::

Route119_House_Text_RumorAboutCaveOfOrigin:
	.string "I heard about a cave called the CAVE\n"
	.string "OF ORIGIN.\p"
	.string "People rumor that the spirits of\n"
	.string "POKéMON are revived there. Could\l"
	.string "something like that really happen?$"

Route119_House_Text_Wingull:
	.string "WINGULL: Pihyoh!$"

