LilycoveCity_Harbor_MapScripts::

LilycoveCity_Harbor_OnTransition:

LilycoveCity_Harbor_EventScript_FerryAttendant::

@ First goto_if_eq is unnecessary; identical scripts
LilycoveCity_Harbor_EventScript_NoFirstTimeEventTickets::

LilycoveCity_Harbor_EventScript_FerryRegularLocationSelect::

LilycoveCity_Harbor_EventScript_GoToSouthernIsland::

LilycoveCity_Harbor_EventScript_GoToNavelRock::

LilycoveCity_Harbor_EventScript_GoToBirthIsland::

LilycoveCity_Harbor_EventScript_GoToFarawayIsland::

LilycoveCity_Harbor_EventScript_GoToSlateport::

LilycoveCity_Harbor_EventScript_GoToBattleFrontier::

LilycoveCity_Harbor_EventScript_GetEonTicketState::

LilycoveCity_Harbor_EventScript_GetAuroraTicketState::

LilycoveCity_Harbor_EventScript_GetOldSeaMapState::

LilycoveCity_Harbor_EventScript_GetMysticTicketState::

LilycoveCity_Harbor_EventScript_GetFirstTimeShowingTicket::

LilycoveCity_Harbor_EventScript_SetFirstTimeShowingEonTicket::

LilycoveCity_Harbor_EventScript_SetFirstTimeShowingAuroraTicket::

LilycoveCity_Harbor_EventScript_SetFirstTimeShowingOldSeaMap::

LilycoveCity_Harbor_EventScript_SetFirstTimeShowingMysticTicket::

LilycoveCity_Harbor_EventScript_GetHasTicketsState::

LilycoveCity_Harbor_EventScript_SetHasEonTicket::

LilycoveCity_Harbor_EventScript_SetHasAuroraTicket::

LilycoveCity_Harbor_EventScript_SetHasOldSeaMap::

LilycoveCity_Harbor_EventScript_SetHasMysticTicket::

LilycoveCity_Harbor_EventScript_EonTicketFirstTime::

LilycoveCity_Harbor_EventScript_GoToSouthernIslandFirstTime::

LilycoveCity_Harbor_EventScript_AuroraTicketFirstTime::

LilycoveCity_Harbor_EventScript_GoToBirthIslandFirstTime::

LilycoveCity_Harbor_EventScript_OldSeaMapFirstTime::

LilycoveCity_Harbor_EventScript_GoToFarawayIslandFirstTime::

LilycoveCity_Harbor_EventScript_MysticTicketFirstTime::

LilycoveCity_Harbor_EventScript_GoToNavelRockFirstTime::

LilycoveCity_Harbor_EventScript_MultipleEventTicketsFirstTime::

LilycoveCity_Harbor_EventScript_ExitFirstTimeTicketSailSelect::

LilycoveCity_Harbor_EventScript_GetEventTicketSailor::

LilycoveCity_Harbor_EventScript_BoardFerryWithSailor::

LilycoveCity_Harbor_EventScript_FerryUnavailable::

LilycoveCity_Harbor_EventScript_NoEventTickets::

@ Unused
LilycoveCity_Harbor_EventScript_NoTicket::

@ Unused
LilycoveCity_Harbor_EventScript_GoToSlateportUnused::

@ Unused
LilycoveCity_Harbor_EventScript_GoToBattleFrontierUnused::

LilycoveCity_Harbor_EventScript_FerryDestinationChangeMind::

LilycoveCity_Harbor_EventScript_BoardFerry::

LilycoveCity_Harbor_EventScript_PlayerBoardFerryEast::

LilycoveCity_Harbor_EventScript_PlayerBoardFerryNorth::

LilycoveCity_Harbor_EventScript_ExitSailSelect::

LilycoveCity_Harbor_Movement_PlayerBoardFerryEast:

LilycoveCity_Harbor_Movement_PlayerBoardFerryNorth:

LilycoveCity_Harbor_Movement_UnusedBoardFerry:

LilycoveCity_Harbor_EventScript_Sailor::

LilycoveCity_Harbor_EventScript_SailorFerryAvailable::

LilycoveCity_Harbor_EventScript_MoveSailorOutOfWayNorth::

LilycoveCity_Harbor_EventScript_MoveSailorOutOfWayEast::

LilycoveCity_Harbor_Movement_SailorOutOfWayNorth:

LilycoveCity_Harbor_Movement_SailorOutOfWayEast:

LilycoveCity_Harbor_EventScript_BrineyFaceSailorNorth::

LilycoveCity_Harbor_EventScript_BrineyFaceSailorEast::

LilycoveCity_Harbor_EventScript_BrineyFacePlayerNorth::

LilycoveCity_Harbor_EventScript_BrineyFacePlayerEast::

LilycoveCity_Harbor_EventScript_BoardFerryWithBrineyAndSailorNorth::

LilycoveCity_Harbor_EventScript_BoardFerryWithBrineyAndSailorEast::

LilycoveCity_Harbor_Movement_BrineyBoardFerry:

LilycoveCity_Harbor_Movement_PlayerBoardWithBrineyNorth:

LilycoveCity_Harbor_Movement_SailorBoardWithBrineyNorth:

LilycoveCity_Harbor_Movement_PlayerBoardWithBrineyEast:

LilycoveCity_Harbor_Movement_SailorBoardWithBrineyEast:

LilycoveCity_Harbor_Text_FerryUnavailable:
	.string "I beg your pardon?\n"
	.string "You're looking for a ship?\p"
	.string "I'm sorry, the ferry service isn't\n"
	.string "available at present…$"

LilycoveCity_Harbor_Text_MayISeeYourTicket:
	.string "Hello, are you here for the ferry?\n"
	.string "May I see your TICKET?$"

LilycoveCity_Harbor_Text_NoTicket:
	.string "{PLAYER} doesn't have the TICKET…\p"
	.string "I'm terribly sorry.\p"
	.string "You must have a TICKET to board\n"
	.string "the ferry.$"

LilycoveCity_Harbor_Text_FlashTicketWhereTo:
	.string "{PLAYER} flashed the TICKET.\p"
	.string "Perfect! That's all you need!\p"
	.string "And where would you like to go?$"

LilycoveCity_Harbor_Text_SailAnotherTime:
	.string "Please sail with us another time!$"

LilycoveCity_Harbor_Text_SlateportItIs:
	.string "SLATEPORT CITY it is, then!$"

LilycoveCity_Harbor_Text_BattleFrontierItIs:
	.string "BATTLE FRONTIER it is, then!$"

LilycoveCity_Harbor_Text_PleaseBoard:
	.string "Please board the ferry and wait for\n"
	.string "departure.$"

LilycoveCity_Harbor_Text_WhereWouldYouLikeToGo:
	.string "Then, where would you like to go?$"

LilycoveCity_Harbor_Text_SailorFerryUnavailable:
	.string "Until they finish making the ferry,\n"
	.string "we sailors have nothing to do…\p"
	.string "I wish they'd get a move on, the folks\n"
	.string "at the SHIPYARD in SLATEPORT.$"

LilycoveCity_Harbor_Text_SailorFerryAvailable:
	.string "The ferry S.S. TIDAL is finally in\n"
	.string "operation.\p"
	.string "The folks at the SHIPYARD in SLATEPORT\n"
	.string "must've worked extra hard.\p"
	.string "Well, it's my turn to get busy now!$"
