LilycoveCity_House2_MapScripts::

LilycoveCity_House2_EventScript_FatMan::

LilycoveCity_House2_EventScript_ReceivedRest::

LilycoveCity_House2_Text_NotAwakeYetHaveThis:
	.string "Huh? What? What's that?\p"
	.string "I'm not near awake yet…\n"
	.string "You can have this…$"

LilycoveCity_House2_Text_SleepIsEssential:
	.string "Yawn…\p"
	.string "Sleep is essential for good health…\n"
	.string "Sleep and regain health…$"
