BattleFrontier_BattlePikeThreePathRoom_MapScripts::

BattleFrontier_BattlePikeThreePathRoom_OnFrame:

BattleFrontier_BattlePikeThreePathRoom_OnWarp:

BattleFrontier_BattlePikeThreePathRoom_EventScript_TurnPlayerNorth::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GetChallengeStatus::

BattleFrontier_BattlePikeThreePathRoom_EventScript_WarpToLobby::

BattleFrontier_BattlePikeThreePathRoom_EventScript_ResumeChallenge::

BattleFrontier_BattlePikeThreePathRoom_EventScript_Attendant::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom1::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom3::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom5::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom7::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom9::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom11::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AttendantRoom13::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AskContinueChallenge::

BattleFrontier_BattlePikeThreePathRoom_EventScript_PauseChallenge::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AskSaveChallenge::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AskRetireChallenge::

BattleFrontier_BattlePikeThreePathRoom_EventScript_SetHintRoom::

BattleFrontier_BattlePikeThreePathRoom_EventScript_SetPikeQueenHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GivePikeQueenHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_HintGiver::

BattleFrontier_BattlePikeThreePathRoom_EventScript_DeclineHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_AcceptHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GiveLeftRoomHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GiveCenterRoomHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GiveRightRoomHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GiveHint::

BattleFrontier_BattlePikeThreePathRoom_EventScript_HintNostalgia::

BattleFrontier_BattlePikeThreePathRoom_EventScript_HintWhispering::

BattleFrontier_BattlePikeThreePathRoom_EventScript_HintPokemon::

BattleFrontier_BattlePikeThreePathRoom_EventScript_HintPeople::

BattleFrontier_BattlePikeThreePathRoom_EventScript_GiveBrainHint::

BattleFrontier_BattlePikeThreePathRoom_Movement_HintGiverApproachPlayer:

BattleFrontier_BattlePikeThreePathRoom_Movement_HintGiverReturnToPos:

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom1:
	.string "You are currently in\n"
	.string "the 1st room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom3:
	.string "You are currently in\n"
	.string "the 3rd room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom5:
	.string "You are currently in\n"
	.string "the 5th room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom7:
	.string "You are currently in\n"
	.string "the 7th room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom9:
	.string "You are currently in\n"
	.string "the 9th room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom11:
	.string "You are currently in\n"
	.string "the 11th room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom13:
	.string "You are currently in\n"
	.string "the 13th room…$"

BattleFrontier_BattlePikeThreePathRoom_Text_ContinueWithChallenge:
	.string "Will you continue with\n"
	.string "your challenge?$"

BattleFrontier_BattlePikeThreePathRoom_Text_SaveChallengeAndQuit:
	.string "Would you like to save your challenge\n"
	.string "and quit the game for now?$"

BattleFrontier_BattlePikeThreePathRoom_Text_RetireFromChallenge:
	.string "Do you wish to retire from your\n"
	.string "Battle Choice challenge?$"

BattleFrontier_BattlePikeThreePathRoom_Text_AwaitingReturnSaveBeforeResume:
	.string "We've been awaiting your return…\p"
	.string "Before resuming your Battle Choice\n"
	.string "challenge, let me save the game…$"

BattleFrontier_BattlePikeThreePathRoom_Text_PleaseEnjoyChallenge:
	.string "Please do enjoy your Battle Choice\n"
	.string "challenge…$"

BattleFrontier_BattlePikeThreePathRoom_Text_SavingYourData:
	.string "I am saving your data…\n"
	.string "A little time, please…$"

BattleFrontier_BattlePike_Text_PathBlockedNoTurningBack:
	.string "The path is blocked!\n"
	.string "And there is no turning back…$"

BattleFrontier_BattlePikeThreePathRoom_Text_FindingItDifficultToChoose:
	.string "I beg your pardon, but…\p"
	.string "Are you perhaps finding it difficult\n"
	.string "to choose your path?$"

BattleFrontier_BattlePikeThreePathRoom_Text_ApologizeForImpertinence:
	.string "I see…\n"
	.string "I apologize for my impertinence…$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutRightPath:
	.string "Ah, let me see… There is something\n"
	.string "about the path on the right…$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutCenterPath:
	.string "Ah, let me see… There is something\n"
	.string "about the path in the center…$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutLeftPath:
	.string "Ah, let me see… There is something\n"
	.string "about the path on the left…$"

BattleFrontier_BattlePikeThreePathRoom_Text_AromaOfPokemon:
	.string "It seems to have the distinct aroma\n"
	.string "of POKéMON wafting around it…$"

BattleFrontier_BattlePikeThreePathRoom_Text_PresenceOfPeople:
	.string "Is it… A TRAINER?\n"
	.string "I sense the presence of people…$"

BattleFrontier_BattlePikeThreePathRoom_Text_HeardWhispering:
	.string "I seem to have heard something…\n"
	.string "It may have been whispering…$"

BattleFrontier_BattlePikeThreePathRoom_Text_WaveOfNostaliga:
	.string "For some odd reason, I felt a wave\n"
	.string "of nostalgia coming from it…$"

BattleFrontier_BattlePikeThreePathRoom_Text_TerrifyingEvent:
	.string "I am sorry to say…\p"
	.string "A terrifying event, yes, a horrible one,\n"
	.string "is about to befall you…\p"
	.string "I urge you to pay the utmost care\n"
	.string "and prepare for the worst…$"

BattleFrontier_BattlePikeThreePathRoom_Text_DreadfulPresence:
	.string "From every path I sense a dreadful\n"
	.string "presence…$"
