Route106_MapScripts::

Route106_EventScript_TrainerTipsSign::

Route106_EventScript_Douglas::

Route106_EventScript_Kyla::

Route106_EventScript_Elliot::

Route106_EventScript_ElliotRegisterMatchCallAfterBattle::

Route106_EventScript_ElliotRematch::

Route106_EventScript_Ned::

Route106_Text_TrainerTips:
	.string "TRAINER TIPS\p"
	.string "Advice on catching POKéMON with a ROD:\n"
	.string "Press the A Button if you get a bite.$"

