DesertRuins_MapScripts::

DesertRuins_OnResume:

DesertRuins_EventScript_TryRemoveRegirock::

DesertRuins_OnLoad:

DesertRuins_EventScript_HideRegiEntrance::

DesertRuins_OnTransition:

DesertRuins_EventScript_ShowRegirock::

DesertRuins_EventScript_CaveEntranceMiddle::

DesertRuins_EventScript_BigHoleInWall::

DesertRuins_EventScript_CaveEntranceSide::

DesertRuins_EventScript_Regirock::

DesertRuins_EventScript_DefeatedRegirock::

DesertRuins_EventScript_RanFromRegirock::

