OldaleTown_MapScripts::

OldaleTown_OnTransition:

@ This script seems pointless because nothing uses VAR_OLDALE_TOWN_STATE
OldaleTown_EventScript_SetOldaleState::

OldaleTown_EventScript_BlockWestEntrance::

OldaleTown_EventScript_MoveMartEmployee::

OldaleTown_EventScript_TownSign::

OldaleTown_EventScript_Girl::

OldaleTown_EventScript_MartEmployee::

OldaleTown_EventScript_GoToMartSouth::

OldaleTown_EventScript_GoToMartNorth::

OldaleTown_EventScript_GoToMartEast::

OldaleTown_EventScript_ExplainPokemonMart::

OldaleTown_EventScript_ExplainPotion::

OldaleTown_EventScript_BagIsFull::

OldaleTown_Movement_EmployeeEast:

OldaleTown_Movement_EmployeeSouth:

OldaleTown_Movement_EmployeeNorth:

OldaleTown_Movement_Unknown1:

OldaleTown_Movement_PlayerEast:

OldaleTown_Movement_PlayerSouth:

OldaleTown_Movement_PlayerNorth:

OldaleTown_Movement_Unknown2:

OldaleTown_EventScript_FootprintsMan::

OldaleTown_EventScript_BlockedPath::

OldaleTown_EventScript_NotBlockingPath::

OldaleTown_EventScript_Rival::

OldaleTown_EventScript_RivalTrigger1::

OldaleTown_EventScript_RivalTrigger2::

OldaleTown_EventScript_RivalTrigger3::

OldaleTown_EventScript_ShowRivalMessage::

OldaleTown_EventScript_ShowMayMessage::

OldaleTown_EventScript_ShowBrendanMessage::

OldaleTown_EventScript_RivalFinish::

OldaleTown_EventScript_DoExitMovement1::

OldaleTown_EventScript_DoExitMovement2::

OldaleTown_Movement_RivalApproachPlayer1:

OldaleTown_Movement_RivalApproachPlayer2:

OldaleTown_Movement_RivalApproachPlayer3:

OldaleTown_Movement_RivalExit:

OldaleTown_Movement_WatchRivalExit:

OldaleTown_Movement_PlayerStepBack:

OldaleTown_Movement_BackUp:

OldaleTown_Movement_ReturnToOriginalPosition:

OldaleTown_Text_SavingMyProgress:
	.string "I want to take a rest, so I'm saving my\n"
	.string "progress.$"

OldaleTown_Text_IWorkAtPokemonMart:
	.string "Hi!\n"
	.string "I work at a POKéMON MART.\p"
	.string "Can I get you to come with me?$"

OldaleTown_Text_ThisIsAPokemonMart:
	.string "This is a POKéMON MART.\n"
	.string "Just look for our blue roof.\p"
	.string "We sell a variety of goods including\n"
	.string "POKé BALLS for catching POKéMON.\p"
	.string "Here, I'd like you to have this as\n"
	.string "a promotional item.$"

OldaleTown_Text_PotionExplanation:
	.string "A POTION can be used anytime, so it's\n"
	.string "even more useful than a POKéMON CENTER\l"
	.string "in certain situations.$"

OldaleTown_Text_WaitDontComeInHere:
	.string "Aaaaah! Wait!\n"
	.string "Please don't come in here.\p"
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_DiscoveredFootprints:
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_FinishedSketchingFootprints:
	.string "I finished sketching the footprints of\n"
	.string "a rare POKéMON.\p"
	.string "But it turns out they were only my\n"
	.string "own footprints…$"

OldaleTown_Text_MayLetsGoBack:
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Over here!\l"
	.string "Let's hurry home!$"

OldaleTown_Text_BrendanLetsGoBack:
	.string "BRENDAN: I'm heading back to my dad's\n"
	.string "LAB now.\l"
	.string "{PLAYER}, you should hustle back, too.$"

OldaleTown_Text_TownSign:
	.string "OLDALE TOWN\n"
	.string "“Where things start off scarce.”$"

