MossdeepCity_PokemonCenter_2F_MapScripts::

@ The below 3 are unused and leftover from RS
MossdeepCity_PokemonCenter_2F_EventScript_Colosseum::

MossdeepCity_PokemonCenter_2F_EventScript_TradeCenter::

MossdeepCity_PokemonCenter_2F_EventScript_RecordCorner::

MossdeepCity_PokemonCenter_2F_EventScript_Woman5::

MossdeepCity_PokemonCenter_2F_Text_Woman5:
	.string "If I win a whole lot of link battles\n"
	.string "and show everyone how good I am,\l"
	.string "I might get a fan following!$"

