Route121_MapScripts::

Route121_EventScript_Woman::

Route121_EventScript_MtPyrePierSign::

Route121_EventScript_SafariZoneSign::

Route121_EventScript_AquaGruntsMoveOut::

Route121_Movement_Grunt1Exit:

Route121_Movement_Grunt2Exit:

Route121_Movement_Grunt3Exit:

Route121_EventScript_Vanessa::

Route121_EventScript_Walter::

Route121_EventScript_RegisterWalter::

Route121_EventScript_RematchWalter::

Route121_EventScript_Tammy::

Route121_EventScript_Kate::

Route121_EventScript_Joy::

Route121_EventScript_Jessica::

Route121_EventScript_RegisterJessica::

Route121_EventScript_RematchJessica::

Route121_EventScript_Cale::

Route121_EventScript_Myles::

Route121_EventScript_Pat::

Route121_EventScript_Marcel::

Route121_EventScript_Cristin::

Route121_EventScript_RegisterCristin::

Route121_EventScript_RematchCristin::

Route121_Text_OkayMoveOutToMtPyre:
	.string "Okay!\n"
	.string "We're to move out to MT. PYRE!$"

Route121_Text_AheadLoomsMtPyre:
	.string "Ahead looms MT. PYRE…\p"
	.string "It is a natural monument to the spirits \n"
	.string "of departed POKéMON…$"

Route121_Text_MtPyrePierSign:
	.string "MT. PYRE PIER\p"
	.string "…The sign is old and worn out.\n"
	.string "The words are barely legible…$"

Route121_Text_SafariZoneSign:
	.string "“Filled with rare POKéMON!”\n"
	.string "SAFARI ZONE$"

