PetalburgCity_MapScripts::

PetalburgCity_OnTransition:

PetalburgCity_EventScript_MoveGymBoyToWestEntrance::

PetalburgCity_EventScript_DisableMapNameAndMusic::

PetalburgCity_EventScript_SetGymDoorsUnlocked::

PetalburgCity_OnFrame:

PetalburgCity_EventScript_WallyTutorial::

PetalburgCity_EventScript_WalkToWallyHouse::

PetalburgCity_EventScript_Boy::

PetalburgCity_EventScript_WallysMom::

PetalburgCity_Movement_WalkToWallyHousePlayer:

PetalburgCity_Movement_WalkInsideHousePlayer:

PetalburgCity_Movement_WalkToWallyHouseWallysDad:

PetalburgCity_Movement_WalkInsideHouseWallysDad:

PetalburgCity_Movement_WallyTutorialPlayer:

PetalburgCity_Movement_WallyTutorialWally:

PetalburgCity_EventScript_GymSign::

PetalburgCity_EventScript_CitySign::

PetalburgCity_EventScript_Gentleman::

PetalburgCity_EventScript_WallyHouseSign::

PetalburgCity_EventScript_ShowGymToPlayer0::

PetalburgCity_EventScript_ShowGymToPlayer1::

PetalburgCity_EventScript_ShowGymToPlayer2::

PetalburgCity_EventScript_ShowGymToPlayer3::

PetalburgCity_EventScript_ShowGymToPlayer::

PetalburgCity_EventScript_BoyApproachPlayer0::

PetalburgCity_EventScript_BoyApproachPlayer1::

PetalburgCity_EventScript_BoyApproachPlayer2::

PetalburgCity_EventScript_BoyApproachPlayer3::

PetalburgCity_EventScript_LeadPlayerToGym0::

PetalburgCity_EventScript_LeadPlayerToGym1::

PetalburgCity_EventScript_LeadPlayerToGym2::

PetalburgCity_EventScript_LeadPlayerToGym3::

@ Unused
PetalburgCity_Movement_Delay48::

PetalburgCity_Movement_BoyApproachPlayer0:

PetalburgCity_Movement_BoyApproachPlayer1:

PetalburgCity_Movement_BoyApproachPlayer2:

PetalburgCity_Movement_BoyApproachPlayer3:

PetalburgCity_Movement_BoyWalkToGym0:

PetalburgCity_Movement_BoyWalkToGym1:

PetalburgCity_Movement_BoyWalkToGym2:

PetalburgCity_Movement_BoyWalkToGym3:

PetalburgCity_Movement_BoyWalkAway:

PetalburgCity_Movement_PlayerWalkToGym0:

PetalburgCity_Movement_PlayerWalkToGym1:

PetalburgCity_Movement_PlayerWalkToGym2:

PetalburgCity_Movement_PlayerWalkToGym3:

PetalburgCity_EventScript_Scott0::

PetalburgCity_EventScript_Scott1::

PetalburgCity_EventScript_Scott2::

PetalburgCity_EventScript_Scott3::

PetalburgCity_EventScript_Scott::

PetalburgCity_EventScript_ScottExit0::

PetalburgCity_EventScript_ScottExit1::

PetalburgCity_EventScript_ScottExit2::

PetalburgCity_EventScript_ScottExit3::

PetalburgCity_Movement_ScottStartWalkLeft:

PetalburgCity_Movement_ScottApproachPlayer:

PetalburgCity_Movement_ScottExit0:

PetalburgCity_Movement_PlayerWatchScottExit0:

PetalburgCity_Movement_ScottExit1:

PetalburgCity_Movement_PlayerWatchScottExit1:

PetalburgCity_Movement_ScottExit2:

PetalburgCity_Movement_PlayerWatchScottExit2:

PetalburgCity_Movement_ScottExit3:

PetalburgCity_Movement_PlayerWatchScottExit3:

PetalburgCity_EventScript_GymBoy::

PetalburgCity_Text_WhereIsWally:
	.string "Where has our WALLY gone?\p"
	.string "We have to leave for VERDANTURF TOWN\n"
	.string "very soon…$"

PetalburgCity_Text_AreYouRookieTrainer:
	.string "Hiya! Are you maybe…\n"
	.string "A rookie TRAINER?\p"
	.string "Do you know what POKéMON TRAINERS\n"
	.string "do when they reach a new town?\p"
	.string "They first check what kind of GYM\n"
	.string "is in the town.$"

PetalburgCity_Text_ThisIsPetalburgGym:
	.string "See? This is PETALBURG CITY's GYM.$"

PetalburgCity_Text_ThisIsGymSign:
	.string "This is the GYM's sign. Look for it\n"
	.string "whenever you're looking for a GYM.$"

PetalburgCity_Text_WaterReflection:
	.string "My face is reflected in the water.\p"
	.string "It's a shining grin full of hope…\p"
	.string "Or it could be a look of somber silence\n"
	.string "struggling with fear…\p"
	.string "What do you see reflected in your face?$"

PetalburgCity_Text_FullPartyExplanation:
	.string "Let's say you have six POKéMON.\n"
	.string "If you catch another one…\p"
	.string "It is automatically sent to a STORAGE\n"
	.string "BOX over a PC connection.$"

PetalburgCity_Text_GymSign:
	.string "PETALBURG CITY POKéMON GYM\n"
	.string "LEADER: NORMAN\l"
	.string "“A man in pursuit of power!”$"

PetalburgCity_Text_CitySign:
	.string "PETALBURG CITY\n"
	.string "“Where people mingle with nature.”$"

PetalburgCity_Text_WallyHouseSign:
	.string "WALLY'S HOUSE$"

PetalburgCity_Text_AreYouATrainer:
	.string "Excuse me!\p"
	.string "Let me guess, from the way you're\n"
	.string "dressed, are you a POKéMON TRAINER?$"

PetalburgCity_Text_WellMaybeNot:
	.string "… … … … … …\p"
	.string "Well, maybe not.\n"
	.string "Your clothes aren't all that dirty.\p"
	.string "You're either a rookie TRAINER,\n"
	.string "or maybe you're just an ordinary kid.$"

PetalburgCity_Text_ImLookingForTalentedTrainers:
	.string "I'm roaming the land in search of\n"
	.string "talented TRAINERS.\p"
	.string "I'm sorry to have taken your time.$"
