Route114_MapScripts::

Route114_OnTransition:

Route114_OnLoad:

Route114_OnFrame:

Route114_EventScript_Man::

Route114_EventScript_ReceivedBerry::

Route114_EventScript_RoarGentleman::

Route114_EventScript_ReceivedRoar::

Route114_EventScript_Poochyena::

Route114_EventScript_MeteorFallsSign::

Route114_EventScript_FossilManiacsHouseSign::

Route114_EventScript_LanettesHouseSign::

Route114_EventScript_Lenny::

Route114_EventScript_Lucas::

Route114_EventScript_Shane::

Route114_EventScript_Nancy::

Route114_EventScript_Steve::

Route114_EventScript_RegisterSteve::

Route114_EventScript_RematchSteve::

Route114_EventScript_Bernie::

Route114_EventScript_RegisterBernie::

Route114_EventScript_RematchBernie::

Route114_EventScript_Claude::

Route114_EventScript_Nolan::

Route114_EventScript_Tyra::

Route114_EventScript_Ivy::

Route114_EventScript_Angelina::

Route114_EventScript_Charlotte::

Route114_EventScript_Kai::

Route114_Text_AllMyMonDoesIsRoarTakeThis:
	.string "All my POKéMON does is ROAR…\n"
	.string "No one dares to come near me…\p"
	.string "Sigh… If you would, please take\n"
	.string "this TM away…$"

Route114_Text_ExplainRoar:
	.string "TM05 contains ROAR.\n"
	.string "A ROAR sends POKéMON scurrying.$"

Route114_Text_Poochyena:
	.string "Bow! Bowwow!$"

Route114_Text_MeteorFallsSign:
	.string "METEOR FALLS\n"
	.string "RUSTBORO CITY THROUGH HERE$"

Route114_Text_FossilManiacsHouseSign:
	.string "FOSSIL MANIAC'S HOUSE\n"
	.string "“Fossils gratefully accepted!”$"

Route114_Text_LanettesHouse:
	.string "LANETTE'S HOUSE$"

