Route118_MapScripts::

Route118_OnTransition:

Route118_OnLoad:

Route118_OnFrame:

Route118_EventScript_GoodRodFisherman::

Route118_EventScript_ReceiveGoodRod::

Route118_EventScript_DeclineGoodRod::

Route118_EventScript_ReceivedGoodRod::

Route118_EventScript_Girl::

Route118_EventScript_RouteSignMauville::

Route118_EventScript_RouteSign119::

Route118_EventScript_StevenTrigger0::

Route118_EventScript_StevenTrigger1::

Route118_EventScript_StevenTrigger2::

Route118_EventScript_StevenTrigger::

Route118_EventScript_StevenExit0::

Route118_EventScript_StevenExit1::

Route118_EventScript_StevenExit2::

Route118_Movement_PlayerWatchStevenExit:

Route118_Movement_StevenApproachLedge0:

Route118_Movement_StevenApproachLedge2:

Route118_Movement_StevenJumpLedge:

Route118_Movement_StevenExit0:

Route118_Movement_StevenExit1:

Route118_Movement_StevenExit2:

Route118_EventScript_Rose::

Route118_EventScript_RegisterRose::

Route118_EventScript_RematchRose::

Route118_EventScript_Barny::

Route118_EventScript_Wade::

Route118_EventScript_Dalton::

Route118_EventScript_RegisterDalton::

Route118_EventScript_RematchDalton::

Route118_EventScript_Perry::

Route118_EventScript_Chester::

Route118_EventScript_Deandre::

Route118_Text_StevenQuestions:
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "It's me, STEVEN!\n"
	.string "We met in the cave near DEWFORD.\p"
	.string "Have you met many kinds of POKéMON\n"
	.string "since I last saw you?\p"
	.string "There are many, many kinds of POKéMON\n"
	.string "in this wide world of ours.\p"
	.string "If you wanted to raise only your\n"
	.string "favorites, that's fine.\p"
	.string "Perhaps you find it more fun to raise\n"
	.string "all sorts of POKéMON.\p"
	.string "As a TRAINER of POKéMON,\n"
	.string "what do you think?\p"
	.string "Of course, it's not any of my business.\p"
	.string "It would be nice if we were to meet\n"
	.string "again somewhere.$"

Route118_Text_YouAgreeGoodRodIsGood:
	.string "Hmm!\n"
	.string "A GOOD ROD is really good!\p"
	.string "Wouldn't you agree?$"

Route118_Text_IdenticalMindsTakeThis:
	.string "Hmm!\n"
	.string "We're of identical minds!\p"
	.string "Hmm!\n"
	.string "Take this GOOD ROD!$"

Route118_Text_TryYourLuckFishing:
	.string "Wherever there's water, try your luck\n"
	.string "at fishing.$"

Route118_Text_DontYouLikeToFish:
	.string "Don't you like to fish?$"

Route118_Text_TryCatchingMonWithGoodRod:
	.string "Try catching all sorts of POKéMON\n"
	.string "with your GOOD ROD.$"

Route118_Text_CanCrossRiversWithSurf:
	.string "Even if there isn't a boat, you can\n"
	.string "cross rivers and the sea if you have\l"
	.string "a POKéMON that knows SURF.\p"
	.string "POKéMON can be counted on to do so\n"
	.string "much!$"

Route118_Text_RouteSignMauville:
	.string "ROUTE 118\n"
	.string "{LEFT_ARROW} MAUVILLE CITY$"

Route118_Text_RouteSign119:
	.string "ROUTE 118\n"
	.string "{UP_ARROW} ROUTE 119$"

