LilycoveCity_DepartmentStore_4F_MapScripts::

LilycoveCity_DepartmentStore_4F_EventScript_Gentleman::

LilycoveCity_DepartmentStore_4F_EventScript_Woman::

LilycoveCity_DepartmentStore_4F_EventScript_Youngster::

LilycoveCity_DepartmentStore_4F_EventScript_ClerkLeft::

LilycoveCity_DepartmentStore_4F_Pokemart_AttackTMs:

LilycoveCity_DepartmentStore_4F_EventScript_ClerkRight::

LilycoveCity_DepartmentStore_4F_Pokemart_DefenseTMs:

LilycoveCity_DepartmentStore_4F_Text_AttackOrDefenseTM:
	.string "Hmm…\p"
	.string "An attacking move…\n"
	.string "Or a defensive move…\p"
	.string "It's no easy matter to decide which TM\n"
	.string "moves should be taught to POKéMON…$"

LilycoveCity_DepartmentStore_4F_Text_FiftyDifferentTMs:
	.string "There are so many different kinds of\n"
	.string "TM moves.\p"
	.string "A catalog I read said there are fifty\n"
	.string "different kinds.$"

LilycoveCity_DepartmentStore_4F_Text_PokemonOnlyHaveFourMoves:
	.string "I'd like to get all the different TMs,\n"
	.string "but a POKéMON learns only four moves.$"

