BattleFrontier_BattlePalaceCorridor_MapScripts::

BattleFrontier_BattlePalaceCorridor_OnFrame:

BattleFrontier_BattlePalaceCorridor_EventScript_WalkThroughCorridor::

BattleFrontier_BattlePalaceCorridor_EventScript_WalkToOpenBattleRoom::
BattleFrontier_BattlePalaceCorridor_EventScript_WarpToBattleRoom::

BattleFrontier_BattlePalaceCorridor_EventScript_RandomComment1::

BattleFrontier_BattlePalaceCorridor_EventScript_RandomComment2::

BattleFrontier_BattlePalaceCorridor_EventScript_RandomComment3::

BattleFrontier_BattlePalaceCorridor_EventScript_StreakComment::

BattleFrontier_BattlePalaceCorridor_EventScript_LongStreakComment::

BattleFrontier_BattlePalaceCorridor_Movement_EnterCorridor:

BattleFrontier_BattlePalaceCorridor_Movement_AttendantWalkTo50BattleRoom:

BattleFrontier_BattlePalaceCorridor_Movement_PlayerWalkTo50BattleRoom:

BattleFrontier_BattlePalaceCorridor_Movement_AttendantWalkToOpenBattleRoom:

BattleFrontier_BattlePalaceCorridor_Movement_PlayerWalkToOpenBattleRoom:

BattleFrontier_BattlePalaceCorridor_Movement_PlayerEnterBattleRoom:
BattleFrontier_BattlePalaceCorridor_Movement_AttendantEnterBattleRoom:

BattleFrontier_BattlePalaceCorridor_Text_PeopleAndMonAreSame:
	.string "People and POKéMON, they are but\n"
	.string "the same…\p"
	.string "Their individual nature makes them\n"
	.string "good at certain things, and not good\l"
	.string "at others.$"

BattleFrontier_BattlePalaceCorridor_Text_LetMonDoWhatItLikes:
	.string "Rather than trying to make a POKéMON\n"
	.string "do what it dislikes, try to let it do\l"
	.string "what it likes and is good at doing.\p"
	.string "Put yourself in the POKéMON's position\n"
	.string "and consider what moves it would like.$"

BattleFrontier_BattlePalaceCorridor_Text_MonDifferentWhenCornered:
	.string "A POKéMON's nature is a remarkable\n"
	.string "thing…\p"
	.string "Some POKéMON behave in a completely\n"
	.string "different way when they are cornered.$"

BattleFrontier_BattlePalaceCorridor_Text_BeginningToUnderstandNature:
	.string "Are you beginning to understand how\n"
	.string "a POKéMON's nature makes it behave?$"

BattleFrontier_BattlePalaceCorridor_Text_HeartfeltBondBetweenYouAndMons:
	.string "Ah… I see a strong, heartfelt bond\n"
	.string "between you and your POKéMON…$"

