DewfordTown_PokemonCenter_1F_MapScripts::

DewfordTown_PokemonCenter_1F_OnTransition:

DewfordTown_PokemonCenter_1F_EventScript_Nurse::

DewfordTown_PokemonCenter_1F_EventScript_PokefanF::

DewfordTown_PokemonCenter_1F_EventScript_Man::

DewfordTown_PokemonCenter_1F_Text_StoneCavern:
	.string "There's a stone cavern at the edge\n"
	.string "of town.\p"
	.string "I've heard you can find rare stones\n"
	.string "there.$"

DewfordTown_PokemonCenter_1F_Text_FaintedMonCanUseHM:
	.string "Even if a POKéMON faints and can't\n"
	.string "battle, it can still use a move learned\l"
	.string "from a HIDDEN MACHINE (HM).$"

