BirthIsland_Exterior_MapScripts::

BirthIsland_Exterior_OnReturnToField:

BirthIsland_Exterior_OnTransition:

BirthIsland_Exterior_EventScript_HideDeoxysAndPuzzle::

BirthIsland_Exterior_EventScript_TryShowDeoxysPuzzle::

BirthIsland_Exterior_OnResume:

BirthIsland_Exterior_EventScript_TryRemoveDeoxys::

BirthIsland_Exterior_EventScript_Triangle::

@ The actual rock triangle movement is handled by DoDeoxysRockInteraction.
@ Unless the player has solved the puzzle and needs to encounter Deoxys,
@ there's nothing else the script needs to do.
BirthIsland_Exterior_EventScript_Failed::

BirthIsland_Exterior_EventScript_Progressed::

BirthIsland_Exterior_EventScript_Complete::

BirthIsland_Exterior_EventScript_Deoxys::

BirthIsland_Exterior_EventScript_DefeatedDeoxys::

BirthIsland_Exterior_EventScript_RanFromDeoxys::

BirthIsland_Exterior_Movement_DeoxysApproach:
