Route113_MapScripts::

Route113_OnResume:

Route113_OnTransition:

Route113_EventScript_CheckSetAshWeather::

Route113_EventScript_DontSetAshWeather::

Route113_EventScript_Gentleman::

Route113_EventScript_NinjaBoy::

Route113_EventScript_RouteSign111::

Route113_EventScript_RouteSignFallarbor::

Route113_EventScript_GlassWorkshopSign::

Route113_EventScript_TrainerTipsRegisterKeyItems::

Route113_EventScript_Jaylen::

Route113_EventScript_Dillon::

Route113_EventScript_Madeline::

Route113_EventScript_RegisterMadeline::

Route113_EventScript_RematchMadeline::

Route113_EventScript_Lao::

Route113_EventScript_RegisterLao::

Route113_EventScript_RematchLao::

Route113_EventScript_Lung::

Route113_EventScript_Tori::

Route113_EventScript_Tia::

Route113_EventScript_Sophie::

Route113_EventScript_Coby::

Route113_EventScript_Lawrence::

Route113_EventScript_Wyatt::

Route113_Text_AshCanBeFashionedIntoGlass:
	.string "Wahahaha! Today's technology is a\n"
	.string "wondrous thing!\p"
	.string "Take this volcanic ash here.\n"
	.string "It can be fashioned into glass.$"

Route113_Text_FunWalkingThroughAsh:
	.string "It's fun walking through the volcano's\n"
	.string "ashes on the ground and grass.\p"
	.string "You can see where you walked--it's\n"
	.string "really neat!$"

Route113_Text_RouteSign111:
	.string "ROUTE 113\n"
	.string "{RIGHT_ARROW} ROUTE 111$"

Route113_Text_RouteSignFallarbor:
	.string "ROUTE 113\n"
	.string "{LEFT_ARROW} FALLARBOR TOWN$"

Route113_Text_TrainerTipsRegisterKeyItems:
	.string "TRAINER TIPS\p"
	.string "You may register one of the KEY ITEMS\n"
	.string "in your BAG as SELECT.\p"
	.string "Simply press SELECT to use\n"
	.string "the registered item conveniently.$"

Route113_Text_GlassWorkshopSign:
	.string "GLASS WORKSHOP\n"
	.string "“Turning Volcanic Ash into Glass Items”$"

