FallarborTown_BattleTentLobby_MapScripts::

FallarborTown_BattleTentLobby_OnWarp:

FallarborTown_BattleTentLobby_EventScript_TurnPlayerNorth::

FallarborTown_BattleTentLobby_OnFrame:

FallarborTown_BattleTentLobby_EventScript_GetChallengeStatus::

FallarborTown_BattleTentLobby_EventScript_QuitWithoutSaving::

FallarborTown_BattleTentLobby_EventScript_WonChallenge::

FallarborTown_BattleTentLobby_EventScript_GivePrize::

FallarborTown_BattleTentLobby_EventScript_NoRoomForPrize::

FallarborTown_BattleTentLobby_EventScript_PrizeWaiting::

FallarborTown_BattleTentLobby_EventScript_LostChallenge::

FallarborTown_BattleTentLobby_EventScript_ResumeChallenge::

FallarborTown_BattleTentLobby_EventScript_Attendant::
FallarborTown_BattleTentLobby_EventScript_AskEnterChallenge::

FallarborTown_BattleTentLobby_EventScript_TryEnterChallenge::

FallarborTown_BattleTentLobby_EventScript_SaveBeforeChallenge::
FallarborTown_BattleTentLobby_EventScript_EnterChallenge::

FallarborTown_BattleTentLobby_EventScript_ExplainChallenge::

FallarborTown_BattleTentLobby_EventScript_NotEnoughValidMons::
FallarborTown_BattleTentLobby_EventScript_NotEnoughValidMonsLv50::

FallarborTown_BattleTentLobby_EventScript_NotEnoughValidMonsLvOpen::

FallarborTown_BattleTentLobby_EventScript_CancelChallengeSaveFailed::

FallarborTown_BattleTentLobby_EventScript_LoadPartyCancelChallenge::
FallarborTown_BattleTentLobby_EventScript_CancelChallenge::
FallarborTown_BattleTentLobby_EventScript_EndCancelChallenge::

FallarborTown_BattleTentLobby_EventScript_WalkToDoor::

FallarborTown_BattleTentLobby_Movement_AttendantWalkToDoor:

FallarborTown_BattleTentLobby_Movement_AttendantEnterDoor:

FallarborTown_BattleTentLobby_Movement_PlayerWalkToDoor:

FallarborTown_BattleTentLobby_Movement_PlayerEnterDoor:

FallarborTown_BattleTentLobby_EventScript_Hiker::

FallarborTown_BattleTentLobby_EventScript_LittleBoy::

FallarborTown_BattleTentLobby_EventScript_Lass::

FallarborTown_BattleTentLobby_EventScript_Scott::

FallarborTown_BattleTentLobby_EventScript_ScottAlreadySpokenTo::

FallarborTown_BattleTentLobby_EventScript_RulesBoard::

FallarborTown_BattleTentLobby_EventScript_ReadRulesBoard::

FallarborTown_BattleTentLobby_EventScript_RulesLevel::

FallarborTown_BattleTentLobby_EventScript_RulesBattle::

FallarborTown_BattleTentLobby_EventScript_RulesMind::

FallarborTown_BattleTentLobby_EventScript_RulesSkill::

FallarborTown_BattleTentLobby_EventScript_RulesBody::

FallarborTown_BattleTentLobby_EventScript_ExitRules::

FallarborTown_BattleTentLobby_Text_MakeThinkImJustKid:
	.string "Fufufufufu.\p"
	.string "I'm going to make everyone think\n"
	.string "I'm just a kid and let them play down.\p"
	.string "Then, I'll shock them and grab\n"
	.string "the title!$"

FallarborTown_BattleTentLobby_Text_FallarborTentMyFavorite:
	.string "You know how BATTLE TENTS offer\n"
	.string "different events in different towns?\p"
	.string "My favorite is definitely the BATTLE\n"
	.string "TENT in FALLARBOR TOWN.\p"
	.string "I think it's fantastic how TRAINERS\n"
	.string "try to win with all their faith in\l"
	.string "their POKéMON.$"

FallarborTown_BattleTentLobby_Text_CameToCampOut:
	.string "I heard something about some tent,\n"
	.string "so I came to camp out.\p"
	.string "I didn't know that tents these days\n"
	.string "are so luxurious!\p"
	.string "Since I'm here, I may as well try\n"
	.string "my hand at battling!$"

FallarborTown_BattleTentLobby_Text_ScottLookingForSomeone:
	.string "SCOTT: Hi, {PLAYER}{KUN}!\n"
	.string "So you came out to this BATTLE TENT!\p"
	.string "The people in these parts tend to be\n"
	.string "easygoing and laid-back.\p"
	.string "But, you see, what I'm looking for are\n"
	.string "people with…\p"
	.string "How should I say this?\p"
	.string "Someone bursting with the desire\n"
	.string "and the drive to win.\p"
	.string "If there were a TRAINER like that,\n"
	.string "I'd immediately…\p"
	.string "Whoops! Never mind!\n"
	.string "Keep working at it!$"

FallarborTown_BattleTentLobby_Text_ScottMakeChallenge:
	.string "SCOTT: Instead of wasting your\n"
	.string "time with the likes of me, why not\l"
	.string "make a challenge?$"

