OldaleTown_Mart_MapScripts::

OldaleTown_Mart_EventScript_Clerk::

OldaleTown_Mart_Pokemart_Basic:

OldaleTown_Mart_ExpandedItems::

OldaleTown_Mart_Pokemart_Expanded:

OldaleTown_Mart_EventScript_Woman::

OldaleTown_Mart_EventScript_PokeBallsInStock::

OldaleTown_Mart_EventScript_Boy::

OldaleTown_Mart_Text_PokeBallsAreSoldOut:
	.string "The clerk says they're all sold out.\n"
	.string "I can't buy any POKé BALLS.$"

OldaleTown_Mart_Text_ImGoingToBuyPokeBalls:
	.string "I'm going to buy a bunch of POKé BALLS\n"
	.string "and catch a bunch of POKéMON!$"

OldaleTown_Mart_Text_RestoreHPWithPotion:
	.string "If a POKéMON gets hurt and loses its HP\n"
	.string "and faints, it won't be able to battle.\p"
	.string "To prevent your POKéMON from fainting,\n"
	.string "restore its HP with a POTION.$"

