SkyPillar_Top_MapScripts::

SkyPillar_Top_OnResume:

SkyPillar_Top_EventScript_TryRemoveRayquaza::

SkyPillar_Top_OnTransition:

SkyPillar_Top_EventScript_SetCleanLayout::

SkyPillar_Top_EventScript_TryShowRayquaza::

SkyPillar_Top_EventScript_ShowRayquaza::

SkyPillar_Top_OnWarp:

SkyPillar_Top_EventScript_RayquazaFaceDown::

SkyPillar_Top_EventScript_Rayquaza::

SkyPillar_Top_EventScript_DefeatedRayquaza::

SkyPillar_Top_EventScript_RanFromRayquaza::

SkyPillar_Top_EventScript_DefeatedRayquaza2::

SkyPillar_Top_EventScript_RanFromRayquaza2::

SkyPillar_Top_EventScript_AwakenRayquaza::

@ Rayquaza has unusual movement frames
@ See comments, or sAnimTable_Rayquaza
SkyPillar_Top_Movement_RayquazaStir:

SkyPillar_Top_Movement_RayquazaFlyOff:

SkyPillar_Top_Movement_CameraPanUp:

SkyPillar_Top_Movement_CameraPanDown:

SkyPillar_Top_Text_RayquazaFlewOff:
	.string "The awakened RAYQUAZA flew off…$"

