LilycoveCity_DepartmentStore_2F_MapScripts::

LilycoveCity_DepartmentStore_2F_EventScript_Cook::

LilycoveCity_DepartmentStore_2F_EventScript_PokefanF::

LilycoveCity_DepartmentStore_2F_EventScript_Sailor::

LilycoveCity_DepartmentStore_2F_EventScript_ClerkLeft::

LilycoveCity_DepartmentStore_2F_Pokemart1:

LilycoveCity_DepartmentStore_2F_EventScript_ClerkRight::

LilycoveCity_DepartmentStore_2F_Pokemart2:

LilycoveCity_DepartmentStore_2F_Text_LearnToUseItemsProperly:
	.string "Learn to use items properly.\n"
	.string "That's basic, really.$"

LilycoveCity_DepartmentStore_2F_Text_GoodGiftForHusband:
	.string "My husband is waiting at home.\n"
	.string "What would make a good gift for him?$"

LilycoveCity_DepartmentStore_2F_Text_StockUpOnItems:
	.string "I'm leaving on a long journey soon.\n"
	.string "I need to stock up on items.$"

