LittlerootTown_MapScripts::






LittlerootTown_OnTransition:

LittlerootTown_EventScript_LeftLabAfterDexUpgrade::

LittlerootTown_EventScript_HideMapNamePopup::

LittlerootTown_EventScript_SetRivalLeftForRoute103::

LittlerootTown_EventScript_MoveRivalFromOldale::

LittlerootTown_EventScript_SetExitedHouseAfterLatiSSTicketEvent::

LittlerootTown_EventScript_MoveMomToMaysDoor::

LittlerootTown_EventScript_SetTwinPos::

LittlerootTown_EventScript_SetTwinGuardingRoutePos::

LittlerootTown_EventScript_SetMomStandingInFrontOfDoorPos::

LittlerootTown_EventScript_SetMomInFrontOfDoorMale::

LittlerootTown_EventScript_SetMomInFrontOfDoorFemale::

LittlerootTown_OnFrame:

LittlerootTown_EventScript_StepOffTruckMale::

LittlerootTown_EventScript_StepOffTruckFemale::

LittlerootTown_EventScript_GoInsideWithMom::

LittlerootTown_Movement_MomExitHouse:

LittlerootTown_Movement_MomApproachPlayerAtTruck:

LittlerootTown_Movement_MomApproachDoor:

LittlerootTown_Movement_MomEnterHouse:

LittlerootTown_Movement_PlayerApproachDoor:

LittlerootTown_Movement_PlayerEnterHouse:

LittlerootTown_Movement_PlayerStepOffTruck:

LittlerootTown_EventScript_BeginDexUpgradeScene::

LittlerootTown_OnWarp:

LittlerootTown_EventScript_SetRivalBirchPosForDexUpgrade::

LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeMale::

LittlerootTown_EventScript_SetRivalBirchPosForDexUpgradeFemale::

LittlerootTown_EventScript_FatMan::

LittlerootTown_EventScript_Boy::

LittlerootTown_EventScript_Twin::

LittlerootTown_EventScript_GoSaveBirch::

LittlerootTown_EventScript_YouSavedBirch::

LittlerootTown_EventScript_GoodLuck::

LittlerootTown_EventScript_NeedPokemonTriggerLeft::

LittlerootTown_EventScript_DangerousWithoutPokemon::

LittlerootTown_Movement_TwinApproachPlayerLeft:

LittlerootTown_Movement_TwinPushPlayerFromRoute:

LittlerootTown_Movement_TwinReturnLeft:

LittlerootTown_Movement_PushPlayerBackFromRoute:

LittlerootTown_EventScript_NeedPokemonTriggerRight::

LittlerootTown_Movement_TwinApproachPlayerRight:

LittlerootTown_Movement_TwinReturnRight:

LittlerootTown_EventScript_GoSaveBirchTrigger::

LittlerootTown_EventScript_TownSign::

LittlerootTown_EventScript_BirchsLabSign::

LittlerootTown_EventScript_BrendansHouseSign::

LittlerootTown_EventScript_PlayersHouseSignMale::

LittlerootTown_EventScript_BirchsHouseSignFemale::

LittlerootTown_EventScript_MaysHouseSign::

LittlerootTown_EventScript_BirchsHouseSignMale::

LittlerootTown_EventScript_PlayersHouseSignFemale::

LittlerootTown_EventScript_GiveRunningShoesTrigger0::

LittlerootTown_EventScript_GiveRunningShoesTrigger1::

LittlerootTown_EventScript_GiveRunningShoesTrigger2::

LittlerootTown_EventScript_GiveRunningShoesTrigger3::

LittlerootTown_EventScript_GiveRunningShoesTrigger4::

LittlerootTown_EventScript_GiveRunningShoesTrigger5::

LittlerootTown_EventScript_GiveRunningShoesTrigger::

LittlerootTown_EventScript_SetHomeDoorCoordsMale::

LittlerootTown_EventScript_SetHomeDoorCoordsFemale::

LittlerootTown_EventScript_MomNoticePlayerMale::

LittlerootTown_EventScript_MomNoticePlayerFemale::

LittlerootTown_EventScript_MomApproachPlayerMale::

LittlerootTown_EventScript_MomApproachPlayerFemale::

LittlerootTown_EventScript_MomApproachPlayer0::

LittlerootTown_EventScript_MomApproachPlayer1::

LittlerootTown_EventScript_MomApproachPlayerMale2::

LittlerootTown_EventScript_MomApproachPlayerMale3::

LittlerootTown_EventScript_MomApproachPlayerMale4::

LittlerootTown_EventScript_MomApproachPlayerMale5::

LittlerootTown_EventScript_MomApproachPlayerFemale2::

LittlerootTown_EventScript_MomApproachPlayerFemale3::

LittlerootTown_EventScript_MomApproachPlayerFemale4::

LittlerootTown_EventScript_MomApproachPlayerFemale5::

LittlerootTown_EventScript_MomReturnHomeMale::

LittlerootTown_EventScript_MomReturnHomeFemale::

LittlerootTown_EventScript_MomReturnHome0::

LittlerootTown_EventScript_MomReturnHome1::

LittlerootTown_EventScript_MomReturnHomeMale2::

LittlerootTown_EventScript_MomReturnHomeMale3::

LittlerootTown_EventScript_MomReturnHomeMale4::

LittlerootTown_EventScript_MomReturnHomeMale5::

LittlerootTown_EventScript_MomReturnHomeFemale2::

LittlerootTown_EventScript_MomReturnHomeFemale3::

LittlerootTown_EventScript_MomReturnHomeFemale4::

LittlerootTown_EventScript_MomReturnHomeFemale5::

LittlerootTown_Movement_MomApproachPlayer0:

LittlerootTown_Movement_MomApproachPlayer1:

LittlerootTown_Movement_MomApproachPlayerMale2:

LittlerootTown_Movement_MomApproachPlayerMale3:

LittlerootTown_Movement_MomApproachPlayerMale4:

LittlerootTown_Movement_MomApproachPlayerMale5:

LittlerootTown_Movement_MomApproachPlayerFemale2:

LittlerootTown_Movement_MomApproachPlayerFemale3:

LittlerootTown_Movement_MomApproachPlayerFemale4:

LittlerootTown_Movement_MomApproachPlayerFemale5:

LittlerootTown_Movement_MomReturnHome0:

LittlerootTown_Movement_MomReturnHome1:

LittlerootTown_Movement_MomReturnHomeMale2:

LittlerootTown_Movement_MomReturnHomeMale3:

LittlerootTown_Movement_MomReturnHomeMale4:

LittlerootTown_Movement_MomReturnHomeMale5:

LittlerootTown_Movement_MomReturnHomeFemale2:

LittlerootTown_Movement_MomReturnHomeFemale3:

LittlerootTown_Movement_MomReturnHomeFemale4:

LittlerootTown_Movement_MomReturnHomeFemale5:

LittlerootTown_Movement_MomExitThroughDoor:

LittlerootTown_EventScript_Mom::

LittlerootTown_EventScript_SetReceivedRunningShoes::

LittlerootTown_EventScript_GiveRunningShoes::

LittlerootTown_Text_OurNewHomeLetsGoInside:
	.string "MOM: {PLAYER}, we're here, honey!\p"
	.string "It must be tiring riding with our things\n"
	.string "in the moving truck.\p"
	.string "Well, this is LITTLEROOT TOWN.\p"
	.string "How do you like it?\n"
	.string "This is our new home!\p"
	.string "It has a quaint feel, but it seems to be\n"
	.string "an easy place to live, don't you think?\p"
	.string "And, you get your own room, {PLAYER}!\n"
	.string "Let's go inside.$"

LittlerootTown_Text_WaitPlayer:
	.string "MOM: Wait, {PLAYER}!$"

LittlerootTown_Text_WearTheseRunningShoes:
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
	.string "introduce yourself to PROF. BIRCH?\p"
	.string "Oh! What an adorable POKéMON!\n"
	.string "You got it from PROF. BIRCH. How nice!\p"
	.string "You're your father's child, all right.\n"
	.string "You look good together with POKéMON!\p"
	.string "Here, honey! If you're going out on an\n"
	.string "adventure, wear these RUNNING SHOES.\p"
	.string "They'll put a zip in your step!$"

LittlerootTown_Text_SwitchShoesWithRunningShoes:
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"

LittlerootTown_Text_ExplainRunningShoes:
	.string "MOM: {PLAYER}, those shoes came with\n"
	.string "instructions.\p"
	.string "“Press the B Button while wearing these\n"
	.string "RUNNING SHOES to run extra-fast!\p"
	.string "“Slip on these RUNNING SHOES and race\n"
	.string "in the great outdoors!”$"

LittlerootTown_Text_ComeHomeIfAnythingHappens:
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "To think that you have your very own\n"
	.string "POKéMON now…\l"
	.string "Your father will be overjoyed.\p"
	.string "…But please be careful.\n"
	.string "If anything happens, you can come home.\p"
	.string "Go on, go get them, honey!$"

LittlerootTown_Text_CanUsePCToStoreItems:
	.string "If you use a PC, you can store items\n"
	.string "and POKéMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_BirchSpendsDaysInLab:
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out in\l"
	.string "the wild to do more research…\p"
	.string "When does PROF. BIRCH spend time\n"
	.string "at home?$"

LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut:
	.string "Um, um, um!\p"
	.string "If you go outside and go in the grass,\n"
	.string "wild POKéMON will jump out!$"

LittlerootTown_Text_DangerousIfYouDontHavePokemon:
	.string "It's dangerous if you don't have\n"
	.string "your own POKéMON.$"

LittlerootTown_Text_CanYouGoSeeWhatsHappening:
	.string "Um, hi!\p"
	.string "There are scary POKéMON outside!\n"
	.string "I can hear their cries!\p"
	.string "I want to go see what's going on,\n"
	.string "but I don't have any POKéMON…\p"
	.string "Can you go see what's happening\n"
	.string "for me?$"

LittlerootTown_Text_YouSavedBirch:
	.string "You saved PROF. BIRCH!\n"
	.string "I'm so glad!$"

LittlerootTown_Text_GoodLuckCatchingPokemon:
	.string "Are you going to catch POKéMON?\n"
	.string "Good luck!$"

LittlerootTown_Text_TownSign:
	.string "LITTLEROOT TOWN\n"
	.string "“A town that can't be shaded any hue.”$"

LittlerootTown_Text_ProfBirchsLab:
	.string "PROF. BIRCH'S POKéMON LAB$"

LittlerootTown_Text_PlayersHouse:
	.string "{PLAYER}'s HOUSE$"

LittlerootTown_Text_ProfBirchsHouse:
	.string "PROF. BIRCH'S HOUSE$"

LittlerootTown_Text_BirchSomethingToShowYouAtLab:
	.string "PROF. BIRCH: Well, well, {PLAYER}{KUN}!\n"
	.string "That was good work out there!\p"
	.string "I knew there was something special\n"
	.string "about you when I first saw you,\l"
	.string "but I never expected this.\p"
	.string "Oh, yes. Do you still have the POKéDEX\n"
	.string "I gave you?\p"
	.string "I have something to show you.\n"
	.string "Let's go to my LAB.$"

