BattleFrontier_BattleFactoryPreBattleRoom_MapScripts::

BattleFrontier_BattleFactoryPreBattleRoom_OnWarp:

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_SetUpObjects::
BattleFrontier_BattleFactoryPreBattleRoom_EventScript_TurnPlayerNorth::

BattleFrontier_BattleFactoryPreBattleRoom_OnFrame:

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_EnterRoom::
BattleFrontier_BattleFactoryPreBattleRoom_EventScript_EnterBattleRoom::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReturnToRoomFromBattle::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskReadyForOpponent::
BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskReadyForRegularOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskReadyForOpponentNoRecord::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskRecordBattle::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_RecordBattle::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskPauseChallenge::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskRetireChallenge::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskSwapMon::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_SwapMons::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor2ndOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor3rdOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor4thOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor5thOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor6thOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ReadyFor7thOpponent::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_PauseChallenge::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_ResumeChallenge::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_CommentOnOpponentType::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesNormal::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesFighting::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesFlying::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesPoison::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesGround::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesRock::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesBug::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesGhost::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesSteel::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesFire::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesWater::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesGrass::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesElectric::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesPsychic::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesIce::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesDragon::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesDark::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentUsesFairy::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_OpponentHasNoMostCommonType::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_CommentOnOpponentStyle::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleUnrestrained::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleTotalPreparation::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleSlowAndSteady::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleEndurance::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleHighRisk::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleWeakenFoe::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleImpossibleToPredict::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleDependsOnFlow::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_StyleFlexible::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskReadyForHead::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskReadyForHeadNoRecord::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_AskSwapBeforeHead::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_WalkToBattleRoomLv50::

BattleFrontier_BattleFactoryPreBattleRoom_EventScript_WalkToBattleRoomLvOpen::

BattleFrontier_BattleFactoryPreBattleRoom_Movement_PlayerEnterRoom:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_PlayerWalkToBattleRoomLv50:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_PlayerWalkToBattleRoomLvOpen:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_AttendantEnterRoom:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_GuideWalkToBattleRoomLv50:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_GuideWalkToBattleRoomLvOpen:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_AttendantMoveToReceiveCall:

BattleFrontier_BattleFactoryPreBattleRoom_Movement_AttendantReturnToPlayer:

BattleFrontier_BattleFactoryPreBattleRoom_Text_HoldMonsChooseFromSelection:
	.string "First, we will hold your POKéMON for\n"
	.string "safekeeping.\p"
	.string "You may then choose from our\n"
	.string "selection of POKéMON.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_LetUsRestoreMons:
	.string "Thank you for competing!\n"
	.string "Let us restore your POKéMON!$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor2ndOpponent:
	.string "The 2nd match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor3rdOpponent:
	.string "The 3rd match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor4thOpponent:
	.string "The 4th match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor5thOpponent:
	.string "The 5th match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor6thOpponent:
	.string "The 6th match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor7thOpponent:
	.string "Finally, the 7th match is next!\n"
	.string "Are you ready?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_SaveAndQuitGame:
	.string "Would you like to save and quit\n"
	.string "the game?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_RetireFromChallenge:
	.string "Would you like to retire from your\n"
	.string "Battle Swap challenge?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_InvestigatedUpcomingOpponent:
	.string "I've conducted a little investigation\n"
	.string "about your upcoming opponent.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInNormalType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the NORMAL type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInFireType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the FIRE type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInWaterType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the WATER type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInElectricType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the ELECTRIC type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInGrassType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the GRASS type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInIceType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the ICE type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInFightingType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the FIGHTING type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInPoisonType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the POISON type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInGroundType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the GROUND type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInFlyingType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the FLYING type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInPsychicType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the PSYCHIC type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInBugType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the BUG type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInRockType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the ROCK type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInGhostType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the GHOST type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInDragonType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the DRAGON type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInDarkType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the DARK type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInFairyType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the FAIRY type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerSkilledInSteelType:
	.string "The TRAINER is apparently skilled\n"
	.string "in the handling of the STEEL type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_TrainerHasNoClearFavorite:
	.string "The TRAINER appears to have no clear\n"
	.string "favorites when it comes to type.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleSlowAndSteady:
	.string "The favorite battle style appears to\n"
	.string "be slow and steady.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleEndurance:
	.string "The favorite battle style appears to\n"
	.string "be one of endurance.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleHighRisk:
	.string "The favorite battle style appears to\n"
	.string "be high risk, high return.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleDependsOnFlow:
	.string "The favorite battle style appears to\n"
	.string "depend on the battle's flow.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleTotalPreparation:
	.string "The favorite battle style appears to\n"
	.string "be one based on total preparation.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleWeakenFoe:
	.string "The favorite battle style appears\n"
	.string "to be weakening the foe to start.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleFlexible:
	.string "The favorite battle style appears to\n"
	.string "be flexibly adaptable to the situation.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleImpossibleToPredict:
	.string "The favorite battle style appears to\n"
	.string "be impossible to predict.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_StyleUnrestrained:
	.string "The favorite battle style appears to\n"
	.string "be free-spirited and unrestrained.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_LikeToSwapMon:
	.string "Before starting the battle, would you\n"
	.string "like to swap a POKéMON?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_YourSwapIsComplete:
	.string "Thank you!\n"
	.string "Your POKéMON swap is complete.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_RightThisWay:
	.string "Right this way, please!$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_SavingDataPleaseWait:
	.string "I am saving your data.\n"
	.string "Please wait.$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_RecordLatestBattle:
	.string "Would you like to record your latest\n"
	.string "battle on your FRONTIER PASS?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_WaitFewMoments:
	.string "Excuse me! Excuse me, please!\n"
	.string "May I get you to wait a few moments?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_UnderstoodSirWillDo:
	.string "…Uh-huh? What?! …Whoa!\n"
	.string "Understood, sir! Will do!$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_MessageFromHeadComeRightNow:
	.string "Oh, my…\n"
	.string "Sorry to keep you waiting!\p"
	.string "I have a message from this facility's\n"
	.string "boss, the FACTORY HEAD.\p"
	.string "He says, “We're going to do it!\n"
	.string "Come here right now!”$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_PreparedToFaceHead:
	.string "The FACTORY HEAD is demanding you.\n"
	.string "Are you prepared to face him?$"

BattleFrontier_BattleFactoryPreBattleRoom_Text_CantTellAnythingAboutHead:
	.string "I'm terribly sorry, but I can't tell you\n"
	.string "anything about the FACTORY HEAD.$"
